// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer7_out_dout,
        layer7_out_empty_n,
        layer7_out_read,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap,
        layer8_out_din,
        layer8_out_full_n,
        layer8_out_write,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [143:0] layer7_out_dout;
input   layer7_out_empty_n;
output   layer7_out_read;
input  [7:0] layer7_out_num_data_valid;
input  [7:0] layer7_out_fifo_cap;
output  [127:0] layer8_out_din;
input   layer8_out_full_n;
output   layer8_out_write;
input  [31:0] layer8_out_num_data_valid;
input  [31:0] layer8_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer7_out_read;
reg layer8_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_699_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer7_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    layer8_out_blk_n;
wire   [7:0] select_ln51_fu_325_p3;
reg   [7:0] select_ln51_reg_738;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [7:0] select_ln51_1_fu_349_p3;
reg   [7:0] select_ln51_1_reg_743;
wire   [7:0] select_ln51_2_fu_373_p3;
reg   [7:0] select_ln51_2_reg_748;
wire   [7:0] select_ln51_3_fu_397_p3;
reg   [7:0] select_ln51_3_reg_753;
wire   [7:0] select_ln51_4_fu_421_p3;
reg   [7:0] select_ln51_4_reg_758;
wire   [7:0] select_ln51_5_fu_445_p3;
reg   [7:0] select_ln51_5_reg_763;
wire   [7:0] select_ln51_6_fu_469_p3;
reg   [7:0] select_ln51_6_reg_768;
wire   [7:0] select_ln51_7_fu_493_p3;
reg   [7:0] select_ln51_7_reg_773;
wire   [7:0] select_ln51_8_fu_517_p3;
reg   [7:0] select_ln51_8_reg_778;
wire   [7:0] select_ln51_9_fu_541_p3;
reg   [7:0] select_ln51_9_reg_783;
wire   [7:0] select_ln51_10_fu_565_p3;
reg   [7:0] select_ln51_10_reg_788;
wire   [7:0] select_ln51_11_fu_589_p3;
reg   [7:0] select_ln51_11_reg_793;
wire   [7:0] select_ln51_12_fu_613_p3;
reg   [7:0] select_ln51_12_reg_798;
wire   [7:0] select_ln51_13_fu_637_p3;
reg   [7:0] select_ln51_13_reg_803;
wire   [7:0] select_ln51_14_fu_661_p3;
reg   [7:0] select_ln51_14_reg_808;
wire   [7:0] select_ln51_15_fu_685_p3;
reg   [7:0] select_ln51_15_reg_813;
reg    ap_block_pp0_stage0_11001;
reg   [6:0] i_fu_136;
wire   [6:0] i_5_fu_693_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_4;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [8:0] trunc_ln44_fu_161_p1;
wire   [0:0] icmp_ln51_fu_315_p2;
wire   [7:0] trunc_ln52_fu_321_p1;
wire   [8:0] trunc_ln44_s_fu_165_p4;
wire   [0:0] icmp_ln51_1_fu_333_p2;
wire   [7:0] trunc_ln52_1_fu_339_p4;
wire   [8:0] trunc_ln44_1_fu_175_p4;
wire   [0:0] icmp_ln51_2_fu_357_p2;
wire   [7:0] trunc_ln52_2_fu_363_p4;
wire   [8:0] trunc_ln44_2_fu_185_p4;
wire   [0:0] icmp_ln51_3_fu_381_p2;
wire   [7:0] trunc_ln52_3_fu_387_p4;
wire   [8:0] trunc_ln44_3_fu_195_p4;
wire   [0:0] icmp_ln51_4_fu_405_p2;
wire   [7:0] trunc_ln52_4_fu_411_p4;
wire   [8:0] trunc_ln44_4_fu_205_p4;
wire   [0:0] icmp_ln51_5_fu_429_p2;
wire   [7:0] trunc_ln52_5_fu_435_p4;
wire   [8:0] trunc_ln44_5_fu_215_p4;
wire   [0:0] icmp_ln51_6_fu_453_p2;
wire   [7:0] trunc_ln52_6_fu_459_p4;
wire   [8:0] trunc_ln44_6_fu_225_p4;
wire   [0:0] icmp_ln51_7_fu_477_p2;
wire   [7:0] trunc_ln52_7_fu_483_p4;
wire   [8:0] trunc_ln44_7_fu_235_p4;
wire   [0:0] icmp_ln51_8_fu_501_p2;
wire   [7:0] trunc_ln52_8_fu_507_p4;
wire   [8:0] trunc_ln44_8_fu_245_p4;
wire   [0:0] icmp_ln51_9_fu_525_p2;
wire   [7:0] trunc_ln52_9_fu_531_p4;
wire   [8:0] trunc_ln44_9_fu_255_p4;
wire   [0:0] icmp_ln51_10_fu_549_p2;
wire   [7:0] trunc_ln52_s_fu_555_p4;
wire   [8:0] trunc_ln44_10_fu_265_p4;
wire   [0:0] icmp_ln51_11_fu_573_p2;
wire   [7:0] trunc_ln52_10_fu_579_p4;
wire   [8:0] trunc_ln44_11_fu_275_p4;
wire   [0:0] icmp_ln51_12_fu_597_p2;
wire   [7:0] trunc_ln52_11_fu_603_p4;
wire   [8:0] trunc_ln44_12_fu_285_p4;
wire   [0:0] icmp_ln51_13_fu_621_p2;
wire   [7:0] trunc_ln52_12_fu_627_p4;
wire   [8:0] trunc_ln44_13_fu_295_p4;
wire   [0:0] icmp_ln51_14_fu_645_p2;
wire   [7:0] trunc_ln52_13_fu_651_p4;
wire   [8:0] trunc_ln44_14_fu_305_p4;
wire   [0:0] icmp_ln51_15_fu_669_p2;
wire   [7:0] trunc_ln52_14_fu_675_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_145;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_136 = 7'd0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_145)) begin
        i_fu_136 <= i_5_fu_693_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln51_10_reg_788 <= select_ln51_10_fu_565_p3;
        select_ln51_11_reg_793 <= select_ln51_11_fu_589_p3;
        select_ln51_12_reg_798 <= select_ln51_12_fu_613_p3;
        select_ln51_13_reg_803 <= select_ln51_13_fu_637_p3;
        select_ln51_14_reg_808 <= select_ln51_14_fu_661_p3;
        select_ln51_15_reg_813 <= select_ln51_15_fu_685_p3;
        select_ln51_1_reg_743 <= select_ln51_1_fu_349_p3;
        select_ln51_2_reg_748 <= select_ln51_2_fu_373_p3;
        select_ln51_3_reg_753 <= select_ln51_3_fu_397_p3;
        select_ln51_4_reg_758 <= select_ln51_4_fu_421_p3;
        select_ln51_5_reg_763 <= select_ln51_5_fu_445_p3;
        select_ln51_6_reg_768 <= select_ln51_6_fu_469_p3;
        select_ln51_7_reg_773 <= select_ln51_7_fu_493_p3;
        select_ln51_8_reg_778 <= select_ln51_8_fu_517_p3;
        select_ln51_9_reg_783 <= select_ln51_9_fu_541_p3;
        select_ln51_reg_738 <= select_ln51_fu_325_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_699_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_4 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_blk_n = layer7_out_empty_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_read = 1'b1;
    end else begin
        layer7_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_write = 1'b1;
    end else begin
        layer8_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (layer7_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_145 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_5_fu_693_p2 = (ap_sig_allocacmp_i_4 + 7'd1);

assign icmp_ln41_fu_699_p2 = ((ap_sig_allocacmp_i_4 == 7'd120) ? 1'b1 : 1'b0);

assign icmp_ln51_10_fu_549_p2 = (($signed(trunc_ln44_9_fu_255_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_573_p2 = (($signed(trunc_ln44_10_fu_265_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_597_p2 = (($signed(trunc_ln44_11_fu_275_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_621_p2 = (($signed(trunc_ln44_12_fu_285_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_645_p2 = (($signed(trunc_ln44_13_fu_295_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_669_p2 = (($signed(trunc_ln44_14_fu_305_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_333_p2 = (($signed(trunc_ln44_s_fu_165_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_357_p2 = (($signed(trunc_ln44_1_fu_175_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_381_p2 = (($signed(trunc_ln44_2_fu_185_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_405_p2 = (($signed(trunc_ln44_3_fu_195_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_429_p2 = (($signed(trunc_ln44_4_fu_205_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_453_p2 = (($signed(trunc_ln44_5_fu_215_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_477_p2 = (($signed(trunc_ln44_6_fu_225_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_501_p2 = (($signed(trunc_ln44_7_fu_235_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_525_p2 = (($signed(trunc_ln44_8_fu_245_p4) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_315_p2 = (($signed(trunc_ln44_fu_161_p1) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign layer8_out_din = {{{{{{{{{{{{{{{{select_ln51_15_reg_813}, {select_ln51_14_reg_808}}, {select_ln51_13_reg_803}}, {select_ln51_12_reg_798}}, {select_ln51_11_reg_793}}, {select_ln51_10_reg_788}}, {select_ln51_9_reg_783}}, {select_ln51_8_reg_778}}, {select_ln51_7_reg_773}}, {select_ln51_6_reg_768}}, {select_ln51_5_reg_763}}, {select_ln51_4_reg_758}}, {select_ln51_3_reg_753}}, {select_ln51_2_reg_748}}, {select_ln51_1_reg_743}}, {select_ln51_reg_738}};

assign select_ln51_10_fu_565_p3 = ((icmp_ln51_10_fu_549_p2[0:0] == 1'b1) ? trunc_ln52_s_fu_555_p4 : 8'd0);

assign select_ln51_11_fu_589_p3 = ((icmp_ln51_11_fu_573_p2[0:0] == 1'b1) ? trunc_ln52_10_fu_579_p4 : 8'd0);

assign select_ln51_12_fu_613_p3 = ((icmp_ln51_12_fu_597_p2[0:0] == 1'b1) ? trunc_ln52_11_fu_603_p4 : 8'd0);

assign select_ln51_13_fu_637_p3 = ((icmp_ln51_13_fu_621_p2[0:0] == 1'b1) ? trunc_ln52_12_fu_627_p4 : 8'd0);

assign select_ln51_14_fu_661_p3 = ((icmp_ln51_14_fu_645_p2[0:0] == 1'b1) ? trunc_ln52_13_fu_651_p4 : 8'd0);

assign select_ln51_15_fu_685_p3 = ((icmp_ln51_15_fu_669_p2[0:0] == 1'b1) ? trunc_ln52_14_fu_675_p4 : 8'd0);

assign select_ln51_1_fu_349_p3 = ((icmp_ln51_1_fu_333_p2[0:0] == 1'b1) ? trunc_ln52_1_fu_339_p4 : 8'd0);

assign select_ln51_2_fu_373_p3 = ((icmp_ln51_2_fu_357_p2[0:0] == 1'b1) ? trunc_ln52_2_fu_363_p4 : 8'd0);

assign select_ln51_3_fu_397_p3 = ((icmp_ln51_3_fu_381_p2[0:0] == 1'b1) ? trunc_ln52_3_fu_387_p4 : 8'd0);

assign select_ln51_4_fu_421_p3 = ((icmp_ln51_4_fu_405_p2[0:0] == 1'b1) ? trunc_ln52_4_fu_411_p4 : 8'd0);

assign select_ln51_5_fu_445_p3 = ((icmp_ln51_5_fu_429_p2[0:0] == 1'b1) ? trunc_ln52_5_fu_435_p4 : 8'd0);

assign select_ln51_6_fu_469_p3 = ((icmp_ln51_6_fu_453_p2[0:0] == 1'b1) ? trunc_ln52_6_fu_459_p4 : 8'd0);

assign select_ln51_7_fu_493_p3 = ((icmp_ln51_7_fu_477_p2[0:0] == 1'b1) ? trunc_ln52_7_fu_483_p4 : 8'd0);

assign select_ln51_8_fu_517_p3 = ((icmp_ln51_8_fu_501_p2[0:0] == 1'b1) ? trunc_ln52_8_fu_507_p4 : 8'd0);

assign select_ln51_9_fu_541_p3 = ((icmp_ln51_9_fu_525_p2[0:0] == 1'b1) ? trunc_ln52_9_fu_531_p4 : 8'd0);

assign select_ln51_fu_325_p3 = ((icmp_ln51_fu_315_p2[0:0] == 1'b1) ? trunc_ln52_fu_321_p1 : 8'd0);

assign start_out = real_start;

assign trunc_ln44_10_fu_265_p4 = {{layer7_out_dout[107:99]}};

assign trunc_ln44_11_fu_275_p4 = {{layer7_out_dout[116:108]}};

assign trunc_ln44_12_fu_285_p4 = {{layer7_out_dout[125:117]}};

assign trunc_ln44_13_fu_295_p4 = {{layer7_out_dout[134:126]}};

assign trunc_ln44_14_fu_305_p4 = {{layer7_out_dout[143:135]}};

assign trunc_ln44_1_fu_175_p4 = {{layer7_out_dout[26:18]}};

assign trunc_ln44_2_fu_185_p4 = {{layer7_out_dout[35:27]}};

assign trunc_ln44_3_fu_195_p4 = {{layer7_out_dout[44:36]}};

assign trunc_ln44_4_fu_205_p4 = {{layer7_out_dout[53:45]}};

assign trunc_ln44_5_fu_215_p4 = {{layer7_out_dout[62:54]}};

assign trunc_ln44_6_fu_225_p4 = {{layer7_out_dout[71:63]}};

assign trunc_ln44_7_fu_235_p4 = {{layer7_out_dout[80:72]}};

assign trunc_ln44_8_fu_245_p4 = {{layer7_out_dout[89:81]}};

assign trunc_ln44_9_fu_255_p4 = {{layer7_out_dout[98:90]}};

assign trunc_ln44_fu_161_p1 = layer7_out_dout[8:0];

assign trunc_ln44_s_fu_165_p4 = {{layer7_out_dout[17:9]}};

assign trunc_ln52_10_fu_579_p4 = {{layer7_out_dout[106:99]}};

assign trunc_ln52_11_fu_603_p4 = {{layer7_out_dout[115:108]}};

assign trunc_ln52_12_fu_627_p4 = {{layer7_out_dout[124:117]}};

assign trunc_ln52_13_fu_651_p4 = {{layer7_out_dout[133:126]}};

assign trunc_ln52_14_fu_675_p4 = {{layer7_out_dout[142:135]}};

assign trunc_ln52_1_fu_339_p4 = {{layer7_out_dout[16:9]}};

assign trunc_ln52_2_fu_363_p4 = {{layer7_out_dout[25:18]}};

assign trunc_ln52_3_fu_387_p4 = {{layer7_out_dout[34:27]}};

assign trunc_ln52_4_fu_411_p4 = {{layer7_out_dout[43:36]}};

assign trunc_ln52_5_fu_435_p4 = {{layer7_out_dout[52:45]}};

assign trunc_ln52_6_fu_459_p4 = {{layer7_out_dout[61:54]}};

assign trunc_ln52_7_fu_483_p4 = {{layer7_out_dout[70:63]}};

assign trunc_ln52_8_fu_507_p4 = {{layer7_out_dout[79:72]}};

assign trunc_ln52_9_fu_531_p4 = {{layer7_out_dout[88:81]}};

assign trunc_ln52_fu_321_p1 = layer7_out_dout[7:0];

assign trunc_ln52_s_fu_555_p4 = {{layer7_out_dout[97:90]}};

endmodule //myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_s
