// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=2362,HLS_SYN_TPT=2352,HLS_SYN_MEM=27,HLS_SYN_DSP=0,HLS_SYN_FF=10846,HLS_SYN_LUT=64523,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject (
        input_layer_1_TDATA,
        layer13_out_TDATA,
        ap_clk,
        ap_rst_n,
        input_layer_1_TVALID,
        input_layer_1_TREADY,
        ap_start,
        layer13_out_TVALID,
        layer13_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] input_layer_1_TDATA;
output  [159:0] layer13_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   input_layer_1_TVALID;
output   input_layer_1_TREADY;
input   ap_start;
output   layer13_out_TVALID;
input   layer13_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_start;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_done;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_continue;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_idle;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_ready;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_out;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_write;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_input_layer_1_TREADY;
wire   [79:0] conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_din;
wire    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_write;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_start;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_done;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_continue;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_idle;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_ready;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer3_out_read;
wire   [79:0] relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_din;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_write;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_out;
wire    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_write;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_start;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_done;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_continue;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_idle;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_ready;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_out;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_write;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer4_out_read;
wire   [15:0] pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_din;
wire    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_write;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_start;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_done;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_continue;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_idle;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_ready;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_out;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_write;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer5_out_read;
wire   [143:0] conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_din;
wire    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_write;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_start;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_done;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_continue;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_idle;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_ready;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer7_out_read;
wire   [127:0] relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_din;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_write;
wire   [31:0] relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid;
wire   [31:0] relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_out;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_write;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_start;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_done;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_continue;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_idle;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_ready;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_out;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_write;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer8_out_read;
wire   [31:0] pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_din;
wire    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_write;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_start;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_done;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_continue;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_idle;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_ready;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer9_out_read;
wire   [159:0] dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TDATA;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TVALID;
wire    layer3_out_full_n;
wire   [79:0] layer3_out_dout;
wire    layer3_out_empty_n;
wire   [10:0] layer3_out_num_data_valid;
wire   [10:0] layer3_out_fifo_cap;
wire    layer4_out_full_n;
wire   [79:0] layer4_out_dout;
wire    layer4_out_empty_n;
wire   [10:0] layer4_out_num_data_valid;
wire   [10:0] layer4_out_fifo_cap;
wire    layer5_out_full_n;
wire   [15:0] layer5_out_dout;
wire    layer5_out_empty_n;
wire   [8:0] layer5_out_num_data_valid;
wire   [8:0] layer5_out_fifo_cap;
wire    layer7_out_full_n;
wire   [143:0] layer7_out_dout;
wire    layer7_out_empty_n;
wire   [7:0] layer7_out_num_data_valid;
wire   [7:0] layer7_out_fifo_cap;
wire    layer8_out_full_n;
wire   [127:0] layer8_out_dout;
wire    layer8_out_empty_n;
wire   [7:0] layer8_out_num_data_valid;
wire   [7:0] layer8_out_fifo_cap;
wire    layer9_out_full_n;
wire   [31:0] layer9_out_dout;
wire    layer9_out_empty_n;
wire   [5:0] layer9_out_num_data_valid;
wire   [5:0] layer9_out_fifo_cap;
wire   [0:0] start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_din;
wire    start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_full_n;
wire   [0:0] start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_dout;
wire    start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_din;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_dout;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_din;
wire    start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_dout;
wire    start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_din;
wire    start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_dout;
wire    start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_din;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_dout;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_din;
wire    start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_full_n;
wire   [0:0] start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_dout;
wire    start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_empty_n;

myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_out),
    .start_write(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_write),
    .input_layer_1_TDATA(input_layer_1_TDATA),
    .input_layer_1_TVALID(input_layer_1_TVALID),
    .input_layer_1_TREADY(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_input_layer_1_TREADY),
    .layer3_out_din(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_din),
    .layer3_out_full_n(layer3_out_full_n),
    .layer3_out_write(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_write),
    .layer3_out_num_data_valid(layer3_out_num_data_valid),
    .layer3_out_fifo_cap(layer3_out_fifo_cap)
);

myproject_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_s relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_full_n),
    .ap_done(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_done),
    .ap_continue(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_continue),
    .ap_idle(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_idle),
    .ap_ready(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_ready),
    .layer3_out_dout(layer3_out_dout),
    .layer3_out_empty_n(layer3_out_empty_n),
    .layer3_out_read(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer3_out_read),
    .layer3_out_num_data_valid(layer3_out_num_data_valid),
    .layer3_out_fifo_cap(layer3_out_fifo_cap),
    .layer4_out_din(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_din),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_write),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .start_out(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_out),
    .start_write(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_write)
);

myproject_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_s pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_full_n),
    .ap_done(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_done),
    .ap_continue(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_ready),
    .start_out(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_out),
    .start_write(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_write),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer4_out_read),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer5_out_din(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_din),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_write),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap)
);

myproject_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_s conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_out),
    .start_write(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer5_out_read),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer7_out_din(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_din),
    .layer7_out_full_n(layer7_out_full_n),
    .layer7_out_write(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_write),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap)
);

myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_s relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_full_n),
    .ap_done(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_ready),
    .layer7_out_dout(layer7_out_dout),
    .layer7_out_empty_n(layer7_out_empty_n),
    .layer7_out_read(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer7_out_read),
    .layer7_out_num_data_valid(layer7_out_num_data_valid),
    .layer7_out_fifo_cap(layer7_out_fifo_cap),
    .layer8_out_din(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_din),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_write),
    .layer8_out_num_data_valid(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid),
    .layer8_out_fifo_cap(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap),
    .start_out(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_out),
    .start_write(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_write)
);

myproject_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_s pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_full_n),
    .ap_done(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_done),
    .ap_continue(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_ready),
    .start_out(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_out),
    .start_write(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_write),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer8_out_read),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer9_out_din(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_din),
    .layer9_out_full_n(layer9_out_full_n),
    .layer9_out_write(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_write),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap)
);

myproject_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_s dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_start),
    .ap_done(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_done),
    .ap_continue(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_continue),
    .ap_idle(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_idle),
    .ap_ready(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_ready),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer9_out_read),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer13_out_TDATA(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TDATA),
    .layer13_out_TVALID(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TVALID),
    .layer13_out_TREADY(layer13_out_TREADY)
);

myproject_fifo_w80_d676_A layer3_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_din),
    .if_full_n(layer3_out_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_write),
    .if_dout(layer3_out_dout),
    .if_empty_n(layer3_out_empty_n),
    .if_read(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer3_out_read),
    .if_num_data_valid(layer3_out_num_data_valid),
    .if_fifo_cap(layer3_out_fifo_cap)
);

myproject_fifo_w80_d676_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_empty_n(layer4_out_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer4_out_read),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap)
);

myproject_fifo_w16_d169_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_empty_n(layer5_out_empty_n),
    .if_read(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer5_out_read),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap)
);

myproject_fifo_w144_d121_A layer7_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_din),
    .if_full_n(layer7_out_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_write),
    .if_dout(layer7_out_dout),
    .if_empty_n(layer7_out_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer7_out_read),
    .if_num_data_valid(layer7_out_num_data_valid),
    .if_fifo_cap(layer7_out_fifo_cap)
);

myproject_fifo_w128_d121_A layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_empty_n(layer8_out_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer8_out_read),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap)
);

myproject_fifo_w32_d25_S layer9_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_din),
    .if_full_n(layer9_out_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_write),
    .if_dout(layer9_out_dout),
    .if_empty_n(layer9_out_empty_n),
    .if_read(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer9_out_read),
    .if_num_data_valid(layer9_out_num_data_valid),
    .if_fifo_cap(layer9_out_fifo_cap)
);

myproject_start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4JfO start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4JfO_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_din),
    .if_full_n(start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_write),
    .if_dout(start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_dout),
    .if_empty_n(start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_empty_n),
    .if_read(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0 start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_full_n),
    .if_write(relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_ready)
);

myproject_start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7KfY start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7KfY_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0 start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0 start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_ready)
);

myproject_start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0 start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_din),
    .if_full_n(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_write),
    .if_dout(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_dout),
    .if_empty_n(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_empty_n),
    .if_read(dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_ready)
);

assign ap_done = dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_done;

assign ap_idle = (relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_idle & relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_idle & pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_idle & pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_idle & dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_idle & conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_idle & conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_idle);

assign ap_ready = conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_start = start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_empty_n;

assign conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_start = ap_start;

assign dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_continue = 1'b1;

assign dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_start = start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_empty_n;

assign input_layer_1_TREADY = conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_input_layer_1_TREADY;

assign layer13_out_TDATA = dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TDATA;

assign layer13_out_TVALID = dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TVALID;

assign pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_start = start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_empty_n;

assign pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_start = start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_empty_n;

assign relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_start = start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_empty_n;

assign relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap = layer8_out_fifo_cap;

assign relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid = layer8_out_num_data_valid;

assign relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_continue = 1'b1;

assign relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_start = start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_empty_n;

assign start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_din = 1'b1;

assign start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_din = 1'b1;

assign start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_din = 1'b1;

endmodule //myproject
