// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer8_out_dout,
        layer8_out_empty_n,
        layer8_out_read,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer9_out_din,
        layer9_out_full_n,
        layer9_out_write,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] layer8_out_dout;
input   layer8_out_empty_n;
output   layer8_out_read;
input  [7:0] layer8_out_num_data_valid;
input  [7:0] layer8_out_fifo_cap;
output  [31:0] layer9_out_din;
input   layer9_out_full_n;
output   layer9_out_write;
input  [5:0] layer9_out_num_data_valid;
input  [5:0] layer9_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer8_out_read;
reg layer9_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_14;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_7;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_6;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_5;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_4;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_3;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_2;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_1;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_13;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_12;
reg   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_16u_0_line_buffer;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_11;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_10;
reg   [7:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_31;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_30;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_29;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_28;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_27;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_26;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_25;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_24;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_23;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_22;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_21;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_20;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_19;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_18;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_17;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_16;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_15;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_14;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_13;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_12;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_11;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_10;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_9;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_8;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_7;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_6;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_5;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_4;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_3;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_2;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_1;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap;
reg   [31:0] sY;
reg   [31:0] pY;
reg   [31:0] pX;
reg   [31:0] sX;
reg    layer8_out_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    layer9_out_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln55_reg_4040;
reg   [0:0] and_ln55_1_reg_4044;
reg   [0:0] icmp_ln11195_reg_435;
reg   [7:0] p_0_0_0_0_010893_reg_446;
reg    ap_block_state1;
wire   [7:0] select_ln109_fu_996_p3;
reg   [7:0] select_ln109_reg_3868;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op574_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln109_1_fu_1004_p3;
reg   [7:0] select_ln109_1_reg_3873;
wire   [7:0] select_ln109_2_fu_1012_p3;
reg   [7:0] select_ln109_2_reg_3878;
wire   [7:0] select_ln109_3_fu_1020_p3;
reg   [7:0] select_ln109_3_reg_3883;
wire   [7:0] select_ln109_4_fu_1028_p3;
reg   [7:0] select_ln109_4_reg_3888;
wire   [7:0] select_ln109_5_fu_1036_p3;
reg   [7:0] select_ln109_5_reg_3893;
wire   [7:0] select_ln109_6_fu_1044_p3;
reg   [7:0] select_ln109_6_reg_3898;
wire   [7:0] select_ln109_7_fu_1052_p3;
reg   [7:0] select_ln109_7_reg_3903;
wire   [7:0] select_ln109_8_fu_1060_p3;
reg   [7:0] select_ln109_8_reg_3908;
wire   [7:0] select_ln109_9_fu_1068_p3;
reg   [7:0] select_ln109_9_reg_3913;
wire   [7:0] select_ln109_10_fu_1076_p3;
reg   [7:0] select_ln109_10_reg_3918;
wire   [7:0] select_ln109_11_fu_1084_p3;
reg   [7:0] select_ln109_11_reg_3923;
wire   [7:0] select_ln109_12_fu_1092_p3;
reg   [7:0] select_ln109_12_reg_3928;
wire   [7:0] select_ln109_13_fu_1100_p3;
reg   [7:0] select_ln109_13_reg_3933;
wire   [7:0] select_ln109_14_fu_1108_p3;
reg   [7:0] select_ln109_14_reg_3938;
wire   [7:0] trunc_ln115_fu_1116_p1;
reg   [7:0] trunc_ln115_reg_3943;
wire   [7:0] trunc_ln115_3_fu_1120_p4;
reg   [7:0] trunc_ln115_3_reg_3950;
wire   [7:0] trunc_ln115_4_fu_1130_p4;
reg   [7:0] trunc_ln115_4_reg_3956;
wire   [7:0] trunc_ln115_5_fu_1140_p4;
reg   [7:0] trunc_ln115_5_reg_3962;
wire   [7:0] trunc_ln115_6_fu_1150_p4;
reg   [7:0] trunc_ln115_6_reg_3968;
wire   [7:0] trunc_ln115_7_fu_1160_p4;
reg   [7:0] trunc_ln115_7_reg_3974;
wire   [7:0] trunc_ln115_8_fu_1170_p4;
reg   [7:0] trunc_ln115_8_reg_3980;
wire   [7:0] trunc_ln115_9_fu_1180_p4;
reg   [7:0] trunc_ln115_9_reg_3986;
wire   [7:0] trunc_ln115_s_fu_1190_p4;
reg   [7:0] trunc_ln115_s_reg_3992;
wire   [7:0] trunc_ln115_1_fu_1200_p4;
reg   [7:0] trunc_ln115_1_reg_3998;
wire   [7:0] trunc_ln115_2_fu_1210_p4;
reg   [7:0] trunc_ln115_2_reg_4004;
wire   [7:0] trunc_ln115_10_fu_1220_p4;
reg   [7:0] trunc_ln115_10_reg_4010;
wire   [7:0] trunc_ln115_11_fu_1230_p4;
reg   [7:0] trunc_ln115_11_reg_4016;
wire   [7:0] trunc_ln115_12_fu_1240_p4;
reg   [7:0] trunc_ln115_12_reg_4022;
wire   [7:0] trunc_ln115_13_fu_1250_p4;
reg   [7:0] trunc_ln115_13_reg_4028;
wire   [7:0] trunc_ln115_14_fu_1260_p4;
reg   [7:0] trunc_ln115_14_reg_4034;
wire   [0:0] icmp_ln55_fu_1274_p2;
wire   [0:0] and_ln55_1_fu_1322_p2;
wire   [7:0] select_ln0_fu_1391_p3;
reg   [7:0] select_ln0_reg_4048;
wire   [7:0] select_ln0_1_fu_1419_p3;
reg   [7:0] select_ln0_1_reg_4054;
wire   [7:0] select_ln0_2_fu_1439_p3;
reg   [7:0] select_ln0_2_reg_4060;
wire   [7:0] select_ln0_3_fu_1459_p3;
reg   [7:0] select_ln0_3_reg_4066;
wire   [7:0] select_ln0_4_fu_1479_p3;
reg   [7:0] select_ln0_4_reg_4072;
wire   [7:0] select_ln0_5_fu_1499_p3;
reg   [7:0] select_ln0_5_reg_4078;
wire   [7:0] select_ln0_6_fu_1519_p3;
reg   [7:0] select_ln0_6_reg_4084;
wire   [7:0] select_ln0_7_fu_1539_p3;
reg   [7:0] select_ln0_7_reg_4090;
wire   [7:0] select_ln0_8_fu_1559_p3;
reg   [7:0] select_ln0_8_reg_4096;
wire   [7:0] select_ln0_9_fu_1579_p3;
reg   [7:0] select_ln0_9_reg_4102;
wire   [7:0] select_ln0_10_fu_1599_p3;
reg   [7:0] select_ln0_10_reg_4108;
wire   [7:0] select_ln0_11_fu_1619_p3;
reg   [7:0] select_ln0_11_reg_4114;
wire   [7:0] select_ln0_12_fu_1639_p3;
reg   [7:0] select_ln0_12_reg_4120;
wire   [7:0] select_ln0_13_fu_1659_p3;
reg   [7:0] select_ln0_13_reg_4126;
wire   [7:0] select_ln0_14_fu_1679_p3;
reg   [7:0] select_ln0_14_reg_4132;
wire   [7:0] select_ln0_15_fu_1699_p3;
reg   [7:0] select_ln0_15_reg_4138;
wire   [7:0] select_ln0_16_fu_1719_p3;
reg   [7:0] select_ln0_16_reg_4144;
wire   [7:0] select_ln0_17_fu_1739_p3;
reg   [7:0] select_ln0_17_reg_4150;
wire   [7:0] select_ln0_18_fu_1759_p3;
reg   [7:0] select_ln0_18_reg_4156;
wire   [7:0] select_ln0_19_fu_1779_p3;
reg   [7:0] select_ln0_19_reg_4162;
wire   [7:0] select_ln0_20_fu_1799_p3;
reg   [7:0] select_ln0_20_reg_4168;
wire   [7:0] select_ln0_21_fu_1819_p3;
reg   [7:0] select_ln0_21_reg_4174;
wire   [7:0] select_ln0_22_fu_1839_p3;
reg   [7:0] select_ln0_22_reg_4180;
wire   [7:0] select_ln0_23_fu_1859_p3;
reg   [7:0] select_ln0_23_reg_4186;
wire   [7:0] select_ln0_24_fu_1879_p3;
reg   [7:0] select_ln0_24_reg_4192;
wire   [7:0] select_ln0_25_fu_1899_p3;
reg   [7:0] select_ln0_25_reg_4198;
wire   [7:0] select_ln0_26_fu_1919_p3;
reg   [7:0] select_ln0_26_reg_4204;
wire   [7:0] select_ln0_27_fu_1939_p3;
reg   [7:0] select_ln0_27_reg_4210;
wire   [7:0] select_ln0_28_fu_1959_p3;
reg   [7:0] select_ln0_28_reg_4216;
wire   [7:0] select_ln0_29_fu_1979_p3;
reg   [7:0] select_ln0_29_reg_4222;
wire   [7:0] select_ln0_30_fu_1999_p3;
reg   [7:0] select_ln0_30_reg_4228;
wire   [7:0] select_ln0_31_fu_2019_p3;
reg   [7:0] select_ln0_31_reg_4234;
wire   [0:0] icmp_ln76_fu_2033_p2;
wire   [0:0] icmp_ln80_fu_2087_p2;
wire   [0:0] icmp_ln111_fu_2153_p2;
reg   [0:0] icmp_ln111_reg_4248;
wire   [0:0] icmp_ln109_fu_2159_p2;
reg   [0:0] icmp_ln109_reg_4253;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg   [0:0] ap_phi_mux_icmp_ln11195_phi_fu_439_p4;
reg   [7:0] ap_phi_mux_p_0_0_0_0_010893_phi_fu_449_p4;
reg   [31:0] ap_phi_mux_storemerge_i_phi_fu_459_p4;
wire   [31:0] select_ln86_fu_2115_p3;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_reg_456;
wire    ap_CS_fsm_state4;
wire   [31:0] add_ln80_fu_2081_p2;
wire   [31:0] add_ln76_fu_2027_p2;
wire   [31:0] select_ln91_fu_2051_p3;
reg   [6:0] indvar_flatten12_fu_226;
wire   [6:0] add_ln109_fu_1284_p2;
reg   [7:0] p_0_15_0_0_024815_fu_230;
reg   [7:0] p_0_14_0_0_024417_fu_234;
reg   [7:0] p_0_13_0_0_024019_fu_238;
reg   [7:0] p_0_12_0_0_023621_fu_242;
reg   [7:0] p_0_11_0_0_023223_fu_246;
reg   [7:0] p_0_10_0_0_022825_fu_250;
reg   [7:0] p_0_9_0_0_022427_fu_254;
reg   [7:0] p_0_8_0_0_022029_fu_258;
reg   [7:0] p_0_7_0_0_021631_fu_262;
reg   [7:0] p_0_6_0_0_021233_fu_266;
reg   [7:0] p_0_5_0_0_020835_fu_270;
reg   [7:0] p_0_4_0_0_020437_fu_274;
reg   [7:0] p_0_3_0_0_020039_fu_278;
reg   [7:0] p_0_2_0_0_019641_fu_282;
reg   [7:0] p_0_1_0_0_019243_fu_286;
reg   [7:0] p_0_0_0_0_018845_fu_290;
reg   [7:0] p_0_15_0_0_013818546_fu_294;
reg   [7:0] p_0_14_0_0_013618248_fu_298;
reg   [7:0] p_0_13_0_0_013417950_fu_302;
reg   [7:0] p_0_12_0_0_013217652_fu_306;
reg   [7:0] p_0_11_0_0_013017354_fu_310;
reg   [7:0] p_0_10_0_0_012817056_fu_314;
reg   [7:0] p_0_9_0_0_012616758_fu_318;
reg   [7:0] p_0_8_0_0_012416460_fu_322;
reg   [7:0] p_0_7_0_0_012216162_fu_326;
reg   [7:0] p_0_6_0_0_012015864_fu_330;
reg   [7:0] p_0_5_0_0_011815566_fu_334;
reg   [7:0] p_0_4_0_0_011615268_fu_338;
reg   [7:0] p_0_3_0_0_011414970_fu_342;
reg   [7:0] p_0_2_0_0_011214672_fu_346;
reg   [7:0] p_0_1_0_0_011014374_fu_350;
reg   [7:0] p_0_0_0_0_010814076_fu_354;
reg   [7:0] p_0_15_0_0_013878_fu_358;
reg   [7:0] p_0_14_0_0_013679_fu_362;
reg   [7:0] p_0_13_0_0_013480_fu_366;
reg   [7:0] p_0_12_0_0_013281_fu_370;
reg   [7:0] p_0_11_0_0_013082_fu_374;
reg   [7:0] p_0_10_0_0_012883_fu_378;
reg   [7:0] p_0_9_0_0_012684_fu_382;
reg   [7:0] p_0_8_0_0_012485_fu_386;
reg   [7:0] p_0_7_0_0_012286_fu_390;
reg   [7:0] p_0_6_0_0_012087_fu_394;
reg   [7:0] p_0_5_0_0_011888_fu_398;
reg   [7:0] p_0_4_0_0_011689_fu_402;
reg   [7:0] p_0_3_0_0_011490_fu_406;
reg   [7:0] p_0_2_0_0_011291_fu_410;
reg   [7:0] p_0_1_0_0_011092_fu_414;
reg   [3:0] i_iw_fu_418;
wire   [3:0] i_iw_2_fu_2145_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln55_2_fu_1304_p2;
wire   [0:0] icmp_ln55_3_fu_1310_p2;
wire   [0:0] and_ln55_fu_1316_p2;
wire   [0:0] icmp_ln55_1_fu_1294_p2;
wire   [0:0] icmp_ln66_fu_1379_p2;
wire   [0:0] xor_ln66_fu_1385_p2;
wire   [7:0] select_ln10996_fu_1399_p3;
wire   [0:0] icmp_ln66_1_fu_1407_p2;
wire   [0:0] xor_ln66_1_fu_1413_p2;
wire   [0:0] icmp_ln66_3_fu_1427_p2;
wire   [0:0] xor_ln66_3_fu_1433_p2;
wire   [0:0] icmp_ln66_4_fu_1447_p2;
wire   [0:0] xor_ln66_4_fu_1453_p2;
wire   [0:0] icmp_ln66_6_fu_1467_p2;
wire   [0:0] xor_ln66_6_fu_1473_p2;
wire   [0:0] icmp_ln66_7_fu_1487_p2;
wire   [0:0] xor_ln66_7_fu_1493_p2;
wire   [0:0] icmp_ln66_9_fu_1507_p2;
wire   [0:0] xor_ln66_9_fu_1513_p2;
wire   [0:0] icmp_ln66_10_fu_1527_p2;
wire   [0:0] xor_ln66_10_fu_1533_p2;
wire   [0:0] icmp_ln66_12_fu_1547_p2;
wire   [0:0] xor_ln66_12_fu_1553_p2;
wire   [0:0] icmp_ln66_13_fu_1567_p2;
wire   [0:0] xor_ln66_13_fu_1573_p2;
wire   [0:0] icmp_ln66_15_fu_1587_p2;
wire   [0:0] xor_ln66_15_fu_1593_p2;
wire   [0:0] icmp_ln66_16_fu_1607_p2;
wire   [0:0] xor_ln66_16_fu_1613_p2;
wire   [0:0] icmp_ln66_18_fu_1627_p2;
wire   [0:0] xor_ln66_18_fu_1633_p2;
wire   [0:0] icmp_ln66_19_fu_1647_p2;
wire   [0:0] xor_ln66_19_fu_1653_p2;
wire   [0:0] icmp_ln66_21_fu_1667_p2;
wire   [0:0] xor_ln66_21_fu_1673_p2;
wire   [0:0] icmp_ln66_22_fu_1687_p2;
wire   [0:0] xor_ln66_22_fu_1693_p2;
wire   [0:0] icmp_ln66_24_fu_1707_p2;
wire   [0:0] xor_ln66_24_fu_1713_p2;
wire   [0:0] icmp_ln66_25_fu_1727_p2;
wire   [0:0] xor_ln66_25_fu_1733_p2;
wire   [0:0] icmp_ln66_27_fu_1747_p2;
wire   [0:0] xor_ln66_27_fu_1753_p2;
wire   [0:0] icmp_ln66_28_fu_1767_p2;
wire   [0:0] xor_ln66_28_fu_1773_p2;
wire   [0:0] icmp_ln66_30_fu_1787_p2;
wire   [0:0] xor_ln66_30_fu_1793_p2;
wire   [0:0] icmp_ln66_31_fu_1807_p2;
wire   [0:0] xor_ln66_31_fu_1813_p2;
wire   [0:0] icmp_ln66_33_fu_1827_p2;
wire   [0:0] xor_ln66_33_fu_1833_p2;
wire   [0:0] icmp_ln66_34_fu_1847_p2;
wire   [0:0] xor_ln66_34_fu_1853_p2;
wire   [0:0] icmp_ln66_36_fu_1867_p2;
wire   [0:0] xor_ln66_36_fu_1873_p2;
wire   [0:0] icmp_ln66_37_fu_1887_p2;
wire   [0:0] xor_ln66_37_fu_1893_p2;
wire   [0:0] icmp_ln66_39_fu_1907_p2;
wire   [0:0] xor_ln66_39_fu_1913_p2;
wire   [0:0] icmp_ln66_40_fu_1927_p2;
wire   [0:0] xor_ln66_40_fu_1933_p2;
wire   [0:0] icmp_ln66_42_fu_1947_p2;
wire   [0:0] xor_ln66_42_fu_1953_p2;
wire   [0:0] icmp_ln66_43_fu_1967_p2;
wire   [0:0] xor_ln66_43_fu_1973_p2;
wire   [0:0] icmp_ln66_45_fu_1987_p2;
wire   [0:0] xor_ln66_45_fu_1993_p2;
wire   [0:0] icmp_ln66_46_fu_2007_p2;
wire   [0:0] xor_ln66_46_fu_2013_p2;
wire   [31:0] add_ln91_fu_2045_p2;
wire   [0:0] icmp_ln86_fu_2103_p2;
wire   [31:0] add_ln86_fu_2109_p2;
wire   [3:0] add_ln111_fu_2139_p2;
wire   [0:0] icmp_ln66_2_fu_2410_p2;
wire   [0:0] xor_ln66_2_fu_2414_p2;
wire   [7:0] select_ln66_fu_2420_p3;
wire   [5:0] trunc_ln66_fu_2426_p1;
wire   [7:0] zext_ln68_16_fu_2430_p1;
wire   [0:0] tmp_fu_2444_p3;
wire   [1:0] trunc_ln_fu_2434_p4;
wire   [1:0] zext_ln68_fu_2452_p1;
wire   [0:0] icmp_ln66_5_fu_2462_p2;
wire   [0:0] xor_ln66_5_fu_2466_p2;
wire   [7:0] select_ln66_1_fu_2472_p3;
wire   [5:0] trunc_ln66_1_fu_2478_p1;
wire   [7:0] zext_ln68_17_fu_2482_p1;
wire   [0:0] tmp_1_fu_2496_p3;
wire   [1:0] trunc_ln68_1_fu_2486_p4;
wire   [1:0] zext_ln68_1_fu_2504_p1;
wire   [0:0] icmp_ln66_8_fu_2514_p2;
wire   [0:0] xor_ln66_8_fu_2518_p2;
wire   [7:0] select_ln66_2_fu_2524_p3;
wire   [5:0] trunc_ln66_2_fu_2530_p1;
wire   [7:0] zext_ln68_18_fu_2534_p1;
wire   [0:0] tmp_2_fu_2548_p3;
wire   [1:0] trunc_ln68_2_fu_2538_p4;
wire   [1:0] zext_ln68_2_fu_2556_p1;
wire   [0:0] icmp_ln66_11_fu_2566_p2;
wire   [0:0] xor_ln66_11_fu_2570_p2;
wire   [7:0] select_ln66_3_fu_2576_p3;
wire   [5:0] trunc_ln66_3_fu_2582_p1;
wire   [7:0] zext_ln68_19_fu_2586_p1;
wire   [0:0] tmp_3_fu_2600_p3;
wire   [1:0] trunc_ln68_3_fu_2590_p4;
wire   [1:0] zext_ln68_3_fu_2608_p1;
wire   [0:0] icmp_ln66_14_fu_2618_p2;
wire   [0:0] xor_ln66_14_fu_2622_p2;
wire   [7:0] select_ln66_4_fu_2628_p3;
wire   [5:0] trunc_ln66_4_fu_2634_p1;
wire   [7:0] zext_ln68_20_fu_2638_p1;
wire   [0:0] tmp_4_fu_2652_p3;
wire   [1:0] trunc_ln68_4_fu_2642_p4;
wire   [1:0] zext_ln68_4_fu_2660_p1;
wire   [0:0] icmp_ln66_17_fu_2670_p2;
wire   [0:0] xor_ln66_17_fu_2674_p2;
wire   [7:0] select_ln66_5_fu_2680_p3;
wire   [5:0] trunc_ln66_5_fu_2686_p1;
wire   [7:0] zext_ln68_21_fu_2690_p1;
wire   [0:0] tmp_5_fu_2704_p3;
wire   [1:0] trunc_ln68_5_fu_2694_p4;
wire   [1:0] zext_ln68_5_fu_2712_p1;
wire   [0:0] icmp_ln66_20_fu_2722_p2;
wire   [0:0] xor_ln66_20_fu_2726_p2;
wire   [7:0] select_ln66_6_fu_2732_p3;
wire   [5:0] trunc_ln66_6_fu_2738_p1;
wire   [7:0] zext_ln68_22_fu_2742_p1;
wire   [0:0] tmp_6_fu_2756_p3;
wire   [1:0] trunc_ln68_6_fu_2746_p4;
wire   [1:0] zext_ln68_6_fu_2764_p1;
wire   [0:0] icmp_ln66_23_fu_2774_p2;
wire   [0:0] xor_ln66_23_fu_2778_p2;
wire   [7:0] select_ln66_7_fu_2784_p3;
wire   [5:0] trunc_ln66_7_fu_2790_p1;
wire   [7:0] zext_ln68_23_fu_2794_p1;
wire   [0:0] tmp_7_fu_2808_p3;
wire   [1:0] trunc_ln68_7_fu_2798_p4;
wire   [1:0] zext_ln68_7_fu_2816_p1;
wire   [0:0] icmp_ln66_26_fu_2826_p2;
wire   [0:0] xor_ln66_26_fu_2830_p2;
wire   [7:0] select_ln66_8_fu_2836_p3;
wire   [5:0] trunc_ln66_8_fu_2842_p1;
wire   [7:0] zext_ln68_24_fu_2846_p1;
wire   [0:0] tmp_8_fu_2860_p3;
wire   [1:0] trunc_ln68_8_fu_2850_p4;
wire   [1:0] zext_ln68_8_fu_2868_p1;
wire   [0:0] icmp_ln66_29_fu_2878_p2;
wire   [0:0] xor_ln66_29_fu_2882_p2;
wire   [7:0] select_ln66_9_fu_2888_p3;
wire   [5:0] trunc_ln66_9_fu_2894_p1;
wire   [7:0] zext_ln68_25_fu_2898_p1;
wire   [0:0] tmp_9_fu_2912_p3;
wire   [1:0] trunc_ln68_9_fu_2902_p4;
wire   [1:0] zext_ln68_9_fu_2920_p1;
wire   [0:0] icmp_ln66_32_fu_2930_p2;
wire   [0:0] xor_ln66_32_fu_2934_p2;
wire   [7:0] select_ln66_10_fu_2940_p3;
wire   [5:0] trunc_ln66_10_fu_2946_p1;
wire   [7:0] zext_ln68_26_fu_2950_p1;
wire   [0:0] tmp_10_fu_2964_p3;
wire   [1:0] trunc_ln68_s_fu_2954_p4;
wire   [1:0] zext_ln68_10_fu_2972_p1;
wire   [0:0] icmp_ln66_35_fu_2982_p2;
wire   [0:0] xor_ln66_35_fu_2986_p2;
wire   [7:0] select_ln66_11_fu_2992_p3;
wire   [5:0] trunc_ln66_11_fu_2998_p1;
wire   [7:0] zext_ln68_27_fu_3002_p1;
wire   [0:0] tmp_11_fu_3016_p3;
wire   [1:0] trunc_ln68_10_fu_3006_p4;
wire   [1:0] zext_ln68_11_fu_3024_p1;
wire   [0:0] icmp_ln66_38_fu_3034_p2;
wire   [0:0] xor_ln66_38_fu_3038_p2;
wire   [7:0] select_ln66_12_fu_3044_p3;
wire   [5:0] trunc_ln66_12_fu_3050_p1;
wire   [7:0] zext_ln68_28_fu_3054_p1;
wire   [0:0] tmp_12_fu_3068_p3;
wire   [1:0] trunc_ln68_11_fu_3058_p4;
wire   [1:0] zext_ln68_12_fu_3076_p1;
wire   [0:0] icmp_ln66_41_fu_3086_p2;
wire   [0:0] xor_ln66_41_fu_3090_p2;
wire   [7:0] select_ln66_13_fu_3096_p3;
wire   [5:0] trunc_ln66_13_fu_3102_p1;
wire   [7:0] zext_ln68_29_fu_3106_p1;
wire   [0:0] tmp_13_fu_3120_p3;
wire   [1:0] trunc_ln68_12_fu_3110_p4;
wire   [1:0] zext_ln68_13_fu_3128_p1;
wire   [0:0] icmp_ln66_44_fu_3138_p2;
wire   [0:0] xor_ln66_44_fu_3142_p2;
wire   [7:0] select_ln66_14_fu_3148_p3;
wire   [5:0] trunc_ln66_14_fu_3154_p1;
wire   [7:0] zext_ln68_30_fu_3158_p1;
wire   [0:0] tmp_14_fu_3172_p3;
wire   [1:0] trunc_ln68_13_fu_3162_p4;
wire   [1:0] zext_ln68_14_fu_3180_p1;
wire   [0:0] icmp_ln66_47_fu_3190_p2;
wire   [0:0] xor_ln66_47_fu_3194_p2;
wire   [7:0] select_ln66_15_fu_3200_p3;
wire   [5:0] trunc_ln66_15_fu_3206_p1;
wire   [7:0] zext_ln68_31_fu_3210_p1;
wire   [0:0] tmp_15_fu_3224_p3;
wire   [1:0] trunc_ln68_14_fu_3214_p4;
wire   [1:0] zext_ln68_15_fu_3232_p1;
wire   [1:0] res_pack_15_fu_3236_p2;
wire   [1:0] res_pack_14_fu_3184_p2;
wire   [1:0] res_pack_13_fu_3132_p2;
wire   [1:0] res_pack_12_fu_3080_p2;
wire   [1:0] res_pack_11_fu_3028_p2;
wire   [1:0] res_pack_10_fu_2976_p2;
wire   [1:0] res_pack_9_fu_2924_p2;
wire   [1:0] res_pack_8_fu_2872_p2;
wire   [1:0] res_pack_7_fu_2820_p2;
wire   [1:0] res_pack_6_fu_2768_p2;
wire   [1:0] res_pack_5_fu_2716_p2;
wire   [1:0] res_pack_4_fu_2664_p2;
wire   [1:0] res_pack_3_fu_2612_p2;
wire   [1:0] res_pack_2_fu_2560_p2;
wire   [1:0] res_pack_1_fu_2508_p2;
wire   [1:0] res_pack_fu_2456_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_163;
reg    ap_condition_426;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_14 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_7 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_6 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_5 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_4 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_3 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_2 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_1 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_13 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_12 = 8'd0;
#0 void_pooling2d_cl_stream_stream_array_ap_ufixed_16u_0_line_buffer = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_11 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_10 = 8'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_31 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_30 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_29 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_28 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_27 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_26 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_25 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_24 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_23 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_22 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_21 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_20 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_19 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_18 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_17 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_16 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_15 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_14 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_13 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_12 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_11 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_10 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_9 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_8 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_7 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_6 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_5 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_4 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_3 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_2 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_1 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap = 8'd0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 indvar_flatten12_fu_226 = 7'd0;
#0 p_0_15_0_0_024815_fu_230 = 8'd0;
#0 p_0_14_0_0_024417_fu_234 = 8'd0;
#0 p_0_13_0_0_024019_fu_238 = 8'd0;
#0 p_0_12_0_0_023621_fu_242 = 8'd0;
#0 p_0_11_0_0_023223_fu_246 = 8'd0;
#0 p_0_10_0_0_022825_fu_250 = 8'd0;
#0 p_0_9_0_0_022427_fu_254 = 8'd0;
#0 p_0_8_0_0_022029_fu_258 = 8'd0;
#0 p_0_7_0_0_021631_fu_262 = 8'd0;
#0 p_0_6_0_0_021233_fu_266 = 8'd0;
#0 p_0_5_0_0_020835_fu_270 = 8'd0;
#0 p_0_4_0_0_020437_fu_274 = 8'd0;
#0 p_0_3_0_0_020039_fu_278 = 8'd0;
#0 p_0_2_0_0_019641_fu_282 = 8'd0;
#0 p_0_1_0_0_019243_fu_286 = 8'd0;
#0 p_0_0_0_0_018845_fu_290 = 8'd0;
#0 p_0_15_0_0_013818546_fu_294 = 8'd0;
#0 p_0_14_0_0_013618248_fu_298 = 8'd0;
#0 p_0_13_0_0_013417950_fu_302 = 8'd0;
#0 p_0_12_0_0_013217652_fu_306 = 8'd0;
#0 p_0_11_0_0_013017354_fu_310 = 8'd0;
#0 p_0_10_0_0_012817056_fu_314 = 8'd0;
#0 p_0_9_0_0_012616758_fu_318 = 8'd0;
#0 p_0_8_0_0_012416460_fu_322 = 8'd0;
#0 p_0_7_0_0_012216162_fu_326 = 8'd0;
#0 p_0_6_0_0_012015864_fu_330 = 8'd0;
#0 p_0_5_0_0_011815566_fu_334 = 8'd0;
#0 p_0_4_0_0_011615268_fu_338 = 8'd0;
#0 p_0_3_0_0_011414970_fu_342 = 8'd0;
#0 p_0_2_0_0_011214672_fu_346 = 8'd0;
#0 p_0_1_0_0_011014374_fu_350 = 8'd0;
#0 p_0_0_0_0_010814076_fu_354 = 8'd0;
#0 p_0_15_0_0_013878_fu_358 = 8'd0;
#0 p_0_14_0_0_013679_fu_362 = 8'd0;
#0 p_0_13_0_0_013480_fu_366 = 8'd0;
#0 p_0_12_0_0_013281_fu_370 = 8'd0;
#0 p_0_11_0_0_013082_fu_374 = 8'd0;
#0 p_0_10_0_0_012883_fu_378 = 8'd0;
#0 p_0_9_0_0_012684_fu_382 = 8'd0;
#0 p_0_8_0_0_012485_fu_386 = 8'd0;
#0 p_0_7_0_0_012286_fu_390 = 8'd0;
#0 p_0_6_0_0_012087_fu_394 = 8'd0;
#0 p_0_5_0_0_011888_fu_398 = 8'd0;
#0 p_0_4_0_0_011689_fu_402 = 8'd0;
#0 p_0_3_0_0_011490_fu_406 = 8'd0;
#0 p_0_2_0_0_011291_fu_410 = 8'd0;
#0 p_0_1_0_0_011092_fu_414 = 8'd0;
#0 i_iw_fu_418 = 4'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        i_iw_fu_418 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_iw_fu_418 <= i_iw_2_fu_2145_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_4253 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln11195_reg_435 <= icmp_ln111_reg_4248;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        icmp_ln11195_reg_435 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        indvar_flatten12_fu_226 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten12_fu_226 <= add_ln109_fu_1284_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_163)) begin
        if ((icmp_ln76_fu_2033_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln76_fu_2033_p2 == 1'd0)) begin
            pX <= add_ln76_fu_2027_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_426)) begin
        if ((icmp_ln80_fu_2087_p2 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln80_fu_2087_p2 == 1'd0)) begin
            pY <= add_ln80_fu_2081_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_010814076_fu_354 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_31;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_0_0_0_010814076_fu_354 <= ap_phi_mux_p_0_0_0_0_010893_phi_fu_449_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_4253 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_0_0_0_010893_reg_446 <= trunc_ln115_reg_3943;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_010893_reg_446 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_14;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_018845_fu_290 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_15;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_0_0_0_018845_fu_290 <= trunc_ln115_fu_1116_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_012817056_fu_314 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_21;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_012817056_fu_314 <= select_ln109_5_fu_1036_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_012883_fu_378 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_13;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_012883_fu_378 <= {{layer8_out_dout[87:80]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_022825_fu_250 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_5;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_022825_fu_250 <= {{layer8_out_dout[87:80]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_013017354_fu_310 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_20;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_013017354_fu_310 <= select_ln109_4_fu_1028_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_013082_fu_374 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_12;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_013082_fu_374 <= {{layer8_out_dout[95:88]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_023223_fu_246 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_4;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_023223_fu_246 <= {{layer8_out_dout[95:88]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_013217652_fu_306 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_19;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_013217652_fu_306 <= select_ln109_3_fu_1020_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_013281_fu_370 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_16u_0_line_buffer;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_013281_fu_370 <= {{layer8_out_dout[103:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_023621_fu_242 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_3;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_023621_fu_242 <= {{layer8_out_dout[103:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_013417950_fu_302 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_18;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_013417950_fu_302 <= select_ln109_2_fu_1012_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_013480_fu_366 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_11;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_013480_fu_366 <= {{layer8_out_dout[111:104]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_024019_fu_238 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_2;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_024019_fu_238 <= {{layer8_out_dout[111:104]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_013618248_fu_298 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_17;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_013618248_fu_298 <= select_ln109_1_fu_1004_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_013679_fu_362 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_10;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_013679_fu_362 <= {{layer8_out_dout[119:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_024417_fu_234 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_024417_fu_234 <= {{layer8_out_dout[119:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_013818546_fu_294 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_16;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_013818546_fu_294 <= select_ln109_fu_996_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_013878_fu_358 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_013878_fu_358 <= {{layer8_out_dout[127:120]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_024815_fu_230 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_024815_fu_230 <= {{layer8_out_dout[127:120]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_011014374_fu_350 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_30;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_011014374_fu_350 <= select_ln109_14_fu_1108_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_011092_fu_414 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_011092_fu_414 <= {{layer8_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_019243_fu_286 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_14;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_019243_fu_286 <= {{layer8_out_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_011214672_fu_346 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_29;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_011214672_fu_346 <= select_ln109_13_fu_1100_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_011291_fu_410 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_7;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_011291_fu_410 <= {{layer8_out_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_019641_fu_282 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_13;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_019641_fu_282 <= {{layer8_out_dout[23:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_011414970_fu_342 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_28;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_011414970_fu_342 <= select_ln109_12_fu_1092_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_011490_fu_406 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_6;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_011490_fu_406 <= {{layer8_out_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_020039_fu_278 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_12;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_020039_fu_278 <= {{layer8_out_dout[31:24]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_011615268_fu_338 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_27;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_011615268_fu_338 <= select_ln109_11_fu_1084_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_011689_fu_402 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_5;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_011689_fu_402 <= {{layer8_out_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_020437_fu_274 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_11;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_020437_fu_274 <= {{layer8_out_dout[39:32]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_011815566_fu_334 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_26;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_011815566_fu_334 <= select_ln109_10_fu_1076_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_011888_fu_398 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_4;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_011888_fu_398 <= {{layer8_out_dout[47:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_020835_fu_270 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_10;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_020835_fu_270 <= {{layer8_out_dout[47:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_012015864_fu_330 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_25;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_012015864_fu_330 <= select_ln109_9_fu_1068_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_012087_fu_394 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_3;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_012087_fu_394 <= {{layer8_out_dout[55:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_021233_fu_266 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_9;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_021233_fu_266 <= {{layer8_out_dout[55:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_012216162_fu_326 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_24;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_012216162_fu_326 <= select_ln109_8_fu_1060_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_012286_fu_390 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_2;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_012286_fu_390 <= {{layer8_out_dout[63:56]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_021631_fu_262 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_8;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_021631_fu_262 <= {{layer8_out_dout[63:56]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_012416460_fu_322 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_23;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_012416460_fu_322 <= select_ln109_7_fu_1052_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_012485_fu_386 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_012485_fu_386 <= {{layer8_out_dout[71:64]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_022029_fu_258 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_7;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_022029_fu_258 <= {{layer8_out_dout[71:64]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_012616758_fu_318 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_22;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_012616758_fu_318 <= select_ln109_6_fu_1044_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_012684_fu_382 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_012684_fu_382 <= {{layer8_out_dout[79:72]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_022427_fu_254 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_6;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_022427_fu_254 <= {{layer8_out_dout[79:72]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_163)) begin
        if ((icmp_ln76_fu_2033_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln76_fu_2033_p2 == 1'd0)) begin
            sX <= select_ln91_fu_2051_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln55_1_reg_4044 <= and_ln55_1_fu_1322_p2;
        icmp_ln109_reg_4253 <= icmp_ln109_fu_2159_p2;
        icmp_ln55_reg_4040 <= icmp_ln55_fu_1274_p2;
        select_ln0_10_reg_4108 <= select_ln0_10_fu_1599_p3;
        select_ln0_11_reg_4114 <= select_ln0_11_fu_1619_p3;
        select_ln0_12_reg_4120 <= select_ln0_12_fu_1639_p3;
        select_ln0_13_reg_4126 <= select_ln0_13_fu_1659_p3;
        select_ln0_14_reg_4132 <= select_ln0_14_fu_1679_p3;
        select_ln0_15_reg_4138 <= select_ln0_15_fu_1699_p3;
        select_ln0_16_reg_4144 <= select_ln0_16_fu_1719_p3;
        select_ln0_17_reg_4150 <= select_ln0_17_fu_1739_p3;
        select_ln0_18_reg_4156 <= select_ln0_18_fu_1759_p3;
        select_ln0_19_reg_4162 <= select_ln0_19_fu_1779_p3;
        select_ln0_1_reg_4054 <= select_ln0_1_fu_1419_p3;
        select_ln0_20_reg_4168 <= select_ln0_20_fu_1799_p3;
        select_ln0_21_reg_4174 <= select_ln0_21_fu_1819_p3;
        select_ln0_22_reg_4180 <= select_ln0_22_fu_1839_p3;
        select_ln0_23_reg_4186 <= select_ln0_23_fu_1859_p3;
        select_ln0_24_reg_4192 <= select_ln0_24_fu_1879_p3;
        select_ln0_25_reg_4198 <= select_ln0_25_fu_1899_p3;
        select_ln0_26_reg_4204 <= select_ln0_26_fu_1919_p3;
        select_ln0_27_reg_4210 <= select_ln0_27_fu_1939_p3;
        select_ln0_28_reg_4216 <= select_ln0_28_fu_1959_p3;
        select_ln0_29_reg_4222 <= select_ln0_29_fu_1979_p3;
        select_ln0_2_reg_4060 <= select_ln0_2_fu_1439_p3;
        select_ln0_30_reg_4228 <= select_ln0_30_fu_1999_p3;
        select_ln0_31_reg_4234 <= select_ln0_31_fu_2019_p3;
        select_ln0_3_reg_4066 <= select_ln0_3_fu_1459_p3;
        select_ln0_4_reg_4072 <= select_ln0_4_fu_1479_p3;
        select_ln0_5_reg_4078 <= select_ln0_5_fu_1499_p3;
        select_ln0_6_reg_4084 <= select_ln0_6_fu_1519_p3;
        select_ln0_7_reg_4090 <= select_ln0_7_fu_1539_p3;
        select_ln0_8_reg_4096 <= select_ln0_8_fu_1559_p3;
        select_ln0_9_reg_4102 <= select_ln0_9_fu_1579_p3;
        select_ln0_reg_4048 <= select_ln0_fu_1391_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        icmp_ln111_reg_4248 <= icmp_ln111_fu_2153_p2;
        select_ln109_10_reg_3918 <= select_ln109_10_fu_1076_p3;
        select_ln109_11_reg_3923 <= select_ln109_11_fu_1084_p3;
        select_ln109_12_reg_3928 <= select_ln109_12_fu_1092_p3;
        select_ln109_13_reg_3933 <= select_ln109_13_fu_1100_p3;
        select_ln109_14_reg_3938 <= select_ln109_14_fu_1108_p3;
        select_ln109_1_reg_3873 <= select_ln109_1_fu_1004_p3;
        select_ln109_2_reg_3878 <= select_ln109_2_fu_1012_p3;
        select_ln109_3_reg_3883 <= select_ln109_3_fu_1020_p3;
        select_ln109_4_reg_3888 <= select_ln109_4_fu_1028_p3;
        select_ln109_5_reg_3893 <= select_ln109_5_fu_1036_p3;
        select_ln109_6_reg_3898 <= select_ln109_6_fu_1044_p3;
        select_ln109_7_reg_3903 <= select_ln109_7_fu_1052_p3;
        select_ln109_8_reg_3908 <= select_ln109_8_fu_1060_p3;
        select_ln109_9_reg_3913 <= select_ln109_9_fu_1068_p3;
        select_ln109_reg_3868 <= select_ln109_fu_996_p3;
        trunc_ln115_10_reg_4010 <= {{layer8_out_dout[95:88]}};
        trunc_ln115_11_reg_4016 <= {{layer8_out_dout[103:96]}};
        trunc_ln115_12_reg_4022 <= {{layer8_out_dout[111:104]}};
        trunc_ln115_13_reg_4028 <= {{layer8_out_dout[119:112]}};
        trunc_ln115_14_reg_4034 <= {{layer8_out_dout[127:120]}};
        trunc_ln115_1_reg_3998 <= {{layer8_out_dout[79:72]}};
        trunc_ln115_2_reg_4004 <= {{layer8_out_dout[87:80]}};
        trunc_ln115_3_reg_3950 <= {{layer8_out_dout[15:8]}};
        trunc_ln115_4_reg_3956 <= {{layer8_out_dout[23:16]}};
        trunc_ln115_5_reg_3962 <= {{layer8_out_dout[31:24]}};
        trunc_ln115_6_reg_3968 <= {{layer8_out_dout[39:32]}};
        trunc_ln115_7_reg_3974 <= {{layer8_out_dout[47:40]}};
        trunc_ln115_8_reg_3980 <= {{layer8_out_dout[55:48]}};
        trunc_ln115_9_reg_3986 <= {{layer8_out_dout[63:56]}};
        trunc_ln115_reg_3943 <= trunc_ln115_fu_1116_p1;
        trunc_ln115_s_reg_3992 <= {{layer8_out_dout[71:64]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL <= trunc_ln115_1_reg_3998;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_1 <= trunc_ln115_s_reg_3992;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_10 <= trunc_ln115_13_reg_4028;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_11 <= trunc_ln115_12_reg_4022;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_12 <= trunc_ln115_10_reg_4010;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_13 <= trunc_ln115_2_reg_4004;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_14 <= trunc_ln115_reg_3943;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_2 <= trunc_ln115_9_reg_3986;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_3 <= trunc_ln115_8_reg_3980;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_4 <= trunc_ln115_7_reg_3974;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_5 <= trunc_ln115_6_reg_3968;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_6 <= trunc_ln115_5_reg_3962;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_7 <= trunc_ln115_4_reg_3956;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_8 <= trunc_ln115_3_reg_3950;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_o_mode3EL_9 <= trunc_ln115_14_reg_4034;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap <= trunc_ln115_14_reg_4034;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_1 <= trunc_ln115_13_reg_4028;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_10 <= trunc_ln115_7_reg_3974;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_11 <= trunc_ln115_6_reg_3968;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_12 <= trunc_ln115_5_reg_3962;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_13 <= trunc_ln115_4_reg_3956;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_14 <= trunc_ln115_3_reg_3950;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_15 <= trunc_ln115_reg_3943;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_16 <= select_ln109_reg_3868;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_17 <= select_ln109_1_reg_3873;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_18 <= select_ln109_2_reg_3878;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_19 <= select_ln109_3_reg_3883;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_2 <= trunc_ln115_12_reg_4022;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_20 <= select_ln109_4_reg_3888;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_21 <= select_ln109_5_reg_3893;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_22 <= select_ln109_6_reg_3898;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_23 <= select_ln109_7_reg_3903;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_24 <= select_ln109_8_reg_3908;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_25 <= select_ln109_9_reg_3913;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_26 <= select_ln109_10_reg_3918;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_27 <= select_ln109_11_reg_3923;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_28 <= select_ln109_12_reg_3928;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_29 <= select_ln109_13_reg_3933;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_3 <= trunc_ln115_11_reg_4016;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_30 <= select_ln109_14_reg_3938;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_31 <= p_0_0_0_0_010893_reg_446;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_4 <= trunc_ln115_10_reg_4010;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_5 <= trunc_ln115_2_reg_4004;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_6 <= trunc_ln115_1_reg_3998;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_7 <= trunc_ln115_s_reg_3992;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_8 <= trunc_ln115_9_reg_3986;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi8EL9ap_q_mode5EL9ap_9 <= trunc_ln115_8_reg_3980;
        void_pooling2d_cl_stream_stream_array_ap_ufixed_16u_0_line_buffer <= trunc_ln115_11_reg_4016;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln76_fu_2033_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        sY <= ap_phi_mux_storemerge_i_phi_fu_459_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln109_fu_2159_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_4253 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_icmp_ln11195_phi_fu_439_p4 = icmp_ln111_reg_4248;
    end else begin
        ap_phi_mux_icmp_ln11195_phi_fu_439_p4 = icmp_ln11195_reg_435;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_4253 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_0_0_0_0_010893_phi_fu_449_p4 = trunc_ln115_reg_3943;
    end else begin
        ap_phi_mux_p_0_0_0_0_010893_phi_fu_449_p4 = p_0_0_0_0_010893_reg_446;
    end
end

always @ (*) begin
    if ((icmp_ln76_fu_2033_p2 == 1'd1)) begin
        if ((icmp_ln80_fu_2087_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_i_phi_fu_459_p4 = 32'd0;
        end else if ((icmp_ln80_fu_2087_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_i_phi_fu_459_p4 = select_ln86_fu_2115_p3;
        end else begin
            ap_phi_mux_storemerge_i_phi_fu_459_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_456;
        end
    end else begin
        ap_phi_mux_storemerge_i_phi_fu_459_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_456;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln55_1_reg_4044) & (icmp_ln55_reg_4040 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op574_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_1284_p2 = (indvar_flatten12_fu_226 + 7'd1);

assign add_ln111_fu_2139_p2 = (i_iw_fu_418 + 4'd1);

assign add_ln76_fu_2027_p2 = (pX + 32'd1);

assign add_ln80_fu_2081_p2 = (pY + 32'd1);

assign add_ln86_fu_2109_p2 = (sY + 32'd1);

assign add_ln91_fu_2045_p2 = (sX + 32'd1);

assign and_ln55_1_fu_1322_p2 = (icmp_ln55_1_fu_1294_p2 & and_ln55_fu_1316_p2);

assign and_ln55_fu_1316_p2 = (icmp_ln55_3_fu_1310_p2 & icmp_ln55_2_fu_1304_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (layer8_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((layer9_out_full_n == 1'b0) & (ap_predicate_op574_write_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_163 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_426 = ((icmp_ln76_fu_2033_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_i_reg_456 = 'bx;

always @ (*) begin
    ap_predicate_op574_write_state3 = ((1'd1 == and_ln55_1_reg_4044) & (icmp_ln55_reg_4040 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign i_iw_2_fu_2145_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? 4'd1 : add_ln111_fu_2139_p2);

assign icmp_ln109_fu_2159_p2 = ((indvar_flatten12_fu_226 == 7'd120) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_2153_p2 = ((i_iw_2_fu_2145_p3 == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_1294_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_2_fu_1304_p2 = (($signed(pY) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_3_fu_1310_p2 = (($signed(pX) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_1274_p2 = ((sX == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln66_10_fu_1527_p2 = ((p_0_3_0_0_020039_fu_278 < trunc_ln115_5_fu_1140_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_11_fu_2566_p2 = ((select_ln0_6_reg_4084 < select_ln0_7_reg_4090) ? 1'b1 : 1'b0);

assign icmp_ln66_12_fu_1547_p2 = ((p_0_4_0_0_011615268_fu_338 < select_ln109_11_fu_1084_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_13_fu_1567_p2 = ((p_0_4_0_0_020437_fu_274 < trunc_ln115_6_fu_1150_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_14_fu_2618_p2 = ((select_ln0_8_reg_4096 < select_ln0_9_reg_4102) ? 1'b1 : 1'b0);

assign icmp_ln66_15_fu_1587_p2 = ((p_0_5_0_0_011815566_fu_334 < select_ln109_10_fu_1076_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_16_fu_1607_p2 = ((p_0_5_0_0_020835_fu_270 < trunc_ln115_7_fu_1160_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_17_fu_2670_p2 = ((select_ln0_10_reg_4108 < select_ln0_11_reg_4114) ? 1'b1 : 1'b0);

assign icmp_ln66_18_fu_1627_p2 = ((p_0_6_0_0_012015864_fu_330 < select_ln109_9_fu_1068_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_19_fu_1647_p2 = ((p_0_6_0_0_021233_fu_266 < trunc_ln115_8_fu_1170_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_1407_p2 = ((select_ln10996_fu_1399_p3 < trunc_ln115_fu_1116_p1) ? 1'b1 : 1'b0);

assign icmp_ln66_20_fu_2722_p2 = ((select_ln0_12_reg_4120 < select_ln0_13_reg_4126) ? 1'b1 : 1'b0);

assign icmp_ln66_21_fu_1667_p2 = ((p_0_7_0_0_012216162_fu_326 < select_ln109_8_fu_1060_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_22_fu_1687_p2 = ((p_0_7_0_0_021631_fu_262 < trunc_ln115_9_fu_1180_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_23_fu_2774_p2 = ((select_ln0_14_reg_4132 < select_ln0_15_reg_4138) ? 1'b1 : 1'b0);

assign icmp_ln66_24_fu_1707_p2 = ((p_0_8_0_0_012416460_fu_322 < select_ln109_7_fu_1052_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_25_fu_1727_p2 = ((p_0_8_0_0_022029_fu_258 < trunc_ln115_s_fu_1190_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_26_fu_2826_p2 = ((select_ln0_16_reg_4144 < select_ln0_17_reg_4150) ? 1'b1 : 1'b0);

assign icmp_ln66_27_fu_1747_p2 = ((p_0_9_0_0_012616758_fu_318 < select_ln109_6_fu_1044_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_28_fu_1767_p2 = ((p_0_9_0_0_022427_fu_254 < trunc_ln115_1_fu_1200_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_29_fu_2878_p2 = ((select_ln0_18_reg_4156 < select_ln0_19_reg_4162) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_2410_p2 = ((select_ln0_reg_4048 < select_ln0_1_reg_4054) ? 1'b1 : 1'b0);

assign icmp_ln66_30_fu_1787_p2 = ((p_0_10_0_0_012817056_fu_314 < select_ln109_5_fu_1036_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_31_fu_1807_p2 = ((p_0_10_0_0_022825_fu_250 < trunc_ln115_2_fu_1210_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_32_fu_2930_p2 = ((select_ln0_20_reg_4168 < select_ln0_21_reg_4174) ? 1'b1 : 1'b0);

assign icmp_ln66_33_fu_1827_p2 = ((p_0_11_0_0_013017354_fu_310 < select_ln109_4_fu_1028_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_34_fu_1847_p2 = ((p_0_11_0_0_023223_fu_246 < trunc_ln115_10_fu_1220_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_35_fu_2982_p2 = ((select_ln0_22_reg_4180 < select_ln0_23_reg_4186) ? 1'b1 : 1'b0);

assign icmp_ln66_36_fu_1867_p2 = ((p_0_12_0_0_013217652_fu_306 < select_ln109_3_fu_1020_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_37_fu_1887_p2 = ((p_0_12_0_0_023621_fu_242 < trunc_ln115_11_fu_1230_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_38_fu_3034_p2 = ((select_ln0_24_reg_4192 < select_ln0_25_reg_4198) ? 1'b1 : 1'b0);

assign icmp_ln66_39_fu_1907_p2 = ((p_0_13_0_0_013417950_fu_302 < select_ln109_2_fu_1012_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_1427_p2 = ((p_0_1_0_0_011014374_fu_350 < select_ln109_14_fu_1108_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_40_fu_1927_p2 = ((p_0_13_0_0_024019_fu_238 < trunc_ln115_12_fu_1240_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_41_fu_3086_p2 = ((select_ln0_26_reg_4204 < select_ln0_27_reg_4210) ? 1'b1 : 1'b0);

assign icmp_ln66_42_fu_1947_p2 = ((p_0_14_0_0_013618248_fu_298 < select_ln109_1_fu_1004_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_43_fu_1967_p2 = ((p_0_14_0_0_024417_fu_234 < trunc_ln115_13_fu_1250_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_44_fu_3138_p2 = ((select_ln0_28_reg_4216 < select_ln0_29_reg_4222) ? 1'b1 : 1'b0);

assign icmp_ln66_45_fu_1987_p2 = ((p_0_15_0_0_013818546_fu_294 < select_ln109_fu_996_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_46_fu_2007_p2 = ((p_0_15_0_0_024815_fu_230 < trunc_ln115_14_fu_1260_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_47_fu_3190_p2 = ((select_ln0_30_reg_4228 < select_ln0_31_reg_4234) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_1447_p2 = ((p_0_1_0_0_019243_fu_286 < trunc_ln115_3_fu_1120_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_5_fu_2462_p2 = ((select_ln0_2_reg_4060 < select_ln0_3_reg_4066) ? 1'b1 : 1'b0);

assign icmp_ln66_6_fu_1467_p2 = ((p_0_2_0_0_011214672_fu_346 < select_ln109_13_fu_1100_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_7_fu_1487_p2 = ((p_0_2_0_0_019641_fu_282 < trunc_ln115_4_fu_1130_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_8_fu_2514_p2 = ((select_ln0_4_reg_4072 < select_ln0_5_reg_4078) ? 1'b1 : 1'b0);

assign icmp_ln66_9_fu_1507_p2 = ((p_0_3_0_0_011414970_fu_342 < select_ln109_12_fu_1092_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_1379_p2 = ((p_0_0_0_0_010814076_fu_354 < ap_phi_mux_p_0_0_0_0_010893_phi_fu_449_p4) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_2033_p2 = ((add_ln76_fu_2027_p2 == 32'd11) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_2087_p2 = ((add_ln80_fu_2081_p2 == 32'd11) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_2103_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign layer9_out_din = {{{{{{{{{{{{{{{{res_pack_15_fu_3236_p2}, {res_pack_14_fu_3184_p2}}, {res_pack_13_fu_3132_p2}}, {res_pack_12_fu_3080_p2}}, {res_pack_11_fu_3028_p2}}, {res_pack_10_fu_2976_p2}}, {res_pack_9_fu_2924_p2}}, {res_pack_8_fu_2872_p2}}, {res_pack_7_fu_2820_p2}}, {res_pack_6_fu_2768_p2}}, {res_pack_5_fu_2716_p2}}, {res_pack_4_fu_2664_p2}}, {res_pack_3_fu_2612_p2}}, {res_pack_2_fu_2560_p2}}, {res_pack_1_fu_2508_p2}}, {res_pack_fu_2456_p2}};

assign res_pack_10_fu_2976_p2 = (trunc_ln68_s_fu_2954_p4 + zext_ln68_10_fu_2972_p1);

assign res_pack_11_fu_3028_p2 = (trunc_ln68_10_fu_3006_p4 + zext_ln68_11_fu_3024_p1);

assign res_pack_12_fu_3080_p2 = (trunc_ln68_11_fu_3058_p4 + zext_ln68_12_fu_3076_p1);

assign res_pack_13_fu_3132_p2 = (trunc_ln68_12_fu_3110_p4 + zext_ln68_13_fu_3128_p1);

assign res_pack_14_fu_3184_p2 = (trunc_ln68_13_fu_3162_p4 + zext_ln68_14_fu_3180_p1);

assign res_pack_15_fu_3236_p2 = (trunc_ln68_14_fu_3214_p4 + zext_ln68_15_fu_3232_p1);

assign res_pack_1_fu_2508_p2 = (trunc_ln68_1_fu_2486_p4 + zext_ln68_1_fu_2504_p1);

assign res_pack_2_fu_2560_p2 = (trunc_ln68_2_fu_2538_p4 + zext_ln68_2_fu_2556_p1);

assign res_pack_3_fu_2612_p2 = (trunc_ln68_3_fu_2590_p4 + zext_ln68_3_fu_2608_p1);

assign res_pack_4_fu_2664_p2 = (trunc_ln68_4_fu_2642_p4 + zext_ln68_4_fu_2660_p1);

assign res_pack_5_fu_2716_p2 = (trunc_ln68_5_fu_2694_p4 + zext_ln68_5_fu_2712_p1);

assign res_pack_6_fu_2768_p2 = (trunc_ln68_6_fu_2746_p4 + zext_ln68_6_fu_2764_p1);

assign res_pack_7_fu_2820_p2 = (trunc_ln68_7_fu_2798_p4 + zext_ln68_7_fu_2816_p1);

assign res_pack_8_fu_2872_p2 = (trunc_ln68_8_fu_2850_p4 + zext_ln68_8_fu_2868_p1);

assign res_pack_9_fu_2924_p2 = (trunc_ln68_9_fu_2902_p4 + zext_ln68_9_fu_2920_p1);

assign res_pack_fu_2456_p2 = (trunc_ln_fu_2434_p4 + zext_ln68_fu_2452_p1);

assign select_ln0_10_fu_1599_p3 = ((xor_ln66_15_fu_1593_p2[0:0] == 1'b1) ? p_0_5_0_0_011815566_fu_334 : select_ln109_10_fu_1076_p3);

assign select_ln0_11_fu_1619_p3 = ((xor_ln66_16_fu_1613_p2[0:0] == 1'b1) ? p_0_5_0_0_020835_fu_270 : trunc_ln115_7_fu_1160_p4);

assign select_ln0_12_fu_1639_p3 = ((xor_ln66_18_fu_1633_p2[0:0] == 1'b1) ? p_0_6_0_0_012015864_fu_330 : select_ln109_9_fu_1068_p3);

assign select_ln0_13_fu_1659_p3 = ((xor_ln66_19_fu_1653_p2[0:0] == 1'b1) ? p_0_6_0_0_021233_fu_266 : trunc_ln115_8_fu_1170_p4);

assign select_ln0_14_fu_1679_p3 = ((xor_ln66_21_fu_1673_p2[0:0] == 1'b1) ? p_0_7_0_0_012216162_fu_326 : select_ln109_8_fu_1060_p3);

assign select_ln0_15_fu_1699_p3 = ((xor_ln66_22_fu_1693_p2[0:0] == 1'b1) ? p_0_7_0_0_021631_fu_262 : trunc_ln115_9_fu_1180_p4);

assign select_ln0_16_fu_1719_p3 = ((xor_ln66_24_fu_1713_p2[0:0] == 1'b1) ? p_0_8_0_0_012416460_fu_322 : select_ln109_7_fu_1052_p3);

assign select_ln0_17_fu_1739_p3 = ((xor_ln66_25_fu_1733_p2[0:0] == 1'b1) ? p_0_8_0_0_022029_fu_258 : trunc_ln115_s_fu_1190_p4);

assign select_ln0_18_fu_1759_p3 = ((xor_ln66_27_fu_1753_p2[0:0] == 1'b1) ? p_0_9_0_0_012616758_fu_318 : select_ln109_6_fu_1044_p3);

assign select_ln0_19_fu_1779_p3 = ((xor_ln66_28_fu_1773_p2[0:0] == 1'b1) ? p_0_9_0_0_022427_fu_254 : trunc_ln115_1_fu_1200_p4);

assign select_ln0_1_fu_1419_p3 = ((xor_ln66_1_fu_1413_p2[0:0] == 1'b1) ? select_ln10996_fu_1399_p3 : trunc_ln115_fu_1116_p1);

assign select_ln0_20_fu_1799_p3 = ((xor_ln66_30_fu_1793_p2[0:0] == 1'b1) ? p_0_10_0_0_012817056_fu_314 : select_ln109_5_fu_1036_p3);

assign select_ln0_21_fu_1819_p3 = ((xor_ln66_31_fu_1813_p2[0:0] == 1'b1) ? p_0_10_0_0_022825_fu_250 : trunc_ln115_2_fu_1210_p4);

assign select_ln0_22_fu_1839_p3 = ((xor_ln66_33_fu_1833_p2[0:0] == 1'b1) ? p_0_11_0_0_013017354_fu_310 : select_ln109_4_fu_1028_p3);

assign select_ln0_23_fu_1859_p3 = ((xor_ln66_34_fu_1853_p2[0:0] == 1'b1) ? p_0_11_0_0_023223_fu_246 : trunc_ln115_10_fu_1220_p4);

assign select_ln0_24_fu_1879_p3 = ((xor_ln66_36_fu_1873_p2[0:0] == 1'b1) ? p_0_12_0_0_013217652_fu_306 : select_ln109_3_fu_1020_p3);

assign select_ln0_25_fu_1899_p3 = ((xor_ln66_37_fu_1893_p2[0:0] == 1'b1) ? p_0_12_0_0_023621_fu_242 : trunc_ln115_11_fu_1230_p4);

assign select_ln0_26_fu_1919_p3 = ((xor_ln66_39_fu_1913_p2[0:0] == 1'b1) ? p_0_13_0_0_013417950_fu_302 : select_ln109_2_fu_1012_p3);

assign select_ln0_27_fu_1939_p3 = ((xor_ln66_40_fu_1933_p2[0:0] == 1'b1) ? p_0_13_0_0_024019_fu_238 : trunc_ln115_12_fu_1240_p4);

assign select_ln0_28_fu_1959_p3 = ((xor_ln66_42_fu_1953_p2[0:0] == 1'b1) ? p_0_14_0_0_013618248_fu_298 : select_ln109_1_fu_1004_p3);

assign select_ln0_29_fu_1979_p3 = ((xor_ln66_43_fu_1973_p2[0:0] == 1'b1) ? p_0_14_0_0_024417_fu_234 : trunc_ln115_13_fu_1250_p4);

assign select_ln0_2_fu_1439_p3 = ((xor_ln66_3_fu_1433_p2[0:0] == 1'b1) ? p_0_1_0_0_011014374_fu_350 : select_ln109_14_fu_1108_p3);

assign select_ln0_30_fu_1999_p3 = ((xor_ln66_45_fu_1993_p2[0:0] == 1'b1) ? p_0_15_0_0_013818546_fu_294 : select_ln109_fu_996_p3);

assign select_ln0_31_fu_2019_p3 = ((xor_ln66_46_fu_2013_p2[0:0] == 1'b1) ? p_0_15_0_0_024815_fu_230 : trunc_ln115_14_fu_1260_p4);

assign select_ln0_3_fu_1459_p3 = ((xor_ln66_4_fu_1453_p2[0:0] == 1'b1) ? p_0_1_0_0_019243_fu_286 : trunc_ln115_3_fu_1120_p4);

assign select_ln0_4_fu_1479_p3 = ((xor_ln66_6_fu_1473_p2[0:0] == 1'b1) ? p_0_2_0_0_011214672_fu_346 : select_ln109_13_fu_1100_p3);

assign select_ln0_5_fu_1499_p3 = ((xor_ln66_7_fu_1493_p2[0:0] == 1'b1) ? p_0_2_0_0_019641_fu_282 : trunc_ln115_4_fu_1130_p4);

assign select_ln0_6_fu_1519_p3 = ((xor_ln66_9_fu_1513_p2[0:0] == 1'b1) ? p_0_3_0_0_011414970_fu_342 : select_ln109_12_fu_1092_p3);

assign select_ln0_7_fu_1539_p3 = ((xor_ln66_10_fu_1533_p2[0:0] == 1'b1) ? p_0_3_0_0_020039_fu_278 : trunc_ln115_5_fu_1140_p4);

assign select_ln0_8_fu_1559_p3 = ((xor_ln66_12_fu_1553_p2[0:0] == 1'b1) ? p_0_4_0_0_011615268_fu_338 : select_ln109_11_fu_1084_p3);

assign select_ln0_9_fu_1579_p3 = ((xor_ln66_13_fu_1573_p2[0:0] == 1'b1) ? p_0_4_0_0_020437_fu_274 : trunc_ln115_6_fu_1150_p4);

assign select_ln0_fu_1391_p3 = ((xor_ln66_fu_1385_p2[0:0] == 1'b1) ? p_0_0_0_0_010814076_fu_354 : ap_phi_mux_p_0_0_0_0_010893_phi_fu_449_p4);

assign select_ln10996_fu_1399_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0_0_010893_phi_fu_449_p4 : p_0_0_0_0_018845_fu_290);

assign select_ln109_10_fu_1076_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_5_0_0_020835_fu_270 : p_0_5_0_0_011888_fu_398);

assign select_ln109_11_fu_1084_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_4_0_0_020437_fu_274 : p_0_4_0_0_011689_fu_402);

assign select_ln109_12_fu_1092_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_3_0_0_020039_fu_278 : p_0_3_0_0_011490_fu_406);

assign select_ln109_13_fu_1100_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_2_0_0_019641_fu_282 : p_0_2_0_0_011291_fu_410);

assign select_ln109_14_fu_1108_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_1_0_0_019243_fu_286 : p_0_1_0_0_011092_fu_414);

assign select_ln109_1_fu_1004_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_14_0_0_024417_fu_234 : p_0_14_0_0_013679_fu_362);

assign select_ln109_2_fu_1012_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_13_0_0_024019_fu_238 : p_0_13_0_0_013480_fu_366);

assign select_ln109_3_fu_1020_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_12_0_0_023621_fu_242 : p_0_12_0_0_013281_fu_370);

assign select_ln109_4_fu_1028_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_11_0_0_023223_fu_246 : p_0_11_0_0_013082_fu_374);

assign select_ln109_5_fu_1036_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_10_0_0_022825_fu_250 : p_0_10_0_0_012883_fu_378);

assign select_ln109_6_fu_1044_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_9_0_0_022427_fu_254 : p_0_9_0_0_012684_fu_382);

assign select_ln109_7_fu_1052_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_8_0_0_022029_fu_258 : p_0_8_0_0_012485_fu_386);

assign select_ln109_8_fu_1060_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_7_0_0_021631_fu_262 : p_0_7_0_0_012286_fu_390);

assign select_ln109_9_fu_1068_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_6_0_0_021233_fu_266 : p_0_6_0_0_012087_fu_394);

assign select_ln109_fu_996_p3 = ((ap_phi_mux_icmp_ln11195_phi_fu_439_p4[0:0] == 1'b1) ? p_0_15_0_0_024815_fu_230 : p_0_15_0_0_013878_fu_358);

assign select_ln66_10_fu_2940_p3 = ((xor_ln66_32_fu_2934_p2[0:0] == 1'b1) ? select_ln0_20_reg_4168 : select_ln0_21_reg_4174);

assign select_ln66_11_fu_2992_p3 = ((xor_ln66_35_fu_2986_p2[0:0] == 1'b1) ? select_ln0_22_reg_4180 : select_ln0_23_reg_4186);

assign select_ln66_12_fu_3044_p3 = ((xor_ln66_38_fu_3038_p2[0:0] == 1'b1) ? select_ln0_24_reg_4192 : select_ln0_25_reg_4198);

assign select_ln66_13_fu_3096_p3 = ((xor_ln66_41_fu_3090_p2[0:0] == 1'b1) ? select_ln0_26_reg_4204 : select_ln0_27_reg_4210);

assign select_ln66_14_fu_3148_p3 = ((xor_ln66_44_fu_3142_p2[0:0] == 1'b1) ? select_ln0_28_reg_4216 : select_ln0_29_reg_4222);

assign select_ln66_15_fu_3200_p3 = ((xor_ln66_47_fu_3194_p2[0:0] == 1'b1) ? select_ln0_30_reg_4228 : select_ln0_31_reg_4234);

assign select_ln66_1_fu_2472_p3 = ((xor_ln66_5_fu_2466_p2[0:0] == 1'b1) ? select_ln0_2_reg_4060 : select_ln0_3_reg_4066);

assign select_ln66_2_fu_2524_p3 = ((xor_ln66_8_fu_2518_p2[0:0] == 1'b1) ? select_ln0_4_reg_4072 : select_ln0_5_reg_4078);

assign select_ln66_3_fu_2576_p3 = ((xor_ln66_11_fu_2570_p2[0:0] == 1'b1) ? select_ln0_6_reg_4084 : select_ln0_7_reg_4090);

assign select_ln66_4_fu_2628_p3 = ((xor_ln66_14_fu_2622_p2[0:0] == 1'b1) ? select_ln0_8_reg_4096 : select_ln0_9_reg_4102);

assign select_ln66_5_fu_2680_p3 = ((xor_ln66_17_fu_2674_p2[0:0] == 1'b1) ? select_ln0_10_reg_4108 : select_ln0_11_reg_4114);

assign select_ln66_6_fu_2732_p3 = ((xor_ln66_20_fu_2726_p2[0:0] == 1'b1) ? select_ln0_12_reg_4120 : select_ln0_13_reg_4126);

assign select_ln66_7_fu_2784_p3 = ((xor_ln66_23_fu_2778_p2[0:0] == 1'b1) ? select_ln0_14_reg_4132 : select_ln0_15_reg_4138);

assign select_ln66_8_fu_2836_p3 = ((xor_ln66_26_fu_2830_p2[0:0] == 1'b1) ? select_ln0_16_reg_4144 : select_ln0_17_reg_4150);

assign select_ln66_9_fu_2888_p3 = ((xor_ln66_29_fu_2882_p2[0:0] == 1'b1) ? select_ln0_18_reg_4156 : select_ln0_19_reg_4162);

assign select_ln66_fu_2420_p3 = ((xor_ln66_2_fu_2414_p2[0:0] == 1'b1) ? select_ln0_reg_4048 : select_ln0_1_reg_4054);

assign select_ln86_fu_2115_p3 = ((icmp_ln86_fu_2103_p2[0:0] == 1'b1) ? 32'd0 : add_ln86_fu_2109_p2);

assign select_ln91_fu_2051_p3 = ((icmp_ln55_fu_1274_p2[0:0] == 1'b1) ? 32'd0 : add_ln91_fu_2045_p2);

assign start_out = real_start;

assign tmp_10_fu_2964_p3 = zext_ln68_26_fu_2950_p1[32'd3];

assign tmp_11_fu_3016_p3 = zext_ln68_27_fu_3002_p1[32'd3];

assign tmp_12_fu_3068_p3 = zext_ln68_28_fu_3054_p1[32'd3];

assign tmp_13_fu_3120_p3 = zext_ln68_29_fu_3106_p1[32'd3];

assign tmp_14_fu_3172_p3 = zext_ln68_30_fu_3158_p1[32'd3];

assign tmp_15_fu_3224_p3 = zext_ln68_31_fu_3210_p1[32'd3];

assign tmp_1_fu_2496_p3 = zext_ln68_17_fu_2482_p1[32'd3];

assign tmp_2_fu_2548_p3 = zext_ln68_18_fu_2534_p1[32'd3];

assign tmp_3_fu_2600_p3 = zext_ln68_19_fu_2586_p1[32'd3];

assign tmp_4_fu_2652_p3 = zext_ln68_20_fu_2638_p1[32'd3];

assign tmp_5_fu_2704_p3 = zext_ln68_21_fu_2690_p1[32'd3];

assign tmp_6_fu_2756_p3 = zext_ln68_22_fu_2742_p1[32'd3];

assign tmp_7_fu_2808_p3 = zext_ln68_23_fu_2794_p1[32'd3];

assign tmp_8_fu_2860_p3 = zext_ln68_24_fu_2846_p1[32'd3];

assign tmp_9_fu_2912_p3 = zext_ln68_25_fu_2898_p1[32'd3];

assign tmp_fu_2444_p3 = zext_ln68_16_fu_2430_p1[32'd3];

assign trunc_ln115_10_fu_1220_p4 = {{layer8_out_dout[95:88]}};

assign trunc_ln115_11_fu_1230_p4 = {{layer8_out_dout[103:96]}};

assign trunc_ln115_12_fu_1240_p4 = {{layer8_out_dout[111:104]}};

assign trunc_ln115_13_fu_1250_p4 = {{layer8_out_dout[119:112]}};

assign trunc_ln115_14_fu_1260_p4 = {{layer8_out_dout[127:120]}};

assign trunc_ln115_1_fu_1200_p4 = {{layer8_out_dout[79:72]}};

assign trunc_ln115_2_fu_1210_p4 = {{layer8_out_dout[87:80]}};

assign trunc_ln115_3_fu_1120_p4 = {{layer8_out_dout[15:8]}};

assign trunc_ln115_4_fu_1130_p4 = {{layer8_out_dout[23:16]}};

assign trunc_ln115_5_fu_1140_p4 = {{layer8_out_dout[31:24]}};

assign trunc_ln115_6_fu_1150_p4 = {{layer8_out_dout[39:32]}};

assign trunc_ln115_7_fu_1160_p4 = {{layer8_out_dout[47:40]}};

assign trunc_ln115_8_fu_1170_p4 = {{layer8_out_dout[55:48]}};

assign trunc_ln115_9_fu_1180_p4 = {{layer8_out_dout[63:56]}};

assign trunc_ln115_fu_1116_p1 = layer8_out_dout[7:0];

assign trunc_ln115_s_fu_1190_p4 = {{layer8_out_dout[71:64]}};

assign trunc_ln66_10_fu_2946_p1 = select_ln66_10_fu_2940_p3[5:0];

assign trunc_ln66_11_fu_2998_p1 = select_ln66_11_fu_2992_p3[5:0];

assign trunc_ln66_12_fu_3050_p1 = select_ln66_12_fu_3044_p3[5:0];

assign trunc_ln66_13_fu_3102_p1 = select_ln66_13_fu_3096_p3[5:0];

assign trunc_ln66_14_fu_3154_p1 = select_ln66_14_fu_3148_p3[5:0];

assign trunc_ln66_15_fu_3206_p1 = select_ln66_15_fu_3200_p3[5:0];

assign trunc_ln66_1_fu_2478_p1 = select_ln66_1_fu_2472_p3[5:0];

assign trunc_ln66_2_fu_2530_p1 = select_ln66_2_fu_2524_p3[5:0];

assign trunc_ln66_3_fu_2582_p1 = select_ln66_3_fu_2576_p3[5:0];

assign trunc_ln66_4_fu_2634_p1 = select_ln66_4_fu_2628_p3[5:0];

assign trunc_ln66_5_fu_2686_p1 = select_ln66_5_fu_2680_p3[5:0];

assign trunc_ln66_6_fu_2738_p1 = select_ln66_6_fu_2732_p3[5:0];

assign trunc_ln66_7_fu_2790_p1 = select_ln66_7_fu_2784_p3[5:0];

assign trunc_ln66_8_fu_2842_p1 = select_ln66_8_fu_2836_p3[5:0];

assign trunc_ln66_9_fu_2894_p1 = select_ln66_9_fu_2888_p3[5:0];

assign trunc_ln66_fu_2426_p1 = select_ln66_fu_2420_p3[5:0];

assign trunc_ln68_10_fu_3006_p4 = {{select_ln66_11_fu_2992_p3[5:4]}};

assign trunc_ln68_11_fu_3058_p4 = {{select_ln66_12_fu_3044_p3[5:4]}};

assign trunc_ln68_12_fu_3110_p4 = {{select_ln66_13_fu_3096_p3[5:4]}};

assign trunc_ln68_13_fu_3162_p4 = {{select_ln66_14_fu_3148_p3[5:4]}};

assign trunc_ln68_14_fu_3214_p4 = {{select_ln66_15_fu_3200_p3[5:4]}};

assign trunc_ln68_1_fu_2486_p4 = {{select_ln66_1_fu_2472_p3[5:4]}};

assign trunc_ln68_2_fu_2538_p4 = {{select_ln66_2_fu_2524_p3[5:4]}};

assign trunc_ln68_3_fu_2590_p4 = {{select_ln66_3_fu_2576_p3[5:4]}};

assign trunc_ln68_4_fu_2642_p4 = {{select_ln66_4_fu_2628_p3[5:4]}};

assign trunc_ln68_5_fu_2694_p4 = {{select_ln66_5_fu_2680_p3[5:4]}};

assign trunc_ln68_6_fu_2746_p4 = {{select_ln66_6_fu_2732_p3[5:4]}};

assign trunc_ln68_7_fu_2798_p4 = {{select_ln66_7_fu_2784_p3[5:4]}};

assign trunc_ln68_8_fu_2850_p4 = {{select_ln66_8_fu_2836_p3[5:4]}};

assign trunc_ln68_9_fu_2902_p4 = {{select_ln66_9_fu_2888_p3[5:4]}};

assign trunc_ln68_s_fu_2954_p4 = {{select_ln66_10_fu_2940_p3[5:4]}};

assign trunc_ln_fu_2434_p4 = {{select_ln66_fu_2420_p3[5:4]}};

assign xor_ln66_10_fu_1533_p2 = (icmp_ln66_10_fu_1527_p2 ^ 1'd1);

assign xor_ln66_11_fu_2570_p2 = (icmp_ln66_11_fu_2566_p2 ^ 1'd1);

assign xor_ln66_12_fu_1553_p2 = (icmp_ln66_12_fu_1547_p2 ^ 1'd1);

assign xor_ln66_13_fu_1573_p2 = (icmp_ln66_13_fu_1567_p2 ^ 1'd1);

assign xor_ln66_14_fu_2622_p2 = (icmp_ln66_14_fu_2618_p2 ^ 1'd1);

assign xor_ln66_15_fu_1593_p2 = (icmp_ln66_15_fu_1587_p2 ^ 1'd1);

assign xor_ln66_16_fu_1613_p2 = (icmp_ln66_16_fu_1607_p2 ^ 1'd1);

assign xor_ln66_17_fu_2674_p2 = (icmp_ln66_17_fu_2670_p2 ^ 1'd1);

assign xor_ln66_18_fu_1633_p2 = (icmp_ln66_18_fu_1627_p2 ^ 1'd1);

assign xor_ln66_19_fu_1653_p2 = (icmp_ln66_19_fu_1647_p2 ^ 1'd1);

assign xor_ln66_1_fu_1413_p2 = (icmp_ln66_1_fu_1407_p2 ^ 1'd1);

assign xor_ln66_20_fu_2726_p2 = (icmp_ln66_20_fu_2722_p2 ^ 1'd1);

assign xor_ln66_21_fu_1673_p2 = (icmp_ln66_21_fu_1667_p2 ^ 1'd1);

assign xor_ln66_22_fu_1693_p2 = (icmp_ln66_22_fu_1687_p2 ^ 1'd1);

assign xor_ln66_23_fu_2778_p2 = (icmp_ln66_23_fu_2774_p2 ^ 1'd1);

assign xor_ln66_24_fu_1713_p2 = (icmp_ln66_24_fu_1707_p2 ^ 1'd1);

assign xor_ln66_25_fu_1733_p2 = (icmp_ln66_25_fu_1727_p2 ^ 1'd1);

assign xor_ln66_26_fu_2830_p2 = (icmp_ln66_26_fu_2826_p2 ^ 1'd1);

assign xor_ln66_27_fu_1753_p2 = (icmp_ln66_27_fu_1747_p2 ^ 1'd1);

assign xor_ln66_28_fu_1773_p2 = (icmp_ln66_28_fu_1767_p2 ^ 1'd1);

assign xor_ln66_29_fu_2882_p2 = (icmp_ln66_29_fu_2878_p2 ^ 1'd1);

assign xor_ln66_2_fu_2414_p2 = (icmp_ln66_2_fu_2410_p2 ^ 1'd1);

assign xor_ln66_30_fu_1793_p2 = (icmp_ln66_30_fu_1787_p2 ^ 1'd1);

assign xor_ln66_31_fu_1813_p2 = (icmp_ln66_31_fu_1807_p2 ^ 1'd1);

assign xor_ln66_32_fu_2934_p2 = (icmp_ln66_32_fu_2930_p2 ^ 1'd1);

assign xor_ln66_33_fu_1833_p2 = (icmp_ln66_33_fu_1827_p2 ^ 1'd1);

assign xor_ln66_34_fu_1853_p2 = (icmp_ln66_34_fu_1847_p2 ^ 1'd1);

assign xor_ln66_35_fu_2986_p2 = (icmp_ln66_35_fu_2982_p2 ^ 1'd1);

assign xor_ln66_36_fu_1873_p2 = (icmp_ln66_36_fu_1867_p2 ^ 1'd1);

assign xor_ln66_37_fu_1893_p2 = (icmp_ln66_37_fu_1887_p2 ^ 1'd1);

assign xor_ln66_38_fu_3038_p2 = (icmp_ln66_38_fu_3034_p2 ^ 1'd1);

assign xor_ln66_39_fu_1913_p2 = (icmp_ln66_39_fu_1907_p2 ^ 1'd1);

assign xor_ln66_3_fu_1433_p2 = (icmp_ln66_3_fu_1427_p2 ^ 1'd1);

assign xor_ln66_40_fu_1933_p2 = (icmp_ln66_40_fu_1927_p2 ^ 1'd1);

assign xor_ln66_41_fu_3090_p2 = (icmp_ln66_41_fu_3086_p2 ^ 1'd1);

assign xor_ln66_42_fu_1953_p2 = (icmp_ln66_42_fu_1947_p2 ^ 1'd1);

assign xor_ln66_43_fu_1973_p2 = (icmp_ln66_43_fu_1967_p2 ^ 1'd1);

assign xor_ln66_44_fu_3142_p2 = (icmp_ln66_44_fu_3138_p2 ^ 1'd1);

assign xor_ln66_45_fu_1993_p2 = (icmp_ln66_45_fu_1987_p2 ^ 1'd1);

assign xor_ln66_46_fu_2013_p2 = (icmp_ln66_46_fu_2007_p2 ^ 1'd1);

assign xor_ln66_47_fu_3194_p2 = (icmp_ln66_47_fu_3190_p2 ^ 1'd1);

assign xor_ln66_4_fu_1453_p2 = (icmp_ln66_4_fu_1447_p2 ^ 1'd1);

assign xor_ln66_5_fu_2466_p2 = (icmp_ln66_5_fu_2462_p2 ^ 1'd1);

assign xor_ln66_6_fu_1473_p2 = (icmp_ln66_6_fu_1467_p2 ^ 1'd1);

assign xor_ln66_7_fu_1493_p2 = (icmp_ln66_7_fu_1487_p2 ^ 1'd1);

assign xor_ln66_8_fu_2518_p2 = (icmp_ln66_8_fu_2514_p2 ^ 1'd1);

assign xor_ln66_9_fu_1513_p2 = (icmp_ln66_9_fu_1507_p2 ^ 1'd1);

assign xor_ln66_fu_1385_p2 = (icmp_ln66_fu_1379_p2 ^ 1'd1);

assign zext_ln68_10_fu_2972_p1 = tmp_10_fu_2964_p3;

assign zext_ln68_11_fu_3024_p1 = tmp_11_fu_3016_p3;

assign zext_ln68_12_fu_3076_p1 = tmp_12_fu_3068_p3;

assign zext_ln68_13_fu_3128_p1 = tmp_13_fu_3120_p3;

assign zext_ln68_14_fu_3180_p1 = tmp_14_fu_3172_p3;

assign zext_ln68_15_fu_3232_p1 = tmp_15_fu_3224_p3;

assign zext_ln68_16_fu_2430_p1 = trunc_ln66_fu_2426_p1;

assign zext_ln68_17_fu_2482_p1 = trunc_ln66_1_fu_2478_p1;

assign zext_ln68_18_fu_2534_p1 = trunc_ln66_2_fu_2530_p1;

assign zext_ln68_19_fu_2586_p1 = trunc_ln66_3_fu_2582_p1;

assign zext_ln68_1_fu_2504_p1 = tmp_1_fu_2496_p3;

assign zext_ln68_20_fu_2638_p1 = trunc_ln66_4_fu_2634_p1;

assign zext_ln68_21_fu_2690_p1 = trunc_ln66_5_fu_2686_p1;

assign zext_ln68_22_fu_2742_p1 = trunc_ln66_6_fu_2738_p1;

assign zext_ln68_23_fu_2794_p1 = trunc_ln66_7_fu_2790_p1;

assign zext_ln68_24_fu_2846_p1 = trunc_ln66_8_fu_2842_p1;

assign zext_ln68_25_fu_2898_p1 = trunc_ln66_9_fu_2894_p1;

assign zext_ln68_26_fu_2950_p1 = trunc_ln66_10_fu_2946_p1;

assign zext_ln68_27_fu_3002_p1 = trunc_ln66_11_fu_2998_p1;

assign zext_ln68_28_fu_3054_p1 = trunc_ln66_12_fu_3050_p1;

assign zext_ln68_29_fu_3106_p1 = trunc_ln66_13_fu_3102_p1;

assign zext_ln68_2_fu_2556_p1 = tmp_2_fu_2548_p3;

assign zext_ln68_30_fu_3158_p1 = trunc_ln66_14_fu_3154_p1;

assign zext_ln68_31_fu_3210_p1 = trunc_ln66_15_fu_3206_p1;

assign zext_ln68_3_fu_2608_p1 = tmp_3_fu_2600_p3;

assign zext_ln68_4_fu_2660_p1 = tmp_4_fu_2652_p3;

assign zext_ln68_5_fu_2712_p1 = tmp_5_fu_2704_p3;

assign zext_ln68_6_fu_2764_p1 = tmp_6_fu_2756_p3;

assign zext_ln68_7_fu_2816_p1 = tmp_7_fu_2808_p3;

assign zext_ln68_8_fu_2868_p1 = tmp_8_fu_2860_p3;

assign zext_ln68_9_fu_2920_p1 = tmp_9_fu_2912_p3;

assign zext_ln68_fu_2452_p1 = tmp_fu_2444_p3;

endmodule //myproject_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_s
