// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_dense_latency_ap_ufixed_1_5_0_3_0_ap_fixed_9_9_5_3_0_config7_mult_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_18,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_14,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_13,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_12,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_11,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_10,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_9,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_8,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_7,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_6,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_5,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_4,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_3,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_2,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_1,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_22,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_21,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_16,
        p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_15,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
input  [0:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_18;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_14;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_13;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_12;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_11;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_10;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_9;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_8;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_7;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_6;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_5;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_4;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_3;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_2;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_1;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_22;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_21;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_16;
input  [0:0] p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_15;
output  [8:0] ap_return_0;
output  [8:0] ap_return_1;
output  [8:0] ap_return_2;
output  [8:0] ap_return_3;
output  [8:0] ap_return_4;
output  [8:0] ap_return_5;
output  [8:0] ap_return_6;
output  [8:0] ap_return_7;
output  [8:0] ap_return_8;
output  [8:0] ap_return_9;
output  [8:0] ap_return_10;
output  [8:0] ap_return_11;
output  [8:0] ap_return_12;
output  [8:0] ap_return_13;
output  [8:0] ap_return_14;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] a_reg_3308;
reg   [0:0] a_1_reg_3314;
reg   [0:0] a_2_reg_3322;
reg   [0:0] a_3_reg_3330;
reg   [0:0] a_4_reg_3340;
reg   [0:0] a_5_reg_3349;
reg   [0:0] a_6_reg_3356;
reg   [0:0] a_7_reg_3366;
reg   [0:0] a_8_reg_3373;
reg   [0:0] a_9_reg_3380;
reg   [0:0] a_10_reg_3392;
reg   [0:0] a_11_reg_3400;
wire   [3:0] zext_ln17_942_fu_304_p1;
reg   [3:0] zext_ln17_942_reg_3409;
reg   [0:0] a_12_reg_3414;
reg   [0:0] a_13_reg_3421;
reg   [0:0] a_15_reg_3433;
wire   [3:0] zext_ln17_947_fu_340_p1;
reg   [3:0] zext_ln17_947_reg_3444;
reg   [0:0] a_16_reg_3449;
reg   [0:0] a_20_reg_3466;
wire   [4:0] select_ln58_2_fu_384_p3;
reg   [4:0] select_ln58_2_reg_3477;
wire   [4:0] add_ln58_2823_fu_422_p2;
reg   [4:0] add_ln58_2823_reg_3482;
wire   [4:0] add_ln58_2826_fu_474_p2;
reg   [4:0] add_ln58_2826_reg_3487;
wire   [5:0] add_ln58_2830_fu_510_p2;
reg   [5:0] add_ln58_2830_reg_3492;
wire   [3:0] select_ln58_36_fu_540_p3;
reg   [3:0] select_ln58_36_reg_3497;
wire   [5:0] add_ln58_2841_fu_562_p2;
reg   [5:0] add_ln58_2841_reg_3502;
wire   [3:0] add_ln58_2845_fu_568_p2;
reg   [3:0] add_ln58_2845_reg_3507;
wire   [3:0] tmp4822_i_fu_606_p2;
reg   [3:0] tmp4822_i_reg_3512;
wire   [2:0] add_ln58_2877_fu_612_p2;
reg   [2:0] add_ln58_2877_reg_3517;
wire   [5:0] add_ln58_2920_fu_692_p2;
reg   [5:0] add_ln58_2920_reg_3522;
wire   [3:0] add_ln58_2939_fu_698_p2;
reg   [3:0] add_ln58_2939_reg_3527;
wire    ap_CS_fsm_state2;
wire   [1:0] mult_fu_192_p3;
wire   [3:0] mult_1731_fu_224_p3;
wire   [2:0] mult_1732_fu_240_p3;
wire   [3:0] mult_1735_fu_272_p3;
wire   [2:0] mult_1737_fu_296_p3;
wire   [2:0] mult_1738_fu_312_p3;
wire   [2:0] mult_1741_fu_332_p3;
wire   [1:0] mult_1743_fu_348_p3;
wire   [1:0] mult_1747_fu_364_p3;
wire   [4:0] select_ln58_4_fu_392_p3;
wire   [3:0] select_ln58_11_fu_408_p3;
wire   [3:0] zext_ln17_930_fu_200_p1;
wire   [4:0] select_ln58_5_fu_400_p3;
wire   [4:0] zext_ln17_933_fu_232_p1;
wire   [3:0] tmp_fu_428_p4;
wire   [4:0] zext_ln58_fu_438_p1;
wire   [4:0] select_ln58_fu_376_p3;
wire   [4:0] add_ln58_2825_fu_442_p2;
wire   [3:0] or_ln58_4_fu_452_p4;
wire   [4:0] select_ln58_19_fu_466_p3;
wire  signed [4:0] sext_ln58_68_fu_462_p1;
wire   [1:0] select_ln58_26_fu_480_p3;
wire   [4:0] or_ln58_5_fu_488_p4;
wire   [5:0] select_ln58_28_fu_502_p3;
wire  signed [5:0] sext_ln58_79_fu_498_p1;
wire   [3:0] select_ln58_34_fu_524_p3;
wire   [3:0] select_ln58_37_fu_532_p3;
wire   [3:0] tmp5_fu_548_p4;
wire   [5:0] zext_ln58_1924_fu_558_p1;
wire  signed [5:0] sext_ln58_65_fu_448_p1;
wire   [3:0] add_ln58_2822_fu_416_p2;
wire   [3:0] zext_ln17_fu_248_p1;
wire   [1:0] shl_ln73_2_fu_216_p3;
wire   [1:0] shl_ln73_5_fu_264_p3;
wire   [2:0] shl_ln73_670_cast_i_fu_578_p1;
wire   [2:0] shl_ln73_663_cast_i_fu_574_p1;
wire   [2:0] empty_fu_582_p2;
wire   [2:0] tmp7_fu_592_p4;
wire   [3:0] tmp30_cast_fu_602_p1;
wire   [3:0] p_cast_i_fu_588_p1;
wire   [2:0] zext_ln17_950_fu_356_p1;
wire   [2:0] zext_ln42_fu_372_p1;
wire   [4:0] select_ln58_121_fu_618_p3;
wire   [4:0] select_ln58_125_fu_626_p3;
wire   [3:0] tmp9_fu_642_p4;
wire   [4:0] zext_ln58_1943_fu_652_p1;
wire   [4:0] select_ln58_123_fu_634_p3;
wire   [4:0] add_ln58_2916_fu_656_p2;
wire   [5:0] select_ln58_32_fu_516_p3;
wire  signed [5:0] sext_ln58_146_fu_662_p1;
wire   [3:0] zext_ln17_943_fu_320_p1;
wire   [3:0] add_ln58_2918_fu_672_p2;
wire   [4:0] zext_ln58_1944_fu_678_p1;
wire   [4:0] zext_ln17_939_fu_280_p1;
wire   [4:0] add_ln58_2919_fu_682_p2;
wire   [5:0] zext_ln58_1945_fu_688_p1;
wire   [5:0] add_ln58_2917_fu_666_p2;
wire   [2:0] mult_1733_fu_725_p3;
wire   [3:0] mult_1734_fu_743_p3;
wire   [2:0] mult_1736_fu_754_p3;
wire   [3:0] mult_1739_fu_769_p3;
wire   [3:0] mult_1740_fu_788_p3;
wire   [3:0] mult_1742_fu_800_p3;
wire   [3:0] mult_1744_fu_819_p3;
wire   [2:0] mult_1745_fu_835_p3;
wire   [3:0] mult_1746_fu_859_p3;
wire   [2:0] mult_1_fu_871_p3;
wire   [2:0] mult_1748_fu_890_p3;
wire   [2:0] mult_1749_fu_914_p3;
wire   [3:0] mult_1750_fu_926_p3;
wire   [2:0] mult_1751_fu_942_p3;
wire   [3:0] mult_1752_fu_958_p3;
wire   [2:0] mult_1753_fu_982_p3;
wire   [2:0] mult_1754_fu_998_p3;
wire   [4:0] select_ln58_1_fu_1030_p3;
wire   [4:0] select_ln58_3_fu_1037_p3;
wire   [5:0] select_ln58_6_fu_1047_p3;
wire   [5:0] select_ln58_7_fu_1054_p3;
wire   [2:0] or_ln_fu_1068_p4;
wire   [5:0] select_ln58_9_fu_1080_p3;
wire  signed [5:0] sext_ln58_fu_1043_p1;
wire   [6:0] select_ln58_12_fu_1103_p3;
wire  signed [6:0] sext_ln58_61_fu_1076_p1;
wire   [6:0] add_ln58_2824_fu_1110_p2;
wire   [2:0] select_ln58_15_fu_1134_p3;
wire   [2:0] select_ln58_17_fu_1141_p3;
wire   [2:0] select_ln58_16_fu_1148_p3;
wire   [4:0] or_ln58_3_fu_1155_p4;
wire   [5:0] select_ln58_21_fu_1185_p3;
wire  signed [5:0] sext_ln58_71_fu_1182_p1;
wire   [5:0] add_ln58_2827_fu_1199_p2;
wire   [5:0] select_ln58_23_fu_1216_p3;
wire   [5:0] select_ln58_27_fu_1223_p3;
wire   [5:0] select_ln58_25_fu_1230_p3;
wire   [5:0] add_ln58_fu_1087_p2;
wire   [5:0] zext_ln17_940_fu_761_p1;
wire   [5:0] add_ln58_2828_fu_1241_p2;
wire  signed [6:0] sext_ln58_760_fu_1247_p1;
wire  signed [6:0] sext_ln58_759_fu_1237_p1;
wire   [5:0] select_ln58_31_fu_1274_p3;
wire   [5:0] select_ln58_35_fu_1281_p3;
wire   [6:0] select_ln58_30_fu_1267_p3;
wire  signed [6:0] sext_ln58_84_fu_1257_p1;
wire   [6:0] add_ln58_2831_fu_1295_p2;
wire  signed [5:0] sext_ln58_63_fu_1100_p1;
wire   [5:0] zext_ln17_944_fu_776_p1;
wire   [5:0] add_ln58_2832_fu_1308_p2;
wire  signed [5:0] sext_ln58_761_fu_1305_p1;
wire   [5:0] add_ln58_2833_fu_1314_p2;
wire   [5:0] select_ln58_33_fu_1288_p3;
wire   [4:0] select_ln58_47_fu_1401_p3;
wire   [4:0] select_ln58_48_fu_1409_p3;
wire   [4:0] select_ln58_49_fu_1417_p3;
wire   [6:0] select_ln58_39_fu_1337_p3;
wire  signed [6:0] sext_ln58_74_fu_1205_p1;
wire   [6:0] add_ln58_2835_fu_1428_p2;
wire  signed [6:0] sext_ln58_762_fu_1424_p1;
wire   [5:0] select_ln58_52_fu_1456_p3;
wire   [5:0] select_ln58_55_fu_1463_p3;
wire   [5:0] select_ln58_54_fu_1470_p3;
wire   [7:0] select_ln58_40_fu_1344_p3;
wire  signed [7:0] sext_ln58_85_fu_1301_p1;
wire   [7:0] add_ln58_2837_fu_1482_p2;
wire   [7:0] select_ln58_51_fu_1440_p3;
wire   [7:0] add_ln58_2838_fu_1488_p2;
wire  signed [7:0] sext_ln58_763_fu_1478_p1;
wire   [7:0] add_ln58_2839_fu_1494_p2;
wire   [5:0] select_ln58_58_fu_1528_p3;
wire   [5:0] select_ln58_61_fu_1535_p3;
wire   [5:0] select_ln58_60_fu_1542_p3;
wire   [5:0] select_ln58_43_fu_1366_p3;
wire   [5:0] add_ln58_2840_fu_1550_p2;
wire   [5:0] add_ln58_2842_fu_1556_p2;
wire   [6:0] select_ln58_62_fu_1565_p3;
wire  signed [6:0] sext_ln58_109_fu_1561_p1;
wire   [6:0] add_ln58_2843_fu_1620_p2;
wire   [6:0] select_ln58_72_fu_1612_p3;
wire   [4:0] zext_ln58_1925_fu_1632_p1;
wire   [4:0] select_ln58_20_fu_1175_p3;
wire   [4:0] add_ln58_2846_fu_1635_p2;
wire  signed [5:0] sext_ln58_123_fu_1641_p1;
wire   [5:0] add_ln58_2847_fu_1645_p2;
wire   [5:0] select_ln58_38_fu_1324_p3;
wire   [5:0] add_ln58_2848_fu_1651_p2;
wire   [4:0] select_ln58_70_fu_1661_p3;
wire   [4:0] select_ln58_78_fu_1669_p3;
wire   [4:0] select_ln58_77_fu_1677_p3;
wire   [6:0] select_ln58_44_fu_1373_p3;
wire  signed [6:0] sext_ln58_124_fu_1657_p1;
wire   [6:0] add_ln58_2849_fu_1688_p2;
wire  signed [6:0] sext_ln58_764_fu_1684_p1;
wire   [6:0] add_ln58_2850_fu_1694_p2;
wire   [7:0] select_ln58_63_fu_1572_p3;
wire  signed [7:0] sext_ln58_125_fu_1700_p1;
wire   [7:0] add_ln58_2851_fu_1704_p2;
wire   [7:0] select_ln58_68_fu_1596_p3;
wire   [7:0] add_ln58_2852_fu_1710_p2;
wire   [3:0] select_ln58_81_fu_1736_p3;
wire   [3:0] select_ln58_84_fu_1743_p3;
wire   [3:0] select_ln58_82_fu_1750_p3;
wire  signed [4:0] sext_ln58_765_fu_1757_p1;
wire   [4:0] select_ln58_13_fu_1120_p3;
wire   [4:0] add_ln58_2853_fu_1761_p2;
wire   [5:0] select_ln58_83_fu_1771_p3;
wire   [5:0] select_ln58_87_fu_1778_p3;
wire   [5:0] select_ln58_85_fu_1785_p3;
wire   [5:0] select_ln58_8_fu_1061_p3;
wire   [5:0] zext_ln17_938_fu_750_p1;
wire   [5:0] add_ln58_2854_fu_1796_p2;
wire  signed [6:0] sext_ln58_768_fu_1802_p1;
wire  signed [6:0] sext_ln58_767_fu_1792_p1;
wire   [6:0] add_ln58_2855_fu_1806_p2;
wire  signed [6:0] sext_ln58_766_fu_1767_p1;
wire   [4:0] select_ln58_86_fu_1818_p3;
wire   [4:0] select_ln58_89_fu_1825_p3;
wire   [4:0] select_ln58_88_fu_1832_p3;
wire  signed [5:0] sext_ln58_769_fu_1840_p1;
wire   [5:0] select_ln58_53_fu_1448_p3;
wire   [5:0] add_ln58_2857_fu_1844_p2;
wire   [6:0] add_ln58_2856_fu_1812_p2;
wire   [6:0] zext_ln17_953_fu_867_p1;
wire   [3:0] tmp6_fu_1860_p4;
wire   [6:0] zext_ln58_1926_fu_1870_p1;
wire   [6:0] add_ln58_2858_fu_1854_p2;
wire   [6:0] add_ln58_2859_fu_1874_p2;
wire  signed [7:0] sext_ln58_771_fu_1880_p1;
wire  signed [7:0] sext_ln58_770_fu_1850_p1;
wire   [7:0] add_ln58_2860_fu_1884_p2;
wire   [4:0] tmp49_i_fu_1894_p3;
wire   [5:0] select_ln58_65_fu_1905_p3;
wire   [5:0] select_ln58_91_fu_1912_p3;
wire   [5:0] select_ln58_90_fu_1926_p3;
wire   [5:0] select_ln58_94_fu_1933_p3;
wire   [5:0] select_ln58_92_fu_1940_p3;
wire   [5:0] select_ln58_67_fu_1919_p3;
wire   [5:0] zext_ln58_1927_fu_1901_p1;
wire   [5:0] add_ln58_2861_fu_1951_p2;
wire  signed [6:0] sext_ln58_773_fu_1957_p1;
wire  signed [6:0] sext_ln58_772_fu_1947_p1;
wire   [6:0] add_ln58_2862_fu_1961_p2;
wire   [5:0] select_ln58_93_fu_1971_p3;
wire   [5:0] select_ln58_99_fu_1979_p3;
wire   [5:0] select_ln58_95_fu_1987_p3;
wire   [5:0] select_ln58_96_fu_1998_p3;
wire   [5:0] select_ln58_69_fu_1604_p3;
wire   [5:0] select_ln58_97_fu_2006_p3;
wire  signed [6:0] sext_ln58_775_fu_2014_p1;
wire  signed [6:0] sext_ln58_774_fu_1994_p1;
wire   [6:0] add_ln58_2863_fu_2018_p2;
wire   [7:0] select_ln58_56_fu_1504_p3;
wire  signed [7:0] sext_ln58_131_fu_1967_p1;
wire   [3:0] zext_ln17_964_fu_990_p1;
wire   [3:0] zext_ln17_965_fu_1006_p1;
wire   [3:0] add_ln58_2865_fu_2034_p2;
wire   [4:0] zext_ln58_1928_fu_2040_p1;
wire   [4:0] zext_ln17_951_fu_827_p1;
wire   [4:0] add_ln58_2866_fu_2044_p2;
wire   [7:0] zext_ln58_1929_fu_2050_p1;
wire   [7:0] add_ln58_2864_fu_2028_p2;
wire   [7:0] add_ln58_2867_fu_2054_p2;
wire  signed [7:0] sext_ln58_776_fu_2024_p1;
wire   [7:0] add_ln58_2868_fu_2060_p2;
wire   [6:0] select_ln58_45_fu_1380_p3;
wire  signed [6:0] sext_ln58_86_fu_1320_p1;
wire   [3:0] tmp8_fu_2076_p5;
wire   [6:0] zext_ln58_1930_fu_2087_p1;
wire   [6:0] add_ln58_2869_fu_2070_p2;
wire   [5:0] select_ln58_98_fu_2097_p3;
wire   [5:0] select_ln58_101_fu_2105_p3;
wire   [5:0] select_ln58_100_fu_2113_p3;
wire   [6:0] add_ln58_2870_fu_2091_p2;
wire   [6:0] zext_ln17_958_fu_906_p1;
wire   [6:0] add_ln58_2871_fu_2125_p2;
wire  signed [7:0] sext_ln58_778_fu_2131_p1;
wire   [7:0] select_ln58_66_fu_1588_p3;
wire   [7:0] add_ln58_2872_fu_2135_p2;
wire  signed [7:0] sext_ln58_777_fu_2121_p1;
wire   [7:0] add_ln58_2873_fu_2141_p2;
wire   [6:0] select_ln58_102_fu_2159_p3;
wire   [6:0] select_ln58_106_fu_2166_p3;
wire   [6:0] select_ln58_104_fu_2173_p3;
wire   [7:0] select_ln58_14_fu_1127_p3;
wire  signed [7:0] sext_ln58_64_fu_1116_p1;
wire   [7:0] add_ln58_2874_fu_2184_p2;
wire  signed [7:0] sext_ln58_779_fu_2180_p1;
wire   [3:0] zext_ln17_941_fu_765_p1;
wire   [3:0] add_ln58_2876_fu_2196_p2;
wire   [3:0] zext_ln58_1932_fu_2205_p1;
wire   [3:0] zext_ln17_952_fu_843_p1;
wire   [3:0] add_ln58_2878_fu_2208_p2;
wire   [4:0] zext_ln58_1933_fu_2214_p1;
wire   [4:0] zext_ln58_1931_fu_2201_p1;
wire   [4:0] add_ln58_2879_fu_2218_p2;
wire   [7:0] zext_ln58_1934_fu_2224_p1;
wire   [7:0] add_ln58_2875_fu_2190_p2;
wire   [5:0] select_ln58_105_fu_2234_p3;
wire   [5:0] select_ln58_109_fu_2242_p3;
wire   [5:0] select_ln58_107_fu_2250_p3;
wire   [7:0] add_ln58_2880_fu_2228_p2;
wire   [7:0] zext_ln17_966_fu_1010_p1;
wire   [7:0] add_ln58_2881_fu_2262_p2;
wire  signed [8:0] sext_ln58_781_fu_2268_p1;
wire  signed [8:0] sext_ln58_780_fu_2258_p1;
wire   [6:0] add_ln58_2844_fu_1626_p2;
wire   [6:0] zext_ln17_967_fu_1014_p1;
wire   [6:0] add_ln58_2883_fu_2278_p2;
wire  signed [7:0] sext_ln58_782_fu_2284_p1;
wire   [7:0] select_ln58_80_fu_1728_p3;
wire   [7:0] add_ln58_2884_fu_2288_p2;
wire   [5:0] select_ln58_108_fu_2298_p3;
wire   [5:0] select_ln58_117_fu_2305_p3;
wire   [5:0] select_ln58_110_fu_2312_p3;
wire  signed [6:0] sext_ln58_783_fu_2320_p1;
wire   [6:0] select_ln58_50_fu_1394_p3;
wire   [6:0] add_ln58_2885_fu_2324_p2;
wire   [6:0] add_ln58_2829_fu_1251_p2;
wire   [3:0] zext_ln17_959_fu_922_p1;
wire   [3:0] zext_ln17_961_fu_950_p1;
wire   [3:0] add_ln58_2887_fu_2340_p2;
wire   [6:0] zext_ln58_1935_fu_2346_p1;
wire   [6:0] add_ln58_2886_fu_2334_p2;
wire   [6:0] add_ln58_2888_fu_2350_p2;
wire  signed [7:0] sext_ln58_785_fu_2356_p1;
wire  signed [7:0] sext_ln58_784_fu_2330_p1;
wire   [7:0] add_ln58_2889_fu_2360_p2;
wire   [5:0] select_ln58_111_fu_2370_p3;
wire   [5:0] select_ln58_112_fu_2377_p3;
wire  signed [6:0] sext_ln58_786_fu_2385_p1;
wire   [4:0] zext_ln17_960_fu_934_p1;
wire   [4:0] add_ln58_2891_fu_2395_p2;
wire   [5:0] zext_ln58_1936_fu_2401_p1;
wire   [5:0] add_ln58_2834_fu_1331_p2;
wire   [5:0] add_ln58_2892_fu_2405_p2;
wire  signed [6:0] sext_ln58_787_fu_2411_p1;
wire   [6:0] add_ln58_2890_fu_2389_p2;
wire   [6:0] add_ln58_2893_fu_2415_p2;
wire   [6:0] zext_ln17_962_fu_954_p1;
wire   [6:0] add_ln58_2894_fu_2421_p2;
wire  signed [7:0] sext_ln58_788_fu_2427_p1;
wire   [7:0] select_ln58_103_fu_2151_p3;
wire   [7:0] add_ln58_2895_fu_2431_p2;
wire   [2:0] shl_ln73_1_fu_718_p3;
wire   [3:0] shl_ln73_662_cast_i_fu_2441_p1;
wire   [3:0] tmp5020_i_fu_2445_p2;
wire   [4:0] tmp51_i_fu_2451_p3;
wire   [5:0] select_ln58_10_fu_1093_p3;
wire   [5:0] zext_ln17_935_fu_732_p1;
wire   [5:0] add_ln58_2896_fu_2463_p2;
wire   [6:0] select_ln58_24_fu_1209_p3;
wire  signed [6:0] sext_ln58_140_fu_2469_p1;
wire   [5:0] select_ln58_113_fu_2479_p3;
wire   [5:0] select_ln58_114_fu_2490_p3;
wire   [5:0] select_ln58_115_fu_2497_p3;
wire   [5:0] select_ln58_116_fu_2504_p3;
wire  signed [6:0] sext_ln58_790_fu_2512_p1;
wire   [6:0] select_ln58_46_fu_1387_p3;
wire   [6:0] add_ln58_2898_fu_2516_p2;
wire  signed [6:0] sext_ln58_789_fu_2486_p1;
wire   [6:0] add_ln58_2899_fu_2522_p2;
wire   [6:0] add_ln58_2897_fu_2473_p2;
wire   [6:0] zext_ln58_1937_fu_2459_p1;
wire   [3:0] zext_ln17_955_fu_882_p1;
wire   [3:0] zext_ln17_957_fu_902_p1;
wire   [3:0] add_ln58_2901_fu_2538_p2;
wire   [4:0] zext_ln58_1938_fu_2544_p1;
wire   [4:0] zext_ln17_963_fu_966_p1;
wire   [4:0] add_ln58_2902_fu_2548_p2;
wire   [6:0] zext_ln58_1939_fu_2554_p1;
wire   [6:0] add_ln58_2900_fu_2532_p2;
wire   [6:0] add_ln58_2903_fu_2558_p2;
wire  signed [7:0] sext_ln58_792_fu_2564_p1;
wire  signed [7:0] sext_ln58_791_fu_2528_p1;
wire   [7:0] add_ln58_2904_fu_2568_p2;
wire   [8:0] select_ln58_57_fu_1512_p3;
wire  signed [8:0] sext_ln58_101_fu_1500_p1;
wire   [3:0] add_ln58_2906_fu_2584_p2;
wire   [4:0] zext_ln58_1940_fu_2590_p1;
wire   [4:0] add_ln58_2907_fu_2594_p2;
wire   [8:0] zext_ln58_1941_fu_2600_p1;
wire   [8:0] add_ln58_2905_fu_2578_p2;
wire   [1:0] shl_ln_fu_704_p3;
wire   [1:0] shl_ln73_s_fu_711_p3;
wire   [2:0] shl_ln73_661_cast_i_fu_2622_p1;
wire   [2:0] shl_ln73_cast_i_fu_2618_p1;
wire   [2:0] empty_36_fu_2630_p2;
wire   [1:0] shl_ln73_4_fu_736_p3;
wire   [1:0] shl_ln73_6_fu_851_p3;
wire   [3:0] p_cast65_i_fu_2636_p1;
wire   [3:0] shl_ln73_666_cast_i_fu_2626_p1;
wire   [2:0] shl_ln73_257_cast_fu_2640_p1;
wire   [2:0] shl_ln73_273_cast_fu_2644_p1;
wire   [2:0] tmp77_fu_2654_p2;
wire   [3:0] tmp77_cast_fu_2660_p1;
wire   [3:0] tmp76_fu_2648_p2;
wire   [3:0] tmp5518_i_fu_2664_p2;
wire   [5:0] select_ln58_71_fu_2678_p3;
wire   [5:0] select_ln58_119_fu_2685_p3;
wire   [5:0] select_ln58_73_fu_2692_p3;
wire   [5:0] select_ln58_29_fu_1260_p3;
wire   [5:0] add_ln58_2909_fu_2699_p2;
wire   [6:0] select_ln58_41_fu_1351_p3;
wire  signed [6:0] sext_ln58_143_fu_2705_p1;
wire   [6:0] add_ln58_2910_fu_2709_p2;
wire   [6:0] select_ln58_42_fu_1359_p3;
wire   [5:0] select_ln58_118_fu_2721_p3;
wire   [5:0] select_ln58_122_fu_2729_p3;
wire   [5:0] select_ln58_120_fu_2737_p3;
wire   [5:0] select_ln58_79_fu_1720_p3;
wire   [5:0] add_ln58_2912_fu_2745_p2;
wire   [4:0] tmp56_i_fu_2670_p3;
wire   [4:0] zext_ln17_954_fu_878_p1;
wire   [4:0] add_ln58_2913_fu_2755_p2;
wire   [6:0] zext_ln58_1942_fu_2761_p1;
wire   [6:0] add_ln58_2911_fu_2715_p2;
wire   [6:0] add_ln58_2914_fu_2765_p2;
wire  signed [7:0] sext_ln58_794_fu_2771_p1;
wire  signed [7:0] sext_ln58_793_fu_2751_p1;
wire   [7:0] add_ln58_2915_fu_2775_p2;
wire   [5:0] select_ln58_124_fu_2788_p3;
wire   [5:0] select_ln58_128_fu_2796_p3;
wire   [5:0] select_ln58_126_fu_2804_p3;
wire  signed [6:0] sext_ln58_147_fu_2785_p1;
wire   [6:0] zext_ln17_948_fu_807_p1;
wire   [6:0] add_ln58_2921_fu_2816_p2;
wire  signed [6:0] sext_ln58_795_fu_2812_p1;
wire   [6:0] add_ln58_2922_fu_2822_p2;
wire   [4:0] select_ln58_127_fu_2832_p3;
wire   [4:0] select_ln58_131_fu_2840_p3;
wire   [4:0] select_ln58_129_fu_2848_p3;
wire  signed [5:0] sext_ln58_796_fu_2856_p1;
wire   [5:0] add_ln58_2923_fu_2860_p2;
wire  signed [7:0] sext_ln58_148_fu_2828_p1;
wire   [7:0] add_ln58_2924_fu_2870_p2;
wire   [7:0] select_ln58_63_cast_i_cast146_cast_fu_2610_p3;
wire   [7:0] add_ln58_2925_fu_2876_p2;
wire  signed [7:0] sext_ln58_797_fu_2866_p1;
wire   [7:0] add_ln58_2926_fu_2882_p2;
wire   [1:0] shl_ln73_8_fu_1022_p3;
wire   [2:0] shl_ln73_696_cast_i_fu_2892_p1;
wire   [2:0] sext_ln42_cast_i_fu_970_p3;
wire   [2:0] tmp5716_i_fu_2896_p2;
wire   [3:0] tmp_5_fu_2902_p3;
wire   [5:0] select_ln58_22_fu_1192_p3;
wire  signed [5:0] sext_ln58_66_fu_1164_p1;
wire   [5:0] select_ln58_130_fu_2920_p3;
wire   [5:0] select_ln58_135_fu_2928_p3;
wire   [5:0] select_ln58_132_fu_2936_p3;
wire   [5:0] select_ln58_59_fu_1520_p3;
wire   [5:0] add_ln58_2928_fu_2943_p2;
wire   [5:0] add_ln58_2927_fu_2914_p2;
wire   [5:0] zext_ln17_949_fu_811_p1;
wire   [3:0] add_ln58_2930_fu_2959_p2;
wire   [5:0] zext_ln58_1946_fu_2964_p1;
wire   [5:0] add_ln58_2929_fu_2953_p2;
wire   [5:0] add_ln58_2931_fu_2968_p2;
wire  signed [6:0] sext_ln58_800_fu_2974_p1;
wire  signed [6:0] sext_ln58_799_fu_2949_p1;
wire  signed [6:0] sext_ln58_798_fu_2910_p1;
wire   [6:0] add_ln58_2932_fu_2978_p2;
wire   [6:0] add_ln58_2933_fu_2984_p2;
wire   [5:0] select_ln58_133_fu_2994_p3;
wire   [3:0] tmp10_fu_3005_p4;
wire   [6:0] zext_ln58_1947_fu_3015_p1;
wire   [6:0] add_ln58_2836_fu_1434_p2;
wire   [6:0] add_ln58_2934_fu_3019_p2;
wire  signed [7:0] sext_ln58_802_fu_3025_p1;
wire  signed [7:0] sext_ln58_801_fu_3001_p1;
wire   [7:0] add_ln58_2935_fu_3029_p2;
wire   [3:0] tmp60_i_fu_3039_p4;
wire   [4:0] select_ln58_74_fu_3051_p3;
wire   [4:0] select_ln58_75_fu_3058_p3;
wire   [4:0] select_ln58_76_fu_3065_p3;
wire   [3:0] select_ln58_134_fu_3076_p3;
wire   [3:0] select_ln58_138_fu_3084_p3;
wire   [3:0] select_ln58_136_fu_3092_p3;
wire   [5:0] select_ln58_18_fu_1168_p3;
wire  signed [5:0] sext_ln58_151_fu_3072_p1;
wire   [5:0] add_ln58_2936_fu_3103_p2;
wire  signed [5:0] sext_ln58_803_fu_3099_p1;
wire   [4:0] zext_ln17_945_fu_780_p1;
wire   [4:0] zext_ln17_946_fu_796_p1;
wire   [4:0] add_ln58_2938_fu_3115_p2;
wire   [4:0] zext_ln58_1950_fu_3125_p1;
wire   [4:0] add_ln58_2940_fu_3128_p2;
wire   [5:0] zext_ln58_1951_fu_3134_p1;
wire   [5:0] zext_ln58_1949_fu_3121_p1;
wire   [5:0] add_ln58_2941_fu_3138_p2;
wire   [5:0] add_ln58_2937_fu_3109_p2;
wire   [5:0] add_ln58_2942_fu_3144_p2;
wire   [4:0] select_ln58_137_fu_3154_p3;
wire   [4:0] select_ln58_140_fu_3162_p3;
wire   [4:0] select_ln58_139_fu_3170_p3;
wire  signed [5:0] sext_ln58_804_fu_3178_p1;
wire   [5:0] select_ln58_64_fu_1580_p3;
wire   [5:0] add_ln58_2943_fu_3182_p2;
wire   [4:0] zext_ln58_1948_fu_3047_p1;
wire   [4:0] zext_ln17_956_fu_898_p1;
wire   [4:0] add_ln58_2944_fu_3192_p2;
wire   [6:0] zext_ln58_1952_fu_3198_p1;
wire  signed [6:0] sext_ln58_152_fu_3150_p1;
wire   [6:0] add_ln58_2945_fu_3202_p2;
wire  signed [6:0] sext_ln58_805_fu_3188_p1;
wire   [6:0] add_ln58_2946_fu_3208_p2;
wire  signed [8:0] sext_ln58_145_fu_2781_p1;
wire  signed [8:0] sext_ln58_132_fu_2066_p1;
wire  signed [8:0] sext_ln58_134_fu_2147_p1;
wire  signed [8:0] add_ln58_3020_cast_i_fu_2888_p1;
wire   [8:0] add_ln58_2882_fu_2272_p2;
wire  signed [8:0] sext_ln58_136_fu_2294_p1;
wire  signed [8:0] sext_ln58_137_fu_2366_p1;
wire  signed [8:0] sext_ln58_139_fu_2437_p1;
wire  signed [8:0] sext_ln58_142_fu_2574_p1;
wire  signed [8:0] sext_ln58_806_fu_2990_p1;
wire   [8:0] add_ln58_2908_fu_2604_p2;
wire  signed [8:0] sext_ln58_126_fu_1716_p1;
wire  signed [8:0] add_ln58_3029_cast_i_fu_3035_p1;
wire  signed [8:0] add_ln58_3042_cast_i_fu_3214_p1;
wire  signed [8:0] add_ln58_2953_cast_i_fu_1890_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        a_10_reg_3392 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_7;
        a_11_reg_3400 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_6;
        a_12_reg_3414 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_5;
        a_13_reg_3421 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_4;
        a_15_reg_3433 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_2;
        a_16_reg_3449 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_1;
        a_1_reg_3314 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
        a_20_reg_3466 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_22;
        a_2_reg_3322 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_18;
        a_3_reg_3330 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_14;
        a_4_reg_3340 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_13;
        a_5_reg_3349 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_12;
        a_6_reg_3356 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_11;
        a_7_reg_3366 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_10;
        a_8_reg_3373 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_9;
        a_9_reg_3380 <= p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_8;
        a_reg_3308 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
        add_ln58_2823_reg_3482[4 : 3] <= add_ln58_2823_fu_422_p2[4 : 3];
        add_ln58_2826_reg_3487[4 : 2] <= add_ln58_2826_fu_474_p2[4 : 2];
        add_ln58_2830_reg_3492[5 : 2] <= add_ln58_2830_fu_510_p2[5 : 2];
        add_ln58_2841_reg_3502[5 : 2] <= add_ln58_2841_fu_562_p2[5 : 2];
        add_ln58_2845_reg_3507[3 : 1] <= add_ln58_2845_fu_568_p2[3 : 1];
        add_ln58_2877_reg_3517[2 : 1] <= add_ln58_2877_fu_612_p2[2 : 1];
        add_ln58_2920_reg_3522[5 : 2] <= add_ln58_2920_fu_692_p2[5 : 2];
        add_ln58_2939_reg_3527[3 : 2] <= add_ln58_2939_fu_698_p2[3 : 2];
        select_ln58_2_reg_3477[4 : 3] <= select_ln58_2_fu_384_p3[4 : 3];
        select_ln58_36_reg_3497[3 : 2] <= select_ln58_36_fu_540_p3[3 : 2];
        tmp4822_i_reg_3512[3 : 1] <= tmp4822_i_fu_606_p2[3 : 1];
        zext_ln17_942_reg_3409[2] <= zext_ln17_942_fu_304_p1[2];
        zext_ln17_947_reg_3444[2] <= zext_ln17_947_fu_340_p1[2];
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (1'b0 == ap_ce))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_2822_fu_416_p2 = (select_ln58_11_fu_408_p3 + zext_ln17_930_fu_200_p1);

assign add_ln58_2823_fu_422_p2 = (select_ln58_5_fu_400_p3 + zext_ln17_933_fu_232_p1);

assign add_ln58_2824_fu_1110_p2 = ($signed(select_ln58_12_fu_1103_p3) + $signed(sext_ln58_61_fu_1076_p1));

assign add_ln58_2825_fu_442_p2 = (zext_ln58_fu_438_p1 + select_ln58_fu_376_p3);

assign add_ln58_2826_fu_474_p2 = ($signed(select_ln58_19_fu_466_p3) + $signed(sext_ln58_68_fu_462_p1));

assign add_ln58_2827_fu_1199_p2 = ($signed(select_ln58_21_fu_1185_p3) + $signed(sext_ln58_71_fu_1182_p1));

assign add_ln58_2828_fu_1241_p2 = (add_ln58_fu_1087_p2 + zext_ln17_940_fu_761_p1);

assign add_ln58_2829_fu_1251_p2 = ($signed(sext_ln58_760_fu_1247_p1) + $signed(sext_ln58_759_fu_1237_p1));

assign add_ln58_2830_fu_510_p2 = ($signed(select_ln58_28_fu_502_p3) + $signed(sext_ln58_79_fu_498_p1));

assign add_ln58_2831_fu_1295_p2 = ($signed(select_ln58_30_fu_1267_p3) + $signed(sext_ln58_84_fu_1257_p1));

assign add_ln58_2832_fu_1308_p2 = ($signed(sext_ln58_63_fu_1100_p1) + $signed(zext_ln17_944_fu_776_p1));

assign add_ln58_2833_fu_1314_p2 = ($signed(add_ln58_2832_fu_1308_p2) + $signed(sext_ln58_761_fu_1305_p1));

assign add_ln58_2834_fu_1331_p2 = (select_ln58_33_fu_1288_p3 + zext_ln17_944_fu_776_p1);

assign add_ln58_2835_fu_1428_p2 = ($signed(select_ln58_39_fu_1337_p3) + $signed(sext_ln58_74_fu_1205_p1));

assign add_ln58_2836_fu_1434_p2 = ($signed(add_ln58_2835_fu_1428_p2) + $signed(sext_ln58_762_fu_1424_p1));

assign add_ln58_2837_fu_1482_p2 = ($signed(select_ln58_40_fu_1344_p3) + $signed(sext_ln58_85_fu_1301_p1));

assign add_ln58_2838_fu_1488_p2 = (add_ln58_2837_fu_1482_p2 + select_ln58_51_fu_1440_p3);

assign add_ln58_2839_fu_1494_p2 = ($signed(add_ln58_2838_fu_1488_p2) + $signed(sext_ln58_763_fu_1478_p1));

assign add_ln58_2840_fu_1550_p2 = (select_ln58_60_fu_1542_p3 + select_ln58_43_fu_1366_p3);

assign add_ln58_2841_fu_562_p2 = ($signed(zext_ln58_1924_fu_558_p1) + $signed(sext_ln58_65_fu_448_p1));

assign add_ln58_2842_fu_1556_p2 = (add_ln58_2841_reg_3502 + add_ln58_2840_fu_1550_p2);

assign add_ln58_2843_fu_1620_p2 = ($signed(select_ln58_62_fu_1565_p3) + $signed(sext_ln58_109_fu_1561_p1));

assign add_ln58_2844_fu_1626_p2 = (add_ln58_2843_fu_1620_p2 + select_ln58_72_fu_1612_p3);

assign add_ln58_2845_fu_568_p2 = (add_ln58_2822_fu_416_p2 + zext_ln17_fu_248_p1);

assign add_ln58_2846_fu_1635_p2 = (zext_ln58_1925_fu_1632_p1 + select_ln58_20_fu_1175_p3);

assign add_ln58_2847_fu_1645_p2 = ($signed(sext_ln58_123_fu_1641_p1) + $signed(zext_ln17_940_fu_761_p1));

assign add_ln58_2848_fu_1651_p2 = (add_ln58_2847_fu_1645_p2 + select_ln58_38_fu_1324_p3);

assign add_ln58_2849_fu_1688_p2 = ($signed(select_ln58_44_fu_1373_p3) + $signed(sext_ln58_124_fu_1657_p1));

assign add_ln58_2850_fu_1694_p2 = ($signed(add_ln58_2849_fu_1688_p2) + $signed(sext_ln58_764_fu_1684_p1));

assign add_ln58_2851_fu_1704_p2 = ($signed(select_ln58_63_fu_1572_p3) + $signed(sext_ln58_125_fu_1700_p1));

assign add_ln58_2852_fu_1710_p2 = (add_ln58_2851_fu_1704_p2 + select_ln58_68_fu_1596_p3);

assign add_ln58_2853_fu_1761_p2 = ($signed(sext_ln58_765_fu_1757_p1) + $signed(select_ln58_13_fu_1120_p3));

assign add_ln58_2854_fu_1796_p2 = (select_ln58_8_fu_1061_p3 + zext_ln17_938_fu_750_p1);

assign add_ln58_2855_fu_1806_p2 = ($signed(sext_ln58_768_fu_1802_p1) + $signed(sext_ln58_767_fu_1792_p1));

assign add_ln58_2856_fu_1812_p2 = ($signed(add_ln58_2855_fu_1806_p2) + $signed(sext_ln58_766_fu_1767_p1));

assign add_ln58_2857_fu_1844_p2 = ($signed(sext_ln58_769_fu_1840_p1) + $signed(select_ln58_53_fu_1448_p3));

assign add_ln58_2858_fu_1854_p2 = (add_ln58_2856_fu_1812_p2 + zext_ln17_953_fu_867_p1);

assign add_ln58_2859_fu_1874_p2 = (zext_ln58_1926_fu_1870_p1 + add_ln58_2858_fu_1854_p2);

assign add_ln58_2860_fu_1884_p2 = ($signed(sext_ln58_771_fu_1880_p1) + $signed(sext_ln58_770_fu_1850_p1));

assign add_ln58_2861_fu_1951_p2 = (select_ln58_67_fu_1919_p3 + zext_ln58_1927_fu_1901_p1);

assign add_ln58_2862_fu_1961_p2 = ($signed(sext_ln58_773_fu_1957_p1) + $signed(sext_ln58_772_fu_1947_p1));

assign add_ln58_2863_fu_2018_p2 = ($signed(sext_ln58_775_fu_2014_p1) + $signed(sext_ln58_774_fu_1994_p1));

assign add_ln58_2864_fu_2028_p2 = ($signed(select_ln58_56_fu_1504_p3) + $signed(sext_ln58_131_fu_1967_p1));

assign add_ln58_2865_fu_2034_p2 = (zext_ln17_964_fu_990_p1 + zext_ln17_965_fu_1006_p1);

assign add_ln58_2866_fu_2044_p2 = (zext_ln58_1928_fu_2040_p1 + zext_ln17_951_fu_827_p1);

assign add_ln58_2867_fu_2054_p2 = (zext_ln58_1929_fu_2050_p1 + add_ln58_2864_fu_2028_p2);

assign add_ln58_2868_fu_2060_p2 = ($signed(add_ln58_2867_fu_2054_p2) + $signed(sext_ln58_776_fu_2024_p1));

assign add_ln58_2869_fu_2070_p2 = ($signed(select_ln58_45_fu_1380_p3) + $signed(sext_ln58_86_fu_1320_p1));

assign add_ln58_2870_fu_2091_p2 = (zext_ln58_1930_fu_2087_p1 + add_ln58_2869_fu_2070_p2);

assign add_ln58_2871_fu_2125_p2 = (add_ln58_2870_fu_2091_p2 + zext_ln17_958_fu_906_p1);

assign add_ln58_2872_fu_2135_p2 = ($signed(sext_ln58_778_fu_2131_p1) + $signed(select_ln58_66_fu_1588_p3));

assign add_ln58_2873_fu_2141_p2 = ($signed(add_ln58_2872_fu_2135_p2) + $signed(sext_ln58_777_fu_2121_p1));

assign add_ln58_2874_fu_2184_p2 = ($signed(select_ln58_14_fu_1127_p3) + $signed(sext_ln58_64_fu_1116_p1));

assign add_ln58_2875_fu_2190_p2 = ($signed(add_ln58_2874_fu_2184_p2) + $signed(sext_ln58_779_fu_2180_p1));

assign add_ln58_2876_fu_2196_p2 = (zext_ln17_941_fu_765_p1 + zext_ln17_942_reg_3409);

assign add_ln58_2877_fu_612_p2 = (zext_ln17_950_fu_356_p1 + zext_ln42_fu_372_p1);

assign add_ln58_2878_fu_2208_p2 = (zext_ln58_1932_fu_2205_p1 + zext_ln17_952_fu_843_p1);

assign add_ln58_2879_fu_2218_p2 = (zext_ln58_1933_fu_2214_p1 + zext_ln58_1931_fu_2201_p1);

assign add_ln58_2880_fu_2228_p2 = (zext_ln58_1934_fu_2224_p1 + add_ln58_2875_fu_2190_p2);

assign add_ln58_2881_fu_2262_p2 = (add_ln58_2880_fu_2228_p2 + zext_ln17_966_fu_1010_p1);

assign add_ln58_2882_fu_2272_p2 = ($signed(sext_ln58_781_fu_2268_p1) + $signed(sext_ln58_780_fu_2258_p1));

assign add_ln58_2883_fu_2278_p2 = (add_ln58_2844_fu_1626_p2 + zext_ln17_967_fu_1014_p1);

assign add_ln58_2884_fu_2288_p2 = ($signed(sext_ln58_782_fu_2284_p1) + $signed(select_ln58_80_fu_1728_p3));

assign add_ln58_2885_fu_2324_p2 = ($signed(sext_ln58_783_fu_2320_p1) + $signed(select_ln58_50_fu_1394_p3));

assign add_ln58_2886_fu_2334_p2 = (add_ln58_2829_fu_1251_p2 + zext_ln17_953_fu_867_p1);

assign add_ln58_2887_fu_2340_p2 = (zext_ln17_959_fu_922_p1 + zext_ln17_961_fu_950_p1);

assign add_ln58_2888_fu_2350_p2 = (zext_ln58_1935_fu_2346_p1 + add_ln58_2886_fu_2334_p2);

assign add_ln58_2889_fu_2360_p2 = ($signed(sext_ln58_785_fu_2356_p1) + $signed(sext_ln58_784_fu_2330_p1));

assign add_ln58_2890_fu_2389_p2 = ($signed(sext_ln58_786_fu_2385_p1) + $signed(select_ln58_62_fu_1565_p3));

assign add_ln58_2891_fu_2395_p2 = (zext_ln17_951_fu_827_p1 + zext_ln17_960_fu_934_p1);

assign add_ln58_2892_fu_2405_p2 = (zext_ln58_1936_fu_2401_p1 + add_ln58_2834_fu_1331_p2);

assign add_ln58_2893_fu_2415_p2 = ($signed(sext_ln58_787_fu_2411_p1) + $signed(add_ln58_2890_fu_2389_p2));

assign add_ln58_2894_fu_2421_p2 = (add_ln58_2893_fu_2415_p2 + zext_ln17_962_fu_954_p1);

assign add_ln58_2895_fu_2431_p2 = ($signed(sext_ln58_788_fu_2427_p1) + $signed(select_ln58_103_fu_2151_p3));

assign add_ln58_2896_fu_2463_p2 = (select_ln58_10_fu_1093_p3 + zext_ln17_935_fu_732_p1);

assign add_ln58_2897_fu_2473_p2 = ($signed(select_ln58_24_fu_1209_p3) + $signed(sext_ln58_140_fu_2469_p1));

assign add_ln58_2898_fu_2516_p2 = ($signed(sext_ln58_790_fu_2512_p1) + $signed(select_ln58_46_fu_1387_p3));

assign add_ln58_2899_fu_2522_p2 = ($signed(add_ln58_2898_fu_2516_p2) + $signed(sext_ln58_789_fu_2486_p1));

assign add_ln58_2900_fu_2532_p2 = (add_ln58_2897_fu_2473_p2 + zext_ln58_1937_fu_2459_p1);

assign add_ln58_2901_fu_2538_p2 = (zext_ln17_955_fu_882_p1 + zext_ln17_957_fu_902_p1);

assign add_ln58_2902_fu_2548_p2 = (zext_ln58_1938_fu_2544_p1 + zext_ln17_963_fu_966_p1);

assign add_ln58_2903_fu_2558_p2 = (zext_ln58_1939_fu_2554_p1 + add_ln58_2900_fu_2532_p2);

assign add_ln58_2904_fu_2568_p2 = ($signed(sext_ln58_792_fu_2564_p1) + $signed(sext_ln58_791_fu_2528_p1));

assign add_ln58_2905_fu_2578_p2 = ($signed(select_ln58_57_fu_1512_p3) + $signed(sext_ln58_101_fu_1500_p1));

assign add_ln58_2906_fu_2584_p2 = (zext_ln17_961_fu_950_p1 + zext_ln17_965_fu_1006_p1);

assign add_ln58_2907_fu_2594_p2 = (zext_ln58_1940_fu_2590_p1 + zext_ln17_960_fu_934_p1);

assign add_ln58_2908_fu_2604_p2 = (zext_ln58_1941_fu_2600_p1 + add_ln58_2905_fu_2578_p2);

assign add_ln58_2909_fu_2699_p2 = (select_ln58_73_fu_2692_p3 + select_ln58_29_fu_1260_p3);

assign add_ln58_2910_fu_2709_p2 = ($signed(select_ln58_41_fu_1351_p3) + $signed(sext_ln58_143_fu_2705_p1));

assign add_ln58_2911_fu_2715_p2 = (add_ln58_2910_fu_2709_p2 + select_ln58_42_fu_1359_p3);

assign add_ln58_2912_fu_2745_p2 = (select_ln58_120_fu_2737_p3 + select_ln58_79_fu_1720_p3);

assign add_ln58_2913_fu_2755_p2 = (tmp56_i_fu_2670_p3 + zext_ln17_954_fu_878_p1);

assign add_ln58_2914_fu_2765_p2 = (zext_ln58_1942_fu_2761_p1 + add_ln58_2911_fu_2715_p2);

assign add_ln58_2915_fu_2775_p2 = ($signed(sext_ln58_794_fu_2771_p1) + $signed(sext_ln58_793_fu_2751_p1));

assign add_ln58_2916_fu_656_p2 = (zext_ln58_1943_fu_652_p1 + select_ln58_123_fu_634_p3);

assign add_ln58_2917_fu_666_p2 = ($signed(select_ln58_32_fu_516_p3) + $signed(sext_ln58_146_fu_662_p1));

assign add_ln58_2918_fu_672_p2 = (zext_ln17_943_fu_320_p1 + zext_ln17_947_fu_340_p1);

assign add_ln58_2919_fu_682_p2 = (zext_ln58_1944_fu_678_p1 + zext_ln17_939_fu_280_p1);

assign add_ln58_2920_fu_692_p2 = (zext_ln58_1945_fu_688_p1 + add_ln58_2917_fu_666_p2);

assign add_ln58_2921_fu_2816_p2 = ($signed(sext_ln58_147_fu_2785_p1) + $signed(zext_ln17_948_fu_807_p1));

assign add_ln58_2922_fu_2822_p2 = ($signed(add_ln58_2921_fu_2816_p2) + $signed(sext_ln58_795_fu_2812_p1));

assign add_ln58_2923_fu_2860_p2 = ($signed(sext_ln58_796_fu_2856_p1) + $signed(select_ln58_69_fu_1604_p3));

assign add_ln58_2924_fu_2870_p2 = ($signed(select_ln58_66_fu_1588_p3) + $signed(sext_ln58_148_fu_2828_p1));

assign add_ln58_2925_fu_2876_p2 = (add_ln58_2924_fu_2870_p2 + select_ln58_63_cast_i_cast146_cast_fu_2610_p3);

assign add_ln58_2926_fu_2882_p2 = ($signed(add_ln58_2925_fu_2876_p2) + $signed(sext_ln58_797_fu_2866_p1));

assign add_ln58_2927_fu_2914_p2 = ($signed(select_ln58_22_fu_1192_p3) + $signed(sext_ln58_66_fu_1164_p1));

assign add_ln58_2928_fu_2943_p2 = (select_ln58_132_fu_2936_p3 + select_ln58_59_fu_1520_p3);

assign add_ln58_2929_fu_2953_p2 = (add_ln58_2927_fu_2914_p2 + zext_ln17_949_fu_811_p1);

assign add_ln58_2930_fu_2959_p2 = (zext_ln17_947_reg_3444 + zext_ln17_964_fu_990_p1);

assign add_ln58_2931_fu_2968_p2 = (zext_ln58_1946_fu_2964_p1 + add_ln58_2929_fu_2953_p2);

assign add_ln58_2932_fu_2978_p2 = ($signed(sext_ln58_800_fu_2974_p1) + $signed(sext_ln58_799_fu_2949_p1));

assign add_ln58_2933_fu_2984_p2 = ($signed(sext_ln58_798_fu_2910_p1) + $signed(add_ln58_2932_fu_2978_p2));

assign add_ln58_2934_fu_3019_p2 = (zext_ln58_1947_fu_3015_p1 + add_ln58_2836_fu_1434_p2);

assign add_ln58_2935_fu_3029_p2 = ($signed(sext_ln58_802_fu_3025_p1) + $signed(sext_ln58_801_fu_3001_p1));

assign add_ln58_2936_fu_3103_p2 = ($signed(select_ln58_18_fu_1168_p3) + $signed(sext_ln58_151_fu_3072_p1));

assign add_ln58_2937_fu_3109_p2 = ($signed(add_ln58_2936_fu_3103_p2) + $signed(sext_ln58_803_fu_3099_p1));

assign add_ln58_2938_fu_3115_p2 = (zext_ln17_945_fu_780_p1 + zext_ln17_946_fu_796_p1);

assign add_ln58_2939_fu_698_p2 = (zext_ln17_942_fu_304_p1 + zext_ln17_947_fu_340_p1);

assign add_ln58_2940_fu_3128_p2 = (zext_ln58_1950_fu_3125_p1 + zext_ln17_951_fu_827_p1);

assign add_ln58_2941_fu_3138_p2 = (zext_ln58_1951_fu_3134_p1 + zext_ln58_1949_fu_3121_p1);

assign add_ln58_2942_fu_3144_p2 = (add_ln58_2941_fu_3138_p2 + add_ln58_2937_fu_3109_p2);

assign add_ln58_2943_fu_3182_p2 = ($signed(sext_ln58_804_fu_3178_p1) + $signed(select_ln58_64_fu_1580_p3));

assign add_ln58_2944_fu_3192_p2 = (zext_ln58_1948_fu_3047_p1 + zext_ln17_956_fu_898_p1);

assign add_ln58_2945_fu_3202_p2 = ($signed(zext_ln58_1952_fu_3198_p1) + $signed(sext_ln58_152_fu_3150_p1));

assign add_ln58_2946_fu_3208_p2 = ($signed(add_ln58_2945_fu_3202_p2) + $signed(sext_ln58_805_fu_3188_p1));

assign add_ln58_2953_cast_i_fu_1890_p1 = $signed(add_ln58_2860_fu_1884_p2);

assign add_ln58_3020_cast_i_fu_2888_p1 = $signed(add_ln58_2926_fu_2882_p2);

assign add_ln58_3029_cast_i_fu_3035_p1 = $signed(add_ln58_2935_fu_3029_p2);

assign add_ln58_3042_cast_i_fu_3214_p1 = $signed(add_ln58_2946_fu_3208_p2);

assign add_ln58_fu_1087_p2 = ($signed(select_ln58_9_fu_1080_p3) + $signed(sext_ln58_fu_1043_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return_0 = sext_ln58_145_fu_2781_p1;

assign ap_return_1 = sext_ln58_132_fu_2066_p1;

assign ap_return_10 = add_ln58_2908_fu_2604_p2;

assign ap_return_11 = sext_ln58_126_fu_1716_p1;

assign ap_return_12 = add_ln58_3029_cast_i_fu_3035_p1;

assign ap_return_13 = add_ln58_3042_cast_i_fu_3214_p1;

assign ap_return_14 = add_ln58_2953_cast_i_fu_1890_p1;

assign ap_return_2 = sext_ln58_134_fu_2147_p1;

assign ap_return_3 = add_ln58_3020_cast_i_fu_2888_p1;

assign ap_return_4 = add_ln58_2882_fu_2272_p2;

assign ap_return_5 = sext_ln58_136_fu_2294_p1;

assign ap_return_6 = sext_ln58_137_fu_2366_p1;

assign ap_return_7 = sext_ln58_139_fu_2437_p1;

assign ap_return_8 = sext_ln58_142_fu_2574_p1;

assign ap_return_9 = sext_ln58_806_fu_2990_p1;

assign empty_36_fu_2630_p2 = (shl_ln73_661_cast_i_fu_2622_p1 + shl_ln73_cast_i_fu_2618_p1);

assign empty_fu_582_p2 = (shl_ln73_670_cast_i_fu_578_p1 + shl_ln73_663_cast_i_fu_574_p1);

assign mult_1731_fu_224_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_13}, {3'd0}};

assign mult_1732_fu_240_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_12}, {2'd0}};

assign mult_1733_fu_725_p3 = {{a_6_reg_3356}, {2'd0}};

assign mult_1734_fu_743_p3 = {{a_7_reg_3366}, {3'd0}};

assign mult_1735_fu_272_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_9}, {3'd0}};

assign mult_1736_fu_754_p3 = {{a_9_reg_3380}, {2'd0}};

assign mult_1737_fu_296_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_6}, {2'd0}};

assign mult_1738_fu_312_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_5}, {2'd0}};

assign mult_1739_fu_769_p3 = {{a_13_reg_3421}, {3'd0}};

assign mult_1740_fu_788_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_3}, {3'd0}};

assign mult_1741_fu_332_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_2}, {2'd0}};

assign mult_1742_fu_800_p3 = {{a_16_reg_3449}, {3'd0}};

assign mult_1743_fu_348_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_1}, {1'd0}};

assign mult_1744_fu_819_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9}, {3'd0}};

assign mult_1745_fu_835_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24}, {2'd0}};

assign mult_1746_fu_859_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23}, {3'd0}};

assign mult_1747_fu_364_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_22}, {1'd0}};

assign mult_1748_fu_890_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_21}, {2'd0}};

assign mult_1749_fu_914_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20}, {2'd0}};

assign mult_1750_fu_926_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20}, {3'd0}};

assign mult_1751_fu_942_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19}, {2'd0}};

assign mult_1752_fu_958_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19}, {3'd0}};

assign mult_1753_fu_982_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17}, {2'd0}};

assign mult_1754_fu_998_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_16}, {2'd0}};

assign mult_1_fu_871_p3 = {{a_20_reg_3466}, {2'd0}};

assign mult_fu_192_p3 = {{void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig}, {1'd0}};

assign or_ln58_3_fu_1155_p4 = {{{select_ln58_16_fu_1148_p3}, {a_6_reg_3356}}, {1'd0}};

assign or_ln58_4_fu_452_p4 = {{{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_11}, {p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_18}}, {2'd0}};

assign or_ln58_5_fu_488_p4 = {{{select_ln58_26_fu_480_p3}, {p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_11}}, {2'd0}};

assign or_ln_fu_1068_p4 = {{{a_3_reg_3330}, {a_2_reg_3322}}, {1'd0}};

assign p_cast65_i_fu_2636_p1 = empty_36_fu_2630_p2;

assign p_cast_i_fu_588_p1 = empty_fu_582_p2;

assign select_ln58_100_fu_2113_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_16[0:0] == 1'b1) ? select_ln58_98_fu_2097_p3 : select_ln58_101_fu_2105_p3);

assign select_ln58_101_fu_2105_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_102_fu_2159_p3 = ((a_13_reg_3421[0:0] == 1'b1) ? 7'd80 : 7'd96);

assign select_ln58_103_fu_2151_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_16[0:0] == 1'b1) ? 8'd248 : 8'd0);

assign select_ln58_104_fu_2173_p3 = ((a_15_reg_3433[0:0] == 1'b1) ? select_ln58_102_fu_2159_p3 : select_ln58_106_fu_2166_p3);

assign select_ln58_105_fu_2234_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20[0:0] == 1'b1) ? 6'd40 : 6'd56);

assign select_ln58_106_fu_2166_p3 = ((a_13_reg_3421[0:0] == 1'b1) ? 7'd112 : 7'd0);

assign select_ln58_107_fu_2250_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19[0:0] == 1'b1) ? select_ln58_105_fu_2234_p3 : select_ln58_109_fu_2242_p3);

assign select_ln58_108_fu_2298_p3 = ((a_15_reg_3433[0:0] == 1'b1) ? 6'd32 : 6'd48);

assign select_ln58_109_fu_2242_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_10_fu_1093_p3 = ((a_2_reg_3322[0:0] == 1'b1) ? 6'd46 : 6'd62);

assign select_ln58_110_fu_2312_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_16[0:0] == 1'b1) ? select_ln58_108_fu_2298_p3 : select_ln58_117_fu_2305_p3);

assign select_ln58_111_fu_2370_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 6'd44 : 6'd60);

assign select_ln58_112_fu_2377_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17[0:0] == 1'b1) ? select_ln58_111_fu_2370_p3 : select_ln58_55_fu_1463_p3);

assign select_ln58_113_fu_2479_p3 = ((a_15_reg_3433[0:0] == 1'b1) ? select_ln58_83_fu_1771_p3 : select_ln58_87_fu_1778_p3);

assign select_ln58_114_fu_2490_p3 = ((a_12_reg_3414[0:0] == 1'b1) ? 6'd38 : 6'd6);

assign select_ln58_115_fu_2497_p3 = ((a_12_reg_3414[0:0] == 1'b1) ? 6'd32 : 6'd0);

assign select_ln58_116_fu_2504_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_16[0:0] == 1'b1) ? select_ln58_114_fu_2490_p3 : select_ln58_115_fu_2497_p3);

assign select_ln58_117_fu_2305_p3 = ((a_15_reg_3433[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_118_fu_2721_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_21[0:0] == 1'b1) ? 6'd40 : 6'd56);

assign select_ln58_119_fu_2685_p3 = ((a_9_reg_3380[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_11_fu_408_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_14[0:0] == 1'b1) ? 4'd6 : 4'd0);

assign select_ln58_120_fu_2737_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_15[0:0] == 1'b1) ? select_ln58_118_fu_2721_p3 : select_ln58_122_fu_2729_p3);

assign select_ln58_121_fu_618_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_14[0:0] == 1'b1) ? 5'd20 : 5'd24);

assign select_ln58_122_fu_2729_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_21[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_123_fu_634_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_7[0:0] == 1'b1) ? select_ln58_121_fu_618_p3 : select_ln58_125_fu_626_p3);

assign select_ln58_124_fu_2788_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24[0:0] == 1'b1) ? 6'd32 : 6'd48);

assign select_ln58_125_fu_626_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_14[0:0] == 1'b1) ? 5'd28 : 5'd0);

assign select_ln58_126_fu_2804_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? select_ln58_124_fu_2788_p3 : select_ln58_128_fu_2796_p3);

assign select_ln58_127_fu_2832_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17[0:0] == 1'b1) ? 5'd16 : 5'd24);

assign select_ln58_128_fu_2796_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_129_fu_2848_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_16[0:0] == 1'b1) ? select_ln58_127_fu_2832_p3 : select_ln58_131_fu_2840_p3);

assign select_ln58_12_fu_1103_p3 = ((a_4_reg_3340[0:0] == 1'b1) ? 7'd96 : 7'd0);

assign select_ln58_130_fu_2920_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? 6'd40 : 6'd48);

assign select_ln58_131_fu_2840_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17[0:0] == 1'b1) ? 5'd24 : 5'd0);

assign select_ln58_132_fu_2936_p3 = ((a_10_reg_3392[0:0] == 1'b1) ? select_ln58_130_fu_2920_p3 : select_ln58_135_fu_2928_p3);

assign select_ln58_133_fu_2994_p3 = ((a_20_reg_3466[0:0] == 1'b1) ? select_ln58_124_fu_2788_p3 : select_ln58_128_fu_2796_p3);

assign select_ln58_134_fu_3076_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? 4'd8 : 4'd12);

assign select_ln58_135_fu_2928_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_136_fu_3092_p3 = ((a_20_reg_3466[0:0] == 1'b1) ? select_ln58_134_fu_3076_p3 : select_ln58_138_fu_3084_p3);

assign select_ln58_137_fu_3154_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19[0:0] == 1'b1) ? 5'd16 : 5'd24);

assign select_ln58_138_fu_3084_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? 4'd12 : 4'd0);

assign select_ln58_139_fu_3170_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_15[0:0] == 1'b1) ? select_ln58_137_fu_3154_p3 : select_ln58_140_fu_3162_p3);

assign select_ln58_13_fu_1120_p3 = ((a_5_reg_3349[0:0] == 1'b1) ? 5'd24 : 5'd0);

assign select_ln58_140_fu_3162_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19[0:0] == 1'b1) ? 5'd24 : 5'd0);

assign select_ln58_14_fu_1127_p3 = ((a_6_reg_3356[0:0] == 1'b1) ? 8'd224 : 8'd0);

assign select_ln58_15_fu_1134_p3 = ((a_3_reg_3330[0:0] == 1'b1) ? 3'd5 : 3'd6);

assign select_ln58_16_fu_1148_p3 = ((a_5_reg_3349[0:0] == 1'b1) ? select_ln58_15_fu_1134_p3 : select_ln58_17_fu_1141_p3);

assign select_ln58_17_fu_1141_p3 = ((a_3_reg_3330[0:0] == 1'b1) ? 3'd7 : 3'd0);

assign select_ln58_18_fu_1168_p3 = ((a_6_reg_3356[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_19_fu_466_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_10[0:0] == 1'b1) ? 5'd28 : 5'd0);

assign select_ln58_1_fu_1030_p3 = ((a_reg_3308[0:0] == 1'b1) ? 5'd20 : 5'd28);

assign select_ln58_20_fu_1175_p3 = ((a_7_reg_3366[0:0] == 1'b1) ? 5'd24 : 5'd0);

assign select_ln58_21_fu_1185_p3 = ((a_8_reg_3373[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_22_fu_1192_p3 = ((a_8_reg_3373[0:0] == 1'b1) ? 6'd60 : 6'd0);

assign select_ln58_23_fu_1216_p3 = ((a_4_reg_3340[0:0] == 1'b1) ? 6'd32 : 6'd48);

assign select_ln58_24_fu_1209_p3 = ((a_9_reg_3380[0:0] == 1'b1) ? 7'd112 : 7'd0);

assign select_ln58_25_fu_1230_p3 = ((a_8_reg_3373[0:0] == 1'b1) ? select_ln58_23_fu_1216_p3 : select_ln58_27_fu_1223_p3);

assign select_ln58_26_fu_480_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_8[0:0] == 1'b1) ? 2'd2 : 2'd0);

assign select_ln58_27_fu_1223_p3 = ((a_4_reg_3340[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_28_fu_502_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_7[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_29_fu_1260_p3 = ((a_11_reg_3400[0:0] == 1'b1) ? 6'd60 : 6'd0);

assign select_ln58_2_fu_384_p3 = ((void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1[0:0] == 1'b1) ? 5'd24 : 5'd0);

assign select_ln58_30_fu_1267_p3 = ((a_11_reg_3400[0:0] == 1'b1) ? 7'd112 : 7'd0);

assign select_ln58_31_fu_1274_p3 = ((a_9_reg_3380[0:0] == 1'b1) ? 6'd42 : 6'd46);

assign select_ln58_32_fu_516_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_6[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_33_fu_1288_p3 = ((a_11_reg_3400[0:0] == 1'b1) ? select_ln58_31_fu_1274_p3 : select_ln58_35_fu_1281_p3);

assign select_ln58_34_fu_524_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_10[0:0] == 1'b1) ? 4'd8 : 4'd12);

assign select_ln58_35_fu_1281_p3 = ((a_9_reg_3380[0:0] == 1'b1) ? 6'd58 : 6'd62);

assign select_ln58_36_fu_540_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_8[0:0] == 1'b1) ? select_ln58_34_fu_524_p3 : select_ln58_37_fu_532_p3);

assign select_ln58_37_fu_532_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_10[0:0] == 1'b1) ? 4'd12 : 4'd0);

assign select_ln58_38_fu_1324_p3 = ((a_13_reg_3421[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_39_fu_1337_p3 = ((a_13_reg_3421[0:0] == 1'b1) ? 7'd120 : 7'd0);

assign select_ln58_3_fu_1037_p3 = ((a_1_reg_3314[0:0] == 1'b1) ? select_ln58_1_fu_1030_p3 : select_ln58_2_reg_3477);

assign select_ln58_40_fu_1344_p3 = ((a_13_reg_3421[0:0] == 1'b1) ? 8'd224 : 8'd0);

assign select_ln58_41_fu_1351_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_3[0:0] == 1'b1) ? 7'd112 : 7'd0);

assign select_ln58_42_fu_1359_p3 = ((a_15_reg_3433[0:0] == 1'b1) ? 7'd120 : 7'd0);

assign select_ln58_43_fu_1366_p3 = ((a_15_reg_3433[0:0] == 1'b1) ? 6'd60 : 6'd0);

assign select_ln58_44_fu_1373_p3 = ((a_15_reg_3433[0:0] == 1'b1) ? 7'd112 : 7'd0);

assign select_ln58_45_fu_1380_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 7'd96 : 7'd0);

assign select_ln58_46_fu_1387_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 7'd120 : 7'd0);

assign select_ln58_47_fu_1401_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_3[0:0] == 1'b1) ? 5'd22 : 5'd6);

assign select_ln58_48_fu_1409_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_3[0:0] == 1'b1) ? 5'd16 : 5'd0);

assign select_ln58_49_fu_1417_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? select_ln58_47_fu_1401_p3 : select_ln58_48_fu_1409_p3);

assign select_ln58_4_fu_392_p3 = ((void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1[0:0] == 1'b1) ? 5'd16 : 5'd24);

assign select_ln58_50_fu_1394_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 7'd112 : 7'd0);

assign select_ln58_51_fu_1440_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9[0:0] == 1'b1) ? 8'd240 : 8'd0);

assign select_ln58_52_fu_1456_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 6'd32 : 6'd48);

assign select_ln58_53_fu_1448_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_54_fu_1470_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_3[0:0] == 1'b1) ? select_ln58_52_fu_1456_p3 : select_ln58_55_fu_1463_p3);

assign select_ln58_55_fu_1463_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_56_fu_1504_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24[0:0] == 1'b1) ? 8'd240 : 8'd0);

assign select_ln58_57_fu_1512_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24[0:0] == 1'b1) ? 9'd504 : 9'd0);

assign select_ln58_58_fu_1528_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 6'd40 : 6'd48);

assign select_ln58_59_fu_1520_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_5_fu_400_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_18[0:0] == 1'b1) ? select_ln58_4_fu_392_p3 : select_ln58_2_fu_384_p3);

assign select_ln58_60_fu_1542_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? select_ln58_58_fu_1528_p3 : select_ln58_61_fu_1535_p3);

assign select_ln58_61_fu_1535_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_62_fu_1565_p3 = ((a_20_reg_3466[0:0] == 1'b1) ? 7'd112 : 7'd0);

assign select_ln58_63_cast_i_cast146_cast_fu_2610_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_15[0:0] == 1'b1) ? 8'd248 : 8'd0);

assign select_ln58_63_fu_1572_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_21[0:0] == 1'b1) ? 8'd240 : 8'd0);

assign select_ln58_64_fu_1580_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_65_fu_1905_p3 = ((a_1_reg_3314[0:0] == 1'b1) ? 6'd36 : 6'd44);

assign select_ln58_66_fu_1588_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20[0:0] == 1'b1) ? 8'd240 : 8'd0);

assign select_ln58_67_fu_1919_p3 = ((a_9_reg_3380[0:0] == 1'b1) ? select_ln58_65_fu_1905_p3 : select_ln58_91_fu_1912_p3);

assign select_ln58_68_fu_1596_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19[0:0] == 1'b1) ? 8'd240 : 8'd0);

assign select_ln58_69_fu_1604_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_6_fu_1047_p3 = ((a_2_reg_3322[0:0] == 1'b1) ? 6'd38 : 6'd46);

assign select_ln58_70_fu_1661_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? 5'd20 : 5'd28);

assign select_ln58_71_fu_2678_p3 = ((a_9_reg_3380[0:0] == 1'b1) ? 6'd40 : 6'd48);

assign select_ln58_72_fu_1612_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19[0:0] == 1'b1) ? 7'd112 : 7'd0);

assign select_ln58_73_fu_2692_p3 = ((a_10_reg_3392[0:0] == 1'b1) ? select_ln58_71_fu_2678_p3 : select_ln58_119_fu_2685_p3);

assign select_ln58_74_fu_3051_p3 = ((a_4_reg_3340[0:0] == 1'b1) ? 5'd16 : 5'd24);

assign select_ln58_75_fu_3058_p3 = ((a_4_reg_3340[0:0] == 1'b1) ? 5'd20 : 5'd28);

assign select_ln58_76_fu_3065_p3 = ((a_5_reg_3349[0:0] == 1'b1) ? select_ln58_74_fu_3051_p3 : select_ln58_75_fu_3058_p3);

assign select_ln58_77_fu_1677_p3 = ((a_20_reg_3466[0:0] == 1'b1) ? select_ln58_70_fu_1661_p3 : select_ln58_78_fu_1669_p3);

assign select_ln58_78_fu_1669_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? 5'd24 : 5'd0);

assign select_ln58_79_fu_1720_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_7_fu_1054_p3 = ((a_2_reg_3322[0:0] == 1'b1) ? 6'd54 : 6'd62);

assign select_ln58_80_fu_1728_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17[0:0] == 1'b1) ? 8'd240 : 8'd0);

assign select_ln58_81_fu_1736_p3 = ((a_6_reg_3356[0:0] == 1'b1) ? 4'd2 : 4'd12);

assign select_ln58_82_fu_1750_p3 = ((a_9_reg_3380[0:0] == 1'b1) ? select_ln58_81_fu_1736_p3 : select_ln58_84_fu_1743_p3);

assign select_ln58_83_fu_1771_p3 = ((a_13_reg_3421[0:0] == 1'b1) ? 6'd40 : 6'd48);

assign select_ln58_84_fu_1743_p3 = ((a_6_reg_3356[0:0] == 1'b1) ? 4'd6 : 4'd0);

assign select_ln58_85_fu_1785_p3 = ((a_12_reg_3414[0:0] == 1'b1) ? select_ln58_83_fu_1771_p3 : select_ln58_87_fu_1778_p3);

assign select_ln58_86_fu_1818_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 5'd20 : 5'd28);

assign select_ln58_87_fu_1778_p3 = ((a_13_reg_3421[0:0] == 1'b1) ? 6'd56 : 6'd0);

assign select_ln58_88_fu_1832_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17[0:0] == 1'b1) ? select_ln58_86_fu_1818_p3 : select_ln58_89_fu_1825_p3);

assign select_ln58_89_fu_1825_p3 = ((a_16_reg_3449[0:0] == 1'b1) ? 5'd24 : 5'd0);

assign select_ln58_8_fu_1061_p3 = ((a_1_reg_3314[0:0] == 1'b1) ? select_ln58_6_fu_1047_p3 : select_ln58_7_fu_1054_p3);

assign select_ln58_90_fu_1926_p3 = ((a_11_reg_3400[0:0] == 1'b1) ? 6'd40 : 6'd56);

assign select_ln58_91_fu_1912_p3 = ((a_1_reg_3314[0:0] == 1'b1) ? 6'd52 : 6'd60);

assign select_ln58_92_fu_1940_p3 = ((a_10_reg_3392[0:0] == 1'b1) ? select_ln58_90_fu_1926_p3 : select_ln58_94_fu_1933_p3);

assign select_ln58_93_fu_1971_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? 6'd32 : 6'd48);

assign select_ln58_94_fu_1933_p3 = ((a_11_reg_3400[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_95_fu_1987_p3 = ((a_20_reg_3466[0:0] == 1'b1) ? select_ln58_93_fu_1971_p3 : select_ln58_99_fu_1979_p3);

assign select_ln58_96_fu_1998_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19[0:0] == 1'b1) ? 6'd40 : 6'd56);

assign select_ln58_97_fu_2006_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20[0:0] == 1'b1) ? select_ln58_96_fu_1998_p3 : select_ln58_69_fu_1604_p3);

assign select_ln58_98_fu_2097_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_17[0:0] == 1'b1) ? 6'd32 : 6'd48);

assign select_ln58_99_fu_1979_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_9_fu_1080_p3 = ((a_3_reg_3330[0:0] == 1'b1) ? 6'd48 : 6'd0);

assign select_ln58_fu_376_p3 = ((void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1[0:0] == 1'b1) ? 5'd28 : 5'd0);

assign sext_ln42_cast_i_fu_970_p3 = ((p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19[0:0] == 1'b1) ? 3'd7 : 3'd0);

assign sext_ln58_101_fu_1500_p1 = $signed(add_ln58_2839_fu_1494_p2);

assign sext_ln58_109_fu_1561_p1 = $signed(add_ln58_2842_fu_1556_p2);

assign sext_ln58_123_fu_1641_p1 = $signed(add_ln58_2846_fu_1635_p2);

assign sext_ln58_124_fu_1657_p1 = $signed(add_ln58_2848_fu_1651_p2);

assign sext_ln58_125_fu_1700_p1 = $signed(add_ln58_2850_fu_1694_p2);

assign sext_ln58_126_fu_1716_p1 = $signed(add_ln58_2852_fu_1710_p2);

assign sext_ln58_131_fu_1967_p1 = $signed(add_ln58_2862_fu_1961_p2);

assign sext_ln58_132_fu_2066_p1 = $signed(add_ln58_2868_fu_2060_p2);

assign sext_ln58_134_fu_2147_p1 = $signed(add_ln58_2873_fu_2141_p2);

assign sext_ln58_136_fu_2294_p1 = $signed(add_ln58_2884_fu_2288_p2);

assign sext_ln58_137_fu_2366_p1 = $signed(add_ln58_2889_fu_2360_p2);

assign sext_ln58_139_fu_2437_p1 = $signed(add_ln58_2895_fu_2431_p2);

assign sext_ln58_140_fu_2469_p1 = $signed(add_ln58_2896_fu_2463_p2);

assign sext_ln58_142_fu_2574_p1 = $signed(add_ln58_2904_fu_2568_p2);

assign sext_ln58_143_fu_2705_p1 = $signed(add_ln58_2909_fu_2699_p2);

assign sext_ln58_145_fu_2781_p1 = $signed(add_ln58_2915_fu_2775_p2);

assign sext_ln58_146_fu_662_p1 = $signed(add_ln58_2916_fu_656_p2);

assign sext_ln58_147_fu_2785_p1 = $signed(add_ln58_2920_reg_3522);

assign sext_ln58_148_fu_2828_p1 = $signed(add_ln58_2922_fu_2822_p2);

assign sext_ln58_151_fu_3072_p1 = $signed(select_ln58_76_fu_3065_p3);

assign sext_ln58_152_fu_3150_p1 = $signed(add_ln58_2942_fu_3144_p2);

assign sext_ln58_61_fu_1076_p1 = $signed(or_ln_fu_1068_p4);

assign sext_ln58_63_fu_1100_p1 = $signed(add_ln58_2823_reg_3482);

assign sext_ln58_64_fu_1116_p1 = $signed(add_ln58_2824_fu_1110_p2);

assign sext_ln58_65_fu_448_p1 = $signed(add_ln58_2825_fu_442_p2);

assign sext_ln58_66_fu_1164_p1 = $signed(or_ln58_3_fu_1155_p4);

assign sext_ln58_68_fu_462_p1 = $signed(or_ln58_4_fu_452_p4);

assign sext_ln58_71_fu_1182_p1 = $signed(add_ln58_2826_reg_3487);

assign sext_ln58_74_fu_1205_p1 = $signed(add_ln58_2827_fu_1199_p2);

assign sext_ln58_759_fu_1237_p1 = $signed(select_ln58_25_fu_1230_p3);

assign sext_ln58_760_fu_1247_p1 = $signed(add_ln58_2828_fu_1241_p2);

assign sext_ln58_761_fu_1305_p1 = $signed(select_ln58_36_reg_3497);

assign sext_ln58_762_fu_1424_p1 = $signed(select_ln58_49_fu_1417_p3);

assign sext_ln58_763_fu_1478_p1 = $signed(select_ln58_54_fu_1470_p3);

assign sext_ln58_764_fu_1684_p1 = $signed(select_ln58_77_fu_1677_p3);

assign sext_ln58_765_fu_1757_p1 = $signed(select_ln58_82_fu_1750_p3);

assign sext_ln58_766_fu_1767_p1 = $signed(add_ln58_2853_fu_1761_p2);

assign sext_ln58_767_fu_1792_p1 = $signed(select_ln58_85_fu_1785_p3);

assign sext_ln58_768_fu_1802_p1 = $signed(add_ln58_2854_fu_1796_p2);

assign sext_ln58_769_fu_1840_p1 = $signed(select_ln58_88_fu_1832_p3);

assign sext_ln58_770_fu_1850_p1 = $signed(add_ln58_2857_fu_1844_p2);

assign sext_ln58_771_fu_1880_p1 = $signed(add_ln58_2859_fu_1874_p2);

assign sext_ln58_772_fu_1947_p1 = $signed(select_ln58_92_fu_1940_p3);

assign sext_ln58_773_fu_1957_p1 = $signed(add_ln58_2861_fu_1951_p2);

assign sext_ln58_774_fu_1994_p1 = $signed(select_ln58_95_fu_1987_p3);

assign sext_ln58_775_fu_2014_p1 = $signed(select_ln58_97_fu_2006_p3);

assign sext_ln58_776_fu_2024_p1 = $signed(add_ln58_2863_fu_2018_p2);

assign sext_ln58_777_fu_2121_p1 = $signed(select_ln58_100_fu_2113_p3);

assign sext_ln58_778_fu_2131_p1 = $signed(add_ln58_2871_fu_2125_p2);

assign sext_ln58_779_fu_2180_p1 = $signed(select_ln58_104_fu_2173_p3);

assign sext_ln58_780_fu_2258_p1 = $signed(select_ln58_107_fu_2250_p3);

assign sext_ln58_781_fu_2268_p1 = $signed(add_ln58_2881_fu_2262_p2);

assign sext_ln58_782_fu_2284_p1 = $signed(add_ln58_2883_fu_2278_p2);

assign sext_ln58_783_fu_2320_p1 = $signed(select_ln58_110_fu_2312_p3);

assign sext_ln58_784_fu_2330_p1 = $signed(add_ln58_2885_fu_2324_p2);

assign sext_ln58_785_fu_2356_p1 = $signed(add_ln58_2888_fu_2350_p2);

assign sext_ln58_786_fu_2385_p1 = $signed(select_ln58_112_fu_2377_p3);

assign sext_ln58_787_fu_2411_p1 = $signed(add_ln58_2892_fu_2405_p2);

assign sext_ln58_788_fu_2427_p1 = $signed(add_ln58_2894_fu_2421_p2);

assign sext_ln58_789_fu_2486_p1 = $signed(select_ln58_113_fu_2479_p3);

assign sext_ln58_790_fu_2512_p1 = $signed(select_ln58_116_fu_2504_p3);

assign sext_ln58_791_fu_2528_p1 = $signed(add_ln58_2899_fu_2522_p2);

assign sext_ln58_792_fu_2564_p1 = $signed(add_ln58_2903_fu_2558_p2);

assign sext_ln58_793_fu_2751_p1 = $signed(add_ln58_2912_fu_2745_p2);

assign sext_ln58_794_fu_2771_p1 = $signed(add_ln58_2914_fu_2765_p2);

assign sext_ln58_795_fu_2812_p1 = $signed(select_ln58_126_fu_2804_p3);

assign sext_ln58_796_fu_2856_p1 = $signed(select_ln58_129_fu_2848_p3);

assign sext_ln58_797_fu_2866_p1 = $signed(add_ln58_2923_fu_2860_p2);

assign sext_ln58_798_fu_2910_p1 = $signed(tmp_5_fu_2902_p3);

assign sext_ln58_799_fu_2949_p1 = $signed(add_ln58_2928_fu_2943_p2);

assign sext_ln58_79_fu_498_p1 = $signed(or_ln58_5_fu_488_p4);

assign sext_ln58_800_fu_2974_p1 = $signed(add_ln58_2931_fu_2968_p2);

assign sext_ln58_801_fu_3001_p1 = $signed(select_ln58_133_fu_2994_p3);

assign sext_ln58_802_fu_3025_p1 = $signed(add_ln58_2934_fu_3019_p2);

assign sext_ln58_803_fu_3099_p1 = $signed(select_ln58_136_fu_3092_p3);

assign sext_ln58_804_fu_3178_p1 = $signed(select_ln58_139_fu_3170_p3);

assign sext_ln58_805_fu_3188_p1 = $signed(add_ln58_2943_fu_3182_p2);

assign sext_ln58_806_fu_2990_p1 = $signed(add_ln58_2933_fu_2984_p2);

assign sext_ln58_84_fu_1257_p1 = $signed(add_ln58_2830_reg_3492);

assign sext_ln58_85_fu_1301_p1 = $signed(add_ln58_2831_fu_1295_p2);

assign sext_ln58_86_fu_1320_p1 = $signed(add_ln58_2833_fu_1314_p2);

assign sext_ln58_fu_1043_p1 = $signed(select_ln58_3_fu_1037_p3);

assign shl_ln73_1_fu_718_p3 = {{a_3_reg_3330}, {2'd0}};

assign shl_ln73_257_cast_fu_2640_p1 = shl_ln73_4_fu_736_p3;

assign shl_ln73_273_cast_fu_2644_p1 = shl_ln73_6_fu_851_p3;

assign shl_ln73_2_fu_216_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_13}, {1'd0}};

assign shl_ln73_4_fu_736_p3 = {{a_7_reg_3366}, {1'd0}};

assign shl_ln73_5_fu_264_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_9}, {1'd0}};

assign shl_ln73_661_cast_i_fu_2622_p1 = shl_ln73_s_fu_711_p3;

assign shl_ln73_662_cast_i_fu_2441_p1 = shl_ln73_1_fu_718_p3;

assign shl_ln73_663_cast_i_fu_574_p1 = shl_ln73_2_fu_216_p3;

assign shl_ln73_666_cast_i_fu_2626_p1 = mult_1733_fu_725_p3;

assign shl_ln73_670_cast_i_fu_578_p1 = shl_ln73_5_fu_264_p3;

assign shl_ln73_696_cast_i_fu_2892_p1 = shl_ln73_8_fu_1022_p3;

assign shl_ln73_6_fu_851_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_23}, {1'd0}};

assign shl_ln73_8_fu_1022_p3 = {{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_15}, {1'd0}};

assign shl_ln73_cast_i_fu_2618_p1 = shl_ln_fu_704_p3;

assign shl_ln73_s_fu_711_p3 = {{a_3_reg_3330}, {1'd0}};

assign shl_ln_fu_704_p3 = {{a_reg_3308}, {1'd0}};

assign tmp10_fu_3005_p4 = {{{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_15}, {p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_20}}, {2'd0}};

assign tmp30_cast_fu_602_p1 = tmp7_fu_592_p4;

assign tmp4822_i_fu_606_p2 = (tmp30_cast_fu_602_p1 + p_cast_i_fu_588_p1);

assign tmp49_i_fu_1894_p3 = {{tmp4822_i_reg_3512}, {1'd0}};

assign tmp5020_i_fu_2445_p2 = (zext_ln17_964_fu_990_p1 + shl_ln73_662_cast_i_fu_2441_p1);

assign tmp51_i_fu_2451_p3 = {{tmp5020_i_fu_2445_p2}, {1'd0}};

assign tmp5518_i_fu_2664_p2 = (tmp77_cast_fu_2660_p1 + tmp76_fu_2648_p2);

assign tmp56_i_fu_2670_p3 = {{tmp5518_i_fu_2664_p2}, {1'd0}};

assign tmp5716_i_fu_2896_p2 = (shl_ln73_696_cast_i_fu_2892_p1 + sext_ln42_cast_i_fu_970_p3);

assign tmp5_fu_548_p4 = {{{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_9}, {p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_5}}, {2'd0}};

assign tmp60_i_fu_3039_p4 = {{{a_10_reg_3392}, {a_16_reg_3449}}, {2'd0}};

assign tmp6_fu_1860_p4 = {{{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_19}, {p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_24}}, {2'd0}};

assign tmp76_fu_2648_p2 = (p_cast65_i_fu_2636_p1 + shl_ln73_666_cast_i_fu_2626_p1);

assign tmp77_cast_fu_2660_p1 = tmp77_fu_2654_p2;

assign tmp77_fu_2654_p2 = (shl_ln73_257_cast_fu_2640_p1 + shl_ln73_273_cast_fu_2644_p1);

assign tmp7_fu_592_p4 = {{{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_5}, {p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_4}}, {1'd0}};

assign tmp8_fu_2076_p5 = {{{{p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_3}, {1'd0}}, {a_20_reg_3466}}, {1'd0}};

assign tmp9_fu_642_p4 = {{{void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig}, {p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_12}}, {2'd0}};

assign tmp_5_fu_2902_p3 = {{tmp5716_i_fu_2896_p2}, {1'd0}};

assign tmp_fu_428_p4 = {{{void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig}, {p_ZZN4nnet24compute_output_buffer_2dINS_5arrayI9ap_ufixedILi1ELi5EL9ap_q_mode0EL9_11}}, {2'd0}};

assign zext_ln17_930_fu_200_p1 = mult_fu_192_p3;

assign zext_ln17_933_fu_232_p1 = mult_1731_fu_224_p3;

assign zext_ln17_935_fu_732_p1 = mult_1733_fu_725_p3;

assign zext_ln17_938_fu_750_p1 = mult_1734_fu_743_p3;

assign zext_ln17_939_fu_280_p1 = mult_1735_fu_272_p3;

assign zext_ln17_940_fu_761_p1 = mult_1736_fu_754_p3;

assign zext_ln17_941_fu_765_p1 = mult_1736_fu_754_p3;

assign zext_ln17_942_fu_304_p1 = mult_1737_fu_296_p3;

assign zext_ln17_943_fu_320_p1 = mult_1738_fu_312_p3;

assign zext_ln17_944_fu_776_p1 = mult_1739_fu_769_p3;

assign zext_ln17_945_fu_780_p1 = mult_1739_fu_769_p3;

assign zext_ln17_946_fu_796_p1 = mult_1740_fu_788_p3;

assign zext_ln17_947_fu_340_p1 = mult_1741_fu_332_p3;

assign zext_ln17_948_fu_807_p1 = mult_1742_fu_800_p3;

assign zext_ln17_949_fu_811_p1 = mult_1742_fu_800_p3;

assign zext_ln17_950_fu_356_p1 = mult_1743_fu_348_p3;

assign zext_ln17_951_fu_827_p1 = mult_1744_fu_819_p3;

assign zext_ln17_952_fu_843_p1 = mult_1745_fu_835_p3;

assign zext_ln17_953_fu_867_p1 = mult_1746_fu_859_p3;

assign zext_ln17_954_fu_878_p1 = mult_1_fu_871_p3;

assign zext_ln17_955_fu_882_p1 = mult_1_fu_871_p3;

assign zext_ln17_956_fu_898_p1 = mult_1748_fu_890_p3;

assign zext_ln17_957_fu_902_p1 = mult_1748_fu_890_p3;

assign zext_ln17_958_fu_906_p1 = mult_1748_fu_890_p3;

assign zext_ln17_959_fu_922_p1 = mult_1749_fu_914_p3;

assign zext_ln17_960_fu_934_p1 = mult_1750_fu_926_p3;

assign zext_ln17_961_fu_950_p1 = mult_1751_fu_942_p3;

assign zext_ln17_962_fu_954_p1 = mult_1751_fu_942_p3;

assign zext_ln17_963_fu_966_p1 = mult_1752_fu_958_p3;

assign zext_ln17_964_fu_990_p1 = mult_1753_fu_982_p3;

assign zext_ln17_965_fu_1006_p1 = mult_1754_fu_998_p3;

assign zext_ln17_966_fu_1010_p1 = mult_1754_fu_998_p3;

assign zext_ln17_967_fu_1014_p1 = mult_1754_fu_998_p3;

assign zext_ln17_fu_248_p1 = mult_1732_fu_240_p3;

assign zext_ln42_fu_372_p1 = mult_1747_fu_364_p3;

assign zext_ln58_1924_fu_558_p1 = tmp5_fu_548_p4;

assign zext_ln58_1925_fu_1632_p1 = add_ln58_2845_reg_3507;

assign zext_ln58_1926_fu_1870_p1 = tmp6_fu_1860_p4;

assign zext_ln58_1927_fu_1901_p1 = tmp49_i_fu_1894_p3;

assign zext_ln58_1928_fu_2040_p1 = add_ln58_2865_fu_2034_p2;

assign zext_ln58_1929_fu_2050_p1 = add_ln58_2866_fu_2044_p2;

assign zext_ln58_1930_fu_2087_p1 = tmp8_fu_2076_p5;

assign zext_ln58_1931_fu_2201_p1 = add_ln58_2876_fu_2196_p2;

assign zext_ln58_1932_fu_2205_p1 = add_ln58_2877_reg_3517;

assign zext_ln58_1933_fu_2214_p1 = add_ln58_2878_fu_2208_p2;

assign zext_ln58_1934_fu_2224_p1 = add_ln58_2879_fu_2218_p2;

assign zext_ln58_1935_fu_2346_p1 = add_ln58_2887_fu_2340_p2;

assign zext_ln58_1936_fu_2401_p1 = add_ln58_2891_fu_2395_p2;

assign zext_ln58_1937_fu_2459_p1 = tmp51_i_fu_2451_p3;

assign zext_ln58_1938_fu_2544_p1 = add_ln58_2901_fu_2538_p2;

assign zext_ln58_1939_fu_2554_p1 = add_ln58_2902_fu_2548_p2;

assign zext_ln58_1940_fu_2590_p1 = add_ln58_2906_fu_2584_p2;

assign zext_ln58_1941_fu_2600_p1 = add_ln58_2907_fu_2594_p2;

assign zext_ln58_1942_fu_2761_p1 = add_ln58_2913_fu_2755_p2;

assign zext_ln58_1943_fu_652_p1 = tmp9_fu_642_p4;

assign zext_ln58_1944_fu_678_p1 = add_ln58_2918_fu_672_p2;

assign zext_ln58_1945_fu_688_p1 = add_ln58_2919_fu_682_p2;

assign zext_ln58_1946_fu_2964_p1 = add_ln58_2930_fu_2959_p2;

assign zext_ln58_1947_fu_3015_p1 = tmp10_fu_3005_p4;

assign zext_ln58_1948_fu_3047_p1 = tmp60_i_fu_3039_p4;

assign zext_ln58_1949_fu_3121_p1 = add_ln58_2938_fu_3115_p2;

assign zext_ln58_1950_fu_3125_p1 = add_ln58_2939_reg_3527;

assign zext_ln58_1951_fu_3134_p1 = add_ln58_2940_fu_3128_p2;

assign zext_ln58_1952_fu_3198_p1 = add_ln58_2944_fu_3192_p2;

assign zext_ln58_fu_438_p1 = tmp_fu_428_p4;

always @ (posedge ap_clk) begin
    zext_ln17_942_reg_3409[1:0] <= 2'b00;
    zext_ln17_942_reg_3409[3] <= 1'b0;
    zext_ln17_947_reg_3444[1:0] <= 2'b00;
    zext_ln17_947_reg_3444[3] <= 1'b0;
    select_ln58_2_reg_3477[2:0] <= 3'b000;
    add_ln58_2823_reg_3482[2:0] <= 3'b000;
    add_ln58_2826_reg_3487[1:0] <= 2'b00;
    add_ln58_2830_reg_3492[1:0] <= 2'b00;
    select_ln58_36_reg_3497[1:0] <= 2'b00;
    add_ln58_2841_reg_3502[1:0] <= 2'b00;
    add_ln58_2845_reg_3507[0] <= 1'b0;
    tmp4822_i_reg_3512[0] <= 1'b0;
    add_ln58_2877_reg_3517[0] <= 1'b0;
    add_ln58_2920_reg_3522[1:0] <= 2'b00;
    add_ln58_2939_reg_3527[1:0] <= 2'b00;
end

endmodule //myproject_dense_latency_ap_ufixed_1_5_0_3_0_ap_fixed_9_9_5_3_0_config7_mult_s
