// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_layer_1_TDATA,
        input_layer_1_TVALID,
        input_layer_1_TREADY,
        layer3_out_din,
        layer3_out_full_n,
        layer3_out_write,
        layer3_out_num_data_valid,
        layer3_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] input_layer_1_TDATA;
input   input_layer_1_TVALID;
output   input_layer_1_TREADY;
output  [79:0] layer3_out_din;
input   layer3_out_full_n;
output   layer3_out_write;
input  [10:0] layer3_out_num_data_valid;
input  [10:0] layer3_out_fifo_cap;

reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    internal_ap_ready;
wire    ap_CS_fsm_state3;
wire    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n;
reg    ap_block_state3_pp0_stage2_iter0;
wire   [0:0] icmp_ln25_fu_134_p2;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_layer_1_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg    layer3_out_blk_n;
wire    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ready;
wire   [0:0] grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_in_elem_0_0_0_0_0_val;
wire   [79:0] grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce;
reg    ap_block_state2_pp0_stage1_iter0_ignore_call6;
reg    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg;
reg   [2:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
reg   [9:0] indvar_flatten2_fu_70;
wire   [9:0] add_ln25_fu_128_p2;
wire    ap_loop_init;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage1_iter0;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_start_int;
wire    ap_done_sig;
wire    regslice_both_input_layer_1_U_apdone_blk;
wire   [7:0] input_layer_1_TDATA_int_regslice;
wire    input_layer_1_TVALID_int_regslice;
reg    input_layer_1_TREADY_int_regslice;
wire    regslice_both_input_layer_1_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg = 1'b0;
#0 indvar_flatten2_fu_70 = 10'd0;
#0 ap_done_reg = 1'b0;
end

myproject_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ready),
    .in_elem_0_0_0_0_0_val(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_in_elem_0_0_0_0_0_val),
    .layer3_out_din(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_din),
    .layer3_out_full_n(layer3_out_full_n),
    .layer3_out_write(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_write),
    .layer3_out_num_data_valid(11'd0),
    .layer3_out_fifo_cap(11'd0),
    .layer3_out_blk_n(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n),
    .ap_ce(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

myproject_regslice_both #(
    .DataWidth( 8 ))
regslice_both_input_layer_1_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_layer_1_TDATA),
    .vld_in(input_layer_1_TVALID),
    .ack_in(regslice_both_input_layer_1_U_ack_in),
    .data_out(input_layer_1_TDATA_int_regslice),
    .vld_out(input_layer_1_TVALID_int_regslice),
    .ack_out(input_layer_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_layer_1_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state2) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        indvar_flatten2_fu_70 <= 10'd0;
    end else if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten2_fu_70 <= add_ln25_fu_128_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage2_iter0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_134_p2 == 1'd1) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_state2_pp0_stage1_iter0_ignore_call6) & (1'b1 == ap_CS_fsm_state2)))) begin
        grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce = 1'b1;
    end else begin
        grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_layer_1_TDATA_blk_n = input_layer_1_TVALID_int_regslice;
    end else begin
        input_layer_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        input_layer_1_TREADY_int_regslice = 1'b1;
    end else begin
        input_layer_1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer3_out_blk_n = grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_pp0_stage2_iter0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_fu_128_p2 = (indvar_flatten2_fu_70 + 10'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (input_layer_1_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_ignore_call6 = (input_layer_1_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = (grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = internal_ap_ready;

assign grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start = grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg;

assign grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_in_elem_0_0_0_0_0_val = input_layer_1_TDATA_int_regslice[0:0];

assign icmp_ln25_fu_134_p2 = ((indvar_flatten2_fu_70 == 10'd783) ? 1'b1 : 1'b0);

assign input_layer_1_TREADY = regslice_both_input_layer_1_U_ack_in;

assign layer3_out_din = grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_din;

assign layer3_out_write = grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_write;

assign start_out = real_start;

endmodule //myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s
