// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer4_out_dout,
        layer4_out_empty_n,
        layer4_out_read,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer5_out_din,
        layer5_out_full_n,
        layer5_out_write,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [79:0] layer4_out_dout;
input   layer4_out_empty_n;
output   layer4_out_read;
input  [10:0] layer4_out_num_data_valid;
input  [10:0] layer4_out_fifo_cap;
output  [15:0] layer5_out_din;
input   layer5_out_full_n;
output   layer5_out_write;
input  [8:0] layer5_out_num_data_valid;
input  [8:0] layer5_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer4_out_read;
reg layer5_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_14;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_8;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_7;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_6;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_5;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_4;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_3;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_2;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_1;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_13;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_12;
reg   [4:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_16u_0_line_buffer_1;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_11;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_10;
reg   [4:0] p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_9;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_31;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_30;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_29;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_28;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_27;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_26;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_25;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_24;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_23;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_22;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_21;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_20;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_19;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_18;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_17;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_16;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_15;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_14;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_13;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_12;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_11;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_10;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_9;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_8;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_7;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_6;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_5;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_4;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_3;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_2;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_1;
reg   [4:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap;
reg   [31:0] sY_1;
reg   [31:0] pY_1;
reg   [31:0] pX_1;
reg   [31:0] sX_1;
reg    layer4_out_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    layer5_out_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln55_reg_3812;
reg   [0:0] and_ln55_2_reg_3816;
reg   [0:0] icmp_ln11186_reg_431;
reg   [4:0] p_0_0_0_0_010984_reg_442;
reg    ap_block_state1;
wire   [4:0] select_ln109_fu_992_p3;
reg   [4:0] select_ln109_reg_3640;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op526_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln109_15_fu_1000_p3;
reg   [4:0] select_ln109_15_reg_3645;
wire   [4:0] select_ln109_16_fu_1008_p3;
reg   [4:0] select_ln109_16_reg_3650;
wire   [4:0] select_ln109_17_fu_1016_p3;
reg   [4:0] select_ln109_17_reg_3655;
wire   [4:0] select_ln109_18_fu_1024_p3;
reg   [4:0] select_ln109_18_reg_3660;
wire   [4:0] select_ln109_19_fu_1032_p3;
reg   [4:0] select_ln109_19_reg_3665;
wire   [4:0] select_ln109_20_fu_1040_p3;
reg   [4:0] select_ln109_20_reg_3670;
wire   [4:0] select_ln109_21_fu_1048_p3;
reg   [4:0] select_ln109_21_reg_3675;
wire   [4:0] select_ln109_22_fu_1056_p3;
reg   [4:0] select_ln109_22_reg_3680;
wire   [4:0] select_ln109_23_fu_1064_p3;
reg   [4:0] select_ln109_23_reg_3685;
wire   [4:0] select_ln109_24_fu_1072_p3;
reg   [4:0] select_ln109_24_reg_3690;
wire   [4:0] select_ln109_25_fu_1080_p3;
reg   [4:0] select_ln109_25_reg_3695;
wire   [4:0] select_ln109_26_fu_1088_p3;
reg   [4:0] select_ln109_26_reg_3700;
wire   [4:0] select_ln109_27_fu_1096_p3;
reg   [4:0] select_ln109_27_reg_3705;
wire   [4:0] select_ln109_28_fu_1104_p3;
reg   [4:0] select_ln109_28_reg_3710;
wire   [4:0] trunc_ln115_fu_1112_p1;
reg   [4:0] trunc_ln115_reg_3715;
wire   [4:0] trunc_ln115_s_fu_1116_p4;
reg   [4:0] trunc_ln115_s_reg_3722;
wire   [4:0] trunc_ln115_15_fu_1126_p4;
reg   [4:0] trunc_ln115_15_reg_3728;
wire   [4:0] trunc_ln115_16_fu_1136_p4;
reg   [4:0] trunc_ln115_16_reg_3734;
wire   [4:0] trunc_ln115_17_fu_1146_p4;
reg   [4:0] trunc_ln115_17_reg_3740;
wire   [4:0] trunc_ln115_18_fu_1156_p4;
reg   [4:0] trunc_ln115_18_reg_3746;
wire   [4:0] trunc_ln115_19_fu_1166_p4;
reg   [4:0] trunc_ln115_19_reg_3752;
wire   [4:0] trunc_ln115_20_fu_1176_p4;
reg   [4:0] trunc_ln115_20_reg_3758;
wire   [4:0] trunc_ln115_21_fu_1186_p4;
reg   [4:0] trunc_ln115_21_reg_3764;
wire   [4:0] trunc_ln115_22_fu_1196_p4;
reg   [4:0] trunc_ln115_22_reg_3770;
wire   [4:0] trunc_ln115_23_fu_1206_p4;
reg   [4:0] trunc_ln115_23_reg_3776;
wire   [4:0] trunc_ln115_24_fu_1216_p4;
reg   [4:0] trunc_ln115_24_reg_3782;
wire   [4:0] trunc_ln115_25_fu_1226_p4;
reg   [4:0] trunc_ln115_25_reg_3788;
wire   [4:0] trunc_ln115_26_fu_1236_p4;
reg   [4:0] trunc_ln115_26_reg_3794;
wire   [4:0] trunc_ln115_27_fu_1246_p4;
reg   [4:0] trunc_ln115_27_reg_3800;
wire   [4:0] trunc_ln115_28_fu_1256_p4;
reg   [4:0] trunc_ln115_28_reg_3806;
wire   [0:0] icmp_ln55_fu_1270_p2;
wire   [0:0] and_ln55_2_fu_1318_p2;
wire   [4:0] select_ln0_fu_1387_p3;
reg   [4:0] select_ln0_reg_3820;
wire   [4:0] select_ln0_32_fu_1415_p3;
reg   [4:0] select_ln0_32_reg_3826;
wire   [4:0] select_ln0_33_fu_1435_p3;
reg   [4:0] select_ln0_33_reg_3832;
wire   [4:0] select_ln0_34_fu_1455_p3;
reg   [4:0] select_ln0_34_reg_3838;
wire   [4:0] select_ln0_35_fu_1475_p3;
reg   [4:0] select_ln0_35_reg_3844;
wire   [4:0] select_ln0_36_fu_1495_p3;
reg   [4:0] select_ln0_36_reg_3850;
wire   [4:0] select_ln0_37_fu_1515_p3;
reg   [4:0] select_ln0_37_reg_3856;
wire   [4:0] select_ln0_38_fu_1535_p3;
reg   [4:0] select_ln0_38_reg_3862;
wire   [4:0] select_ln0_39_fu_1555_p3;
reg   [4:0] select_ln0_39_reg_3868;
wire   [4:0] select_ln0_40_fu_1575_p3;
reg   [4:0] select_ln0_40_reg_3874;
wire   [4:0] select_ln0_41_fu_1595_p3;
reg   [4:0] select_ln0_41_reg_3880;
wire   [4:0] select_ln0_42_fu_1615_p3;
reg   [4:0] select_ln0_42_reg_3886;
wire   [4:0] select_ln0_43_fu_1635_p3;
reg   [4:0] select_ln0_43_reg_3892;
wire   [4:0] select_ln0_44_fu_1655_p3;
reg   [4:0] select_ln0_44_reg_3898;
wire   [4:0] select_ln0_45_fu_1675_p3;
reg   [4:0] select_ln0_45_reg_3904;
wire   [4:0] select_ln0_46_fu_1695_p3;
reg   [4:0] select_ln0_46_reg_3910;
wire   [4:0] select_ln0_47_fu_1715_p3;
reg   [4:0] select_ln0_47_reg_3916;
wire   [4:0] select_ln0_48_fu_1735_p3;
reg   [4:0] select_ln0_48_reg_3922;
wire   [4:0] select_ln0_49_fu_1755_p3;
reg   [4:0] select_ln0_49_reg_3928;
wire   [4:0] select_ln0_50_fu_1775_p3;
reg   [4:0] select_ln0_50_reg_3934;
wire   [4:0] select_ln0_51_fu_1795_p3;
reg   [4:0] select_ln0_51_reg_3940;
wire   [4:0] select_ln0_52_fu_1815_p3;
reg   [4:0] select_ln0_52_reg_3946;
wire   [4:0] select_ln0_53_fu_1835_p3;
reg   [4:0] select_ln0_53_reg_3952;
wire   [4:0] select_ln0_54_fu_1855_p3;
reg   [4:0] select_ln0_54_reg_3958;
wire   [4:0] select_ln0_55_fu_1875_p3;
reg   [4:0] select_ln0_55_reg_3964;
wire   [4:0] select_ln0_56_fu_1895_p3;
reg   [4:0] select_ln0_56_reg_3970;
wire   [4:0] select_ln0_57_fu_1915_p3;
reg   [4:0] select_ln0_57_reg_3976;
wire   [4:0] select_ln0_58_fu_1935_p3;
reg   [4:0] select_ln0_58_reg_3982;
wire   [4:0] select_ln0_59_fu_1955_p3;
reg   [4:0] select_ln0_59_reg_3988;
wire   [4:0] select_ln0_60_fu_1975_p3;
reg   [4:0] select_ln0_60_reg_3994;
wire   [4:0] select_ln0_61_fu_1995_p3;
reg   [4:0] select_ln0_61_reg_4000;
wire   [4:0] select_ln0_62_fu_2015_p3;
reg   [4:0] select_ln0_62_reg_4006;
wire   [0:0] icmp_ln76_fu_2029_p2;
wire   [0:0] icmp_ln80_fu_2083_p2;
wire   [0:0] icmp_ln111_fu_2149_p2;
reg   [0:0] icmp_ln111_reg_4020;
wire   [0:0] icmp_ln109_fu_2155_p2;
reg   [0:0] icmp_ln109_reg_4025;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg   [0:0] ap_phi_mux_icmp_ln11186_phi_fu_435_p4;
reg   [4:0] ap_phi_mux_p_0_0_0_0_010984_phi_fu_445_p4;
reg   [31:0] ap_phi_mux_storemerge_i_phi_fu_455_p4;
wire   [31:0] select_ln86_fu_2111_p3;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_reg_452;
wire    ap_CS_fsm_state4;
wire   [31:0] add_ln80_fu_2077_p2;
wire   [31:0] add_ln76_fu_2023_p2;
wire   [31:0] select_ln91_fu_2047_p3;
reg   [9:0] indvar_flatten3_fu_222;
wire   [9:0] add_ln109_fu_1280_p2;
reg   [4:0] p_0_15_0_0_02496_fu_226;
reg   [4:0] p_0_14_0_0_02458_fu_230;
reg   [4:0] p_0_13_0_0_024110_fu_234;
reg   [4:0] p_0_12_0_0_023712_fu_238;
reg   [4:0] p_0_11_0_0_023314_fu_242;
reg   [4:0] p_0_10_0_0_022916_fu_246;
reg   [4:0] p_0_9_0_0_022518_fu_250;
reg   [4:0] p_0_8_0_0_022120_fu_254;
reg   [4:0] p_0_7_0_0_021722_fu_258;
reg   [4:0] p_0_6_0_0_021324_fu_262;
reg   [4:0] p_0_5_0_0_020926_fu_266;
reg   [4:0] p_0_4_0_0_020528_fu_270;
reg   [4:0] p_0_3_0_0_020130_fu_274;
reg   [4:0] p_0_2_0_0_019732_fu_278;
reg   [4:0] p_0_1_0_0_019334_fu_282;
reg   [4:0] p_0_0_0_0_018936_fu_286;
reg   [4:0] p_0_15_0_0_013918637_fu_290;
reg   [4:0] p_0_14_0_0_013718339_fu_294;
reg   [4:0] p_0_13_0_0_013518041_fu_298;
reg   [4:0] p_0_12_0_0_013317743_fu_302;
reg   [4:0] p_0_11_0_0_013117445_fu_306;
reg   [4:0] p_0_10_0_0_012917147_fu_310;
reg   [4:0] p_0_9_0_0_012716849_fu_314;
reg   [4:0] p_0_8_0_0_012516551_fu_318;
reg   [4:0] p_0_7_0_0_012316253_fu_322;
reg   [4:0] p_0_6_0_0_012115955_fu_326;
reg   [4:0] p_0_5_0_0_011915657_fu_330;
reg   [4:0] p_0_4_0_0_011715359_fu_334;
reg   [4:0] p_0_3_0_0_011515061_fu_338;
reg   [4:0] p_0_2_0_0_011314763_fu_342;
reg   [4:0] p_0_1_0_0_011114465_fu_346;
reg   [4:0] p_0_0_0_0_010914167_fu_350;
reg   [4:0] p_0_15_0_0_013969_fu_354;
reg   [4:0] p_0_14_0_0_013770_fu_358;
reg   [4:0] p_0_13_0_0_013571_fu_362;
reg   [4:0] p_0_12_0_0_013372_fu_366;
reg   [4:0] p_0_11_0_0_013173_fu_370;
reg   [4:0] p_0_10_0_0_012974_fu_374;
reg   [4:0] p_0_9_0_0_012775_fu_378;
reg   [4:0] p_0_8_0_0_012576_fu_382;
reg   [4:0] p_0_7_0_0_012377_fu_386;
reg   [4:0] p_0_6_0_0_012178_fu_390;
reg   [4:0] p_0_5_0_0_011979_fu_394;
reg   [4:0] p_0_4_0_0_011780_fu_398;
reg   [4:0] p_0_3_0_0_011581_fu_402;
reg   [4:0] p_0_2_0_0_011382_fu_406;
reg   [4:0] p_0_1_0_0_011183_fu_410;
reg   [4:0] i_iw_fu_414;
wire   [4:0] i_iw_3_fu_2141_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln55_5_fu_1300_p2;
wire   [0:0] icmp_ln55_6_fu_1306_p2;
wire   [0:0] and_ln55_fu_1312_p2;
wire   [0:0] icmp_ln55_4_fu_1290_p2;
wire   [0:0] icmp_ln66_fu_1375_p2;
wire   [0:0] xor_ln66_fu_1381_p2;
wire   [4:0] select_ln10987_fu_1395_p3;
wire   [0:0] icmp_ln66_48_fu_1403_p2;
wire   [0:0] xor_ln66_48_fu_1409_p2;
wire   [0:0] icmp_ln66_50_fu_1423_p2;
wire   [0:0] xor_ln66_50_fu_1429_p2;
wire   [0:0] icmp_ln66_51_fu_1443_p2;
wire   [0:0] xor_ln66_51_fu_1449_p2;
wire   [0:0] icmp_ln66_53_fu_1463_p2;
wire   [0:0] xor_ln66_53_fu_1469_p2;
wire   [0:0] icmp_ln66_54_fu_1483_p2;
wire   [0:0] xor_ln66_54_fu_1489_p2;
wire   [0:0] icmp_ln66_56_fu_1503_p2;
wire   [0:0] xor_ln66_56_fu_1509_p2;
wire   [0:0] icmp_ln66_57_fu_1523_p2;
wire   [0:0] xor_ln66_57_fu_1529_p2;
wire   [0:0] icmp_ln66_59_fu_1543_p2;
wire   [0:0] xor_ln66_59_fu_1549_p2;
wire   [0:0] icmp_ln66_60_fu_1563_p2;
wire   [0:0] xor_ln66_60_fu_1569_p2;
wire   [0:0] icmp_ln66_62_fu_1583_p2;
wire   [0:0] xor_ln66_62_fu_1589_p2;
wire   [0:0] icmp_ln66_63_fu_1603_p2;
wire   [0:0] xor_ln66_63_fu_1609_p2;
wire   [0:0] icmp_ln66_65_fu_1623_p2;
wire   [0:0] xor_ln66_65_fu_1629_p2;
wire   [0:0] icmp_ln66_66_fu_1643_p2;
wire   [0:0] xor_ln66_66_fu_1649_p2;
wire   [0:0] icmp_ln66_68_fu_1663_p2;
wire   [0:0] xor_ln66_68_fu_1669_p2;
wire   [0:0] icmp_ln66_69_fu_1683_p2;
wire   [0:0] xor_ln66_69_fu_1689_p2;
wire   [0:0] icmp_ln66_71_fu_1703_p2;
wire   [0:0] xor_ln66_71_fu_1709_p2;
wire   [0:0] icmp_ln66_72_fu_1723_p2;
wire   [0:0] xor_ln66_72_fu_1729_p2;
wire   [0:0] icmp_ln66_74_fu_1743_p2;
wire   [0:0] xor_ln66_74_fu_1749_p2;
wire   [0:0] icmp_ln66_75_fu_1763_p2;
wire   [0:0] xor_ln66_75_fu_1769_p2;
wire   [0:0] icmp_ln66_77_fu_1783_p2;
wire   [0:0] xor_ln66_77_fu_1789_p2;
wire   [0:0] icmp_ln66_78_fu_1803_p2;
wire   [0:0] xor_ln66_78_fu_1809_p2;
wire   [0:0] icmp_ln66_80_fu_1823_p2;
wire   [0:0] xor_ln66_80_fu_1829_p2;
wire   [0:0] icmp_ln66_81_fu_1843_p2;
wire   [0:0] xor_ln66_81_fu_1849_p2;
wire   [0:0] icmp_ln66_83_fu_1863_p2;
wire   [0:0] xor_ln66_83_fu_1869_p2;
wire   [0:0] icmp_ln66_84_fu_1883_p2;
wire   [0:0] xor_ln66_84_fu_1889_p2;
wire   [0:0] icmp_ln66_86_fu_1903_p2;
wire   [0:0] xor_ln66_86_fu_1909_p2;
wire   [0:0] icmp_ln66_87_fu_1923_p2;
wire   [0:0] xor_ln66_87_fu_1929_p2;
wire   [0:0] icmp_ln66_89_fu_1943_p2;
wire   [0:0] xor_ln66_89_fu_1949_p2;
wire   [0:0] icmp_ln66_90_fu_1963_p2;
wire   [0:0] xor_ln66_90_fu_1969_p2;
wire   [0:0] icmp_ln66_92_fu_1983_p2;
wire   [0:0] xor_ln66_92_fu_1989_p2;
wire   [0:0] icmp_ln66_93_fu_2003_p2;
wire   [0:0] xor_ln66_93_fu_2009_p2;
wire   [31:0] add_ln91_fu_2041_p2;
wire   [0:0] icmp_ln86_fu_2099_p2;
wire   [31:0] add_ln86_fu_2105_p2;
wire   [4:0] add_ln111_fu_2135_p2;
wire   [0:0] icmp_ln66_49_fu_2406_p2;
wire   [0:0] xor_ln66_49_fu_2410_p2;
wire   [4:0] select_ln66_fu_2416_p3;
wire   [0:0] tmp_fu_2422_p3;
wire   [0:0] tmp_16_fu_2430_p3;
wire   [0:0] icmp_ln66_52_fu_2444_p2;
wire   [0:0] xor_ln66_52_fu_2448_p2;
wire   [4:0] select_ln66_16_fu_2454_p3;
wire   [0:0] tmp_17_fu_2460_p3;
wire   [0:0] tmp_18_fu_2468_p3;
wire   [0:0] icmp_ln66_55_fu_2482_p2;
wire   [0:0] xor_ln66_55_fu_2486_p2;
wire   [4:0] select_ln66_17_fu_2492_p3;
wire   [0:0] tmp_19_fu_2498_p3;
wire   [0:0] tmp_20_fu_2506_p3;
wire   [0:0] icmp_ln66_58_fu_2520_p2;
wire   [0:0] xor_ln66_58_fu_2524_p2;
wire   [4:0] select_ln66_18_fu_2530_p3;
wire   [0:0] tmp_21_fu_2536_p3;
wire   [0:0] tmp_22_fu_2544_p3;
wire   [0:0] icmp_ln66_61_fu_2558_p2;
wire   [0:0] xor_ln66_61_fu_2562_p2;
wire   [4:0] select_ln66_19_fu_2568_p3;
wire   [0:0] tmp_23_fu_2574_p3;
wire   [0:0] tmp_24_fu_2582_p3;
wire   [0:0] icmp_ln66_64_fu_2596_p2;
wire   [0:0] xor_ln66_64_fu_2600_p2;
wire   [4:0] select_ln66_20_fu_2606_p3;
wire   [0:0] tmp_25_fu_2612_p3;
wire   [0:0] tmp_26_fu_2620_p3;
wire   [0:0] icmp_ln66_67_fu_2634_p2;
wire   [0:0] xor_ln66_67_fu_2638_p2;
wire   [4:0] select_ln66_21_fu_2644_p3;
wire   [0:0] tmp_27_fu_2650_p3;
wire   [0:0] tmp_28_fu_2658_p3;
wire   [0:0] icmp_ln66_70_fu_2672_p2;
wire   [0:0] xor_ln66_70_fu_2676_p2;
wire   [4:0] select_ln66_22_fu_2682_p3;
wire   [0:0] tmp_29_fu_2688_p3;
wire   [0:0] tmp_30_fu_2696_p3;
wire   [0:0] icmp_ln66_73_fu_2710_p2;
wire   [0:0] xor_ln66_73_fu_2714_p2;
wire   [4:0] select_ln66_23_fu_2720_p3;
wire   [0:0] tmp_31_fu_2726_p3;
wire   [0:0] tmp_32_fu_2734_p3;
wire   [0:0] icmp_ln66_76_fu_2748_p2;
wire   [0:0] xor_ln66_76_fu_2752_p2;
wire   [4:0] select_ln66_24_fu_2758_p3;
wire   [0:0] tmp_33_fu_2764_p3;
wire   [0:0] tmp_34_fu_2772_p3;
wire   [0:0] icmp_ln66_79_fu_2786_p2;
wire   [0:0] xor_ln66_79_fu_2790_p2;
wire   [4:0] select_ln66_25_fu_2796_p3;
wire   [0:0] tmp_35_fu_2802_p3;
wire   [0:0] tmp_36_fu_2810_p3;
wire   [0:0] icmp_ln66_82_fu_2824_p2;
wire   [0:0] xor_ln66_82_fu_2828_p2;
wire   [4:0] select_ln66_26_fu_2834_p3;
wire   [0:0] tmp_37_fu_2840_p3;
wire   [0:0] tmp_38_fu_2848_p3;
wire   [0:0] icmp_ln66_85_fu_2862_p2;
wire   [0:0] xor_ln66_85_fu_2866_p2;
wire   [4:0] select_ln66_27_fu_2872_p3;
wire   [0:0] tmp_39_fu_2878_p3;
wire   [0:0] tmp_40_fu_2886_p3;
wire   [0:0] icmp_ln66_88_fu_2900_p2;
wire   [0:0] xor_ln66_88_fu_2904_p2;
wire   [4:0] select_ln66_28_fu_2910_p3;
wire   [0:0] tmp_41_fu_2916_p3;
wire   [0:0] tmp_42_fu_2924_p3;
wire   [0:0] icmp_ln66_91_fu_2938_p2;
wire   [0:0] xor_ln66_91_fu_2942_p2;
wire   [4:0] select_ln66_29_fu_2948_p3;
wire   [0:0] tmp_43_fu_2954_p3;
wire   [0:0] tmp_44_fu_2962_p3;
wire   [0:0] icmp_ln66_94_fu_2976_p2;
wire   [0:0] xor_ln66_94_fu_2980_p2;
wire   [4:0] select_ln66_30_fu_2986_p3;
wire   [0:0] tmp_45_fu_2992_p3;
wire   [0:0] tmp_46_fu_3000_p3;
wire   [0:0] res_pack_30_fu_3008_p2;
wire   [0:0] res_pack_29_fu_2970_p2;
wire   [0:0] res_pack_28_fu_2932_p2;
wire   [0:0] res_pack_27_fu_2894_p2;
wire   [0:0] res_pack_26_fu_2856_p2;
wire   [0:0] res_pack_25_fu_2818_p2;
wire   [0:0] res_pack_24_fu_2780_p2;
wire   [0:0] res_pack_23_fu_2742_p2;
wire   [0:0] res_pack_22_fu_2704_p2;
wire   [0:0] res_pack_21_fu_2666_p2;
wire   [0:0] res_pack_20_fu_2628_p2;
wire   [0:0] res_pack_19_fu_2590_p2;
wire   [0:0] res_pack_18_fu_2552_p2;
wire   [0:0] res_pack_17_fu_2514_p2;
wire   [0:0] res_pack_16_fu_2476_p2;
wire   [0:0] res_pack_fu_2438_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_163;
reg    ap_condition_426;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_14 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_8 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_7 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_6 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_5 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_4 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_3 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_2 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_1 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_13 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_12 = 5'd0;
#0 void_pooling2d_cl_stream_stream_array_ap_ufixed_16u_0_line_buffer_1 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_11 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_10 = 5'd0;
#0 p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_9 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_31 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_30 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_29 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_28 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_27 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_26 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_25 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_24 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_23 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_22 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_21 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_20 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_19 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_18 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_17 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_16 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_15 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_14 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_13 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_12 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_11 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_10 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_9 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_8 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_7 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_6 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_5 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_4 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_3 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_2 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_1 = 5'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap = 5'd0;
#0 sY_1 = 32'd0;
#0 pY_1 = 32'd0;
#0 pX_1 = 32'd0;
#0 sX_1 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 indvar_flatten3_fu_222 = 10'd0;
#0 p_0_15_0_0_02496_fu_226 = 5'd0;
#0 p_0_14_0_0_02458_fu_230 = 5'd0;
#0 p_0_13_0_0_024110_fu_234 = 5'd0;
#0 p_0_12_0_0_023712_fu_238 = 5'd0;
#0 p_0_11_0_0_023314_fu_242 = 5'd0;
#0 p_0_10_0_0_022916_fu_246 = 5'd0;
#0 p_0_9_0_0_022518_fu_250 = 5'd0;
#0 p_0_8_0_0_022120_fu_254 = 5'd0;
#0 p_0_7_0_0_021722_fu_258 = 5'd0;
#0 p_0_6_0_0_021324_fu_262 = 5'd0;
#0 p_0_5_0_0_020926_fu_266 = 5'd0;
#0 p_0_4_0_0_020528_fu_270 = 5'd0;
#0 p_0_3_0_0_020130_fu_274 = 5'd0;
#0 p_0_2_0_0_019732_fu_278 = 5'd0;
#0 p_0_1_0_0_019334_fu_282 = 5'd0;
#0 p_0_0_0_0_018936_fu_286 = 5'd0;
#0 p_0_15_0_0_013918637_fu_290 = 5'd0;
#0 p_0_14_0_0_013718339_fu_294 = 5'd0;
#0 p_0_13_0_0_013518041_fu_298 = 5'd0;
#0 p_0_12_0_0_013317743_fu_302 = 5'd0;
#0 p_0_11_0_0_013117445_fu_306 = 5'd0;
#0 p_0_10_0_0_012917147_fu_310 = 5'd0;
#0 p_0_9_0_0_012716849_fu_314 = 5'd0;
#0 p_0_8_0_0_012516551_fu_318 = 5'd0;
#0 p_0_7_0_0_012316253_fu_322 = 5'd0;
#0 p_0_6_0_0_012115955_fu_326 = 5'd0;
#0 p_0_5_0_0_011915657_fu_330 = 5'd0;
#0 p_0_4_0_0_011715359_fu_334 = 5'd0;
#0 p_0_3_0_0_011515061_fu_338 = 5'd0;
#0 p_0_2_0_0_011314763_fu_342 = 5'd0;
#0 p_0_1_0_0_011114465_fu_346 = 5'd0;
#0 p_0_0_0_0_010914167_fu_350 = 5'd0;
#0 p_0_15_0_0_013969_fu_354 = 5'd0;
#0 p_0_14_0_0_013770_fu_358 = 5'd0;
#0 p_0_13_0_0_013571_fu_362 = 5'd0;
#0 p_0_12_0_0_013372_fu_366 = 5'd0;
#0 p_0_11_0_0_013173_fu_370 = 5'd0;
#0 p_0_10_0_0_012974_fu_374 = 5'd0;
#0 p_0_9_0_0_012775_fu_378 = 5'd0;
#0 p_0_8_0_0_012576_fu_382 = 5'd0;
#0 p_0_7_0_0_012377_fu_386 = 5'd0;
#0 p_0_6_0_0_012178_fu_390 = 5'd0;
#0 p_0_5_0_0_011979_fu_394 = 5'd0;
#0 p_0_4_0_0_011780_fu_398 = 5'd0;
#0 p_0_3_0_0_011581_fu_402 = 5'd0;
#0 p_0_2_0_0_011382_fu_406 = 5'd0;
#0 p_0_1_0_0_011183_fu_410 = 5'd0;
#0 i_iw_fu_414 = 5'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        i_iw_fu_414 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_iw_fu_414 <= i_iw_3_fu_2141_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_4025 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln11186_reg_431 <= icmp_ln111_reg_4020;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        icmp_ln11186_reg_431 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        indvar_flatten3_fu_222 <= 10'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten3_fu_222 <= add_ln109_fu_1280_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_163)) begin
        if ((icmp_ln76_fu_2029_p2 == 1'd1)) begin
            pX_1 <= 32'd0;
        end else if ((icmp_ln76_fu_2029_p2 == 1'd0)) begin
            pX_1 <= add_ln76_fu_2023_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_426)) begin
        if ((icmp_ln80_fu_2083_p2 == 1'd1)) begin
            pY_1 <= 32'd0;
        end else if ((icmp_ln80_fu_2083_p2 == 1'd0)) begin
            pY_1 <= add_ln80_fu_2077_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_010914167_fu_350 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_31;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_0_0_0_010914167_fu_350 <= ap_phi_mux_p_0_0_0_0_010984_phi_fu_445_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_reg_4025 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_0_0_0_010984_reg_442 <= trunc_ln115_reg_3715;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_010984_reg_442 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_14;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_018936_fu_286 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_15;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_0_0_0_018936_fu_286 <= trunc_ln115_fu_1112_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_012917147_fu_310 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_21;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_012917147_fu_310 <= select_ln109_19_fu_1032_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_012974_fu_374 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_13;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_012974_fu_374 <= {{layer4_out_dout[54:50]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_022916_fu_246 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_5;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_10_0_0_022916_fu_246 <= {{layer4_out_dout[54:50]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_013117445_fu_306 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_20;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_013117445_fu_306 <= select_ln109_18_fu_1024_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_013173_fu_370 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_12;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_013173_fu_370 <= {{layer4_out_dout[59:55]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_023314_fu_242 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_4;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_11_0_0_023314_fu_242 <= {{layer4_out_dout[59:55]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_013317743_fu_302 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_19;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_013317743_fu_302 <= select_ln109_17_fu_1016_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_013372_fu_366 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_16u_0_line_buffer_1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_013372_fu_366 <= {{layer4_out_dout[64:60]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_023712_fu_238 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_3;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_12_0_0_023712_fu_238 <= {{layer4_out_dout[64:60]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_013518041_fu_298 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_18;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_013518041_fu_298 <= select_ln109_16_fu_1008_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_013571_fu_362 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_11;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_013571_fu_362 <= {{layer4_out_dout[69:65]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_024110_fu_234 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_2;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_13_0_0_024110_fu_234 <= {{layer4_out_dout[69:65]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_013718339_fu_294 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_17;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_013718339_fu_294 <= select_ln109_15_fu_1000_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_013770_fu_358 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_10;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_013770_fu_358 <= {{layer4_out_dout[74:70]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_14_0_0_02458_fu_230 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_14_0_0_02458_fu_230 <= {{layer4_out_dout[74:70]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_013918637_fu_290 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_16;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_013918637_fu_290 <= select_ln109_fu_992_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_013969_fu_354 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_9;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_013969_fu_354 <= {{layer4_out_dout[79:75]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_15_0_0_02496_fu_226 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_15_0_0_02496_fu_226 <= {{layer4_out_dout[79:75]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_011114465_fu_346 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_30;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_011114465_fu_346 <= select_ln109_28_fu_1104_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_011183_fu_410 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_8;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_011183_fu_410 <= {{layer4_out_dout[9:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_019334_fu_282 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_14;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_1_0_0_019334_fu_282 <= {{layer4_out_dout[9:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_011314763_fu_342 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_29;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_011314763_fu_342 <= select_ln109_27_fu_1096_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_011382_fu_406 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_7;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_011382_fu_406 <= {{layer4_out_dout[14:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_019732_fu_278 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_13;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_2_0_0_019732_fu_278 <= {{layer4_out_dout[14:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_011515061_fu_338 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_28;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_011515061_fu_338 <= select_ln109_26_fu_1088_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_011581_fu_402 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_6;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_011581_fu_402 <= {{layer4_out_dout[19:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_020130_fu_274 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_12;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_3_0_0_020130_fu_274 <= {{layer4_out_dout[19:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_011715359_fu_334 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_27;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_011715359_fu_334 <= select_ln109_25_fu_1080_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_011780_fu_398 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_5;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_011780_fu_398 <= {{layer4_out_dout[24:20]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_020528_fu_270 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_11;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_4_0_0_020528_fu_270 <= {{layer4_out_dout[24:20]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_011915657_fu_330 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_26;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_011915657_fu_330 <= select_ln109_24_fu_1072_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_011979_fu_394 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_4;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_011979_fu_394 <= {{layer4_out_dout[29:25]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_020926_fu_266 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_10;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_5_0_0_020926_fu_266 <= {{layer4_out_dout[29:25]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_012115955_fu_326 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_25;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_012115955_fu_326 <= select_ln109_23_fu_1064_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_012178_fu_390 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_3;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_012178_fu_390 <= {{layer4_out_dout[34:30]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_021324_fu_262 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_9;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_6_0_0_021324_fu_262 <= {{layer4_out_dout[34:30]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_012316253_fu_322 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_24;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_012316253_fu_322 <= select_ln109_22_fu_1056_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_012377_fu_386 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_2;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_012377_fu_386 <= {{layer4_out_dout[39:35]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_021722_fu_258 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_8;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_7_0_0_021722_fu_258 <= {{layer4_out_dout[39:35]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_012516551_fu_318 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_23;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_012516551_fu_318 <= select_ln109_21_fu_1048_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_012576_fu_382 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_012576_fu_382 <= {{layer4_out_dout[44:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_022120_fu_254 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_7;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_8_0_0_022120_fu_254 <= {{layer4_out_dout[44:40]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_012716849_fu_314 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_22;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_012716849_fu_314 <= select_ln109_20_fu_1040_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_012775_fu_378 <= p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_012775_fu_378 <= {{layer4_out_dout[49:45]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_022518_fu_250 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_6;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_0_9_0_0_022518_fu_250 <= {{layer4_out_dout[49:45]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_163)) begin
        if ((icmp_ln76_fu_2029_p2 == 1'd1)) begin
            sX_1 <= 32'd0;
        end else if ((icmp_ln76_fu_2029_p2 == 1'd0)) begin
            sX_1 <= select_ln91_fu_2047_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln55_2_reg_3816 <= and_ln55_2_fu_1318_p2;
        icmp_ln109_reg_4025 <= icmp_ln109_fu_2155_p2;
        icmp_ln55_reg_3812 <= icmp_ln55_fu_1270_p2;
        select_ln0_32_reg_3826 <= select_ln0_32_fu_1415_p3;
        select_ln0_33_reg_3832 <= select_ln0_33_fu_1435_p3;
        select_ln0_34_reg_3838 <= select_ln0_34_fu_1455_p3;
        select_ln0_35_reg_3844 <= select_ln0_35_fu_1475_p3;
        select_ln0_36_reg_3850 <= select_ln0_36_fu_1495_p3;
        select_ln0_37_reg_3856 <= select_ln0_37_fu_1515_p3;
        select_ln0_38_reg_3862 <= select_ln0_38_fu_1535_p3;
        select_ln0_39_reg_3868 <= select_ln0_39_fu_1555_p3;
        select_ln0_40_reg_3874 <= select_ln0_40_fu_1575_p3;
        select_ln0_41_reg_3880 <= select_ln0_41_fu_1595_p3;
        select_ln0_42_reg_3886 <= select_ln0_42_fu_1615_p3;
        select_ln0_43_reg_3892 <= select_ln0_43_fu_1635_p3;
        select_ln0_44_reg_3898 <= select_ln0_44_fu_1655_p3;
        select_ln0_45_reg_3904 <= select_ln0_45_fu_1675_p3;
        select_ln0_46_reg_3910 <= select_ln0_46_fu_1695_p3;
        select_ln0_47_reg_3916 <= select_ln0_47_fu_1715_p3;
        select_ln0_48_reg_3922 <= select_ln0_48_fu_1735_p3;
        select_ln0_49_reg_3928 <= select_ln0_49_fu_1755_p3;
        select_ln0_50_reg_3934 <= select_ln0_50_fu_1775_p3;
        select_ln0_51_reg_3940 <= select_ln0_51_fu_1795_p3;
        select_ln0_52_reg_3946 <= select_ln0_52_fu_1815_p3;
        select_ln0_53_reg_3952 <= select_ln0_53_fu_1835_p3;
        select_ln0_54_reg_3958 <= select_ln0_54_fu_1855_p3;
        select_ln0_55_reg_3964 <= select_ln0_55_fu_1875_p3;
        select_ln0_56_reg_3970 <= select_ln0_56_fu_1895_p3;
        select_ln0_57_reg_3976 <= select_ln0_57_fu_1915_p3;
        select_ln0_58_reg_3982 <= select_ln0_58_fu_1935_p3;
        select_ln0_59_reg_3988 <= select_ln0_59_fu_1955_p3;
        select_ln0_60_reg_3994 <= select_ln0_60_fu_1975_p3;
        select_ln0_61_reg_4000 <= select_ln0_61_fu_1995_p3;
        select_ln0_62_reg_4006 <= select_ln0_62_fu_2015_p3;
        select_ln0_reg_3820 <= select_ln0_fu_1387_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        icmp_ln111_reg_4020 <= icmp_ln111_fu_2149_p2;
        select_ln109_15_reg_3645 <= select_ln109_15_fu_1000_p3;
        select_ln109_16_reg_3650 <= select_ln109_16_fu_1008_p3;
        select_ln109_17_reg_3655 <= select_ln109_17_fu_1016_p3;
        select_ln109_18_reg_3660 <= select_ln109_18_fu_1024_p3;
        select_ln109_19_reg_3665 <= select_ln109_19_fu_1032_p3;
        select_ln109_20_reg_3670 <= select_ln109_20_fu_1040_p3;
        select_ln109_21_reg_3675 <= select_ln109_21_fu_1048_p3;
        select_ln109_22_reg_3680 <= select_ln109_22_fu_1056_p3;
        select_ln109_23_reg_3685 <= select_ln109_23_fu_1064_p3;
        select_ln109_24_reg_3690 <= select_ln109_24_fu_1072_p3;
        select_ln109_25_reg_3695 <= select_ln109_25_fu_1080_p3;
        select_ln109_26_reg_3700 <= select_ln109_26_fu_1088_p3;
        select_ln109_27_reg_3705 <= select_ln109_27_fu_1096_p3;
        select_ln109_28_reg_3710 <= select_ln109_28_fu_1104_p3;
        select_ln109_reg_3640 <= select_ln109_fu_992_p3;
        trunc_ln115_15_reg_3728 <= {{layer4_out_dout[14:10]}};
        trunc_ln115_16_reg_3734 <= {{layer4_out_dout[19:15]}};
        trunc_ln115_17_reg_3740 <= {{layer4_out_dout[24:20]}};
        trunc_ln115_18_reg_3746 <= {{layer4_out_dout[29:25]}};
        trunc_ln115_19_reg_3752 <= {{layer4_out_dout[34:30]}};
        trunc_ln115_20_reg_3758 <= {{layer4_out_dout[39:35]}};
        trunc_ln115_21_reg_3764 <= {{layer4_out_dout[44:40]}};
        trunc_ln115_22_reg_3770 <= {{layer4_out_dout[49:45]}};
        trunc_ln115_23_reg_3776 <= {{layer4_out_dout[54:50]}};
        trunc_ln115_24_reg_3782 <= {{layer4_out_dout[59:55]}};
        trunc_ln115_25_reg_3788 <= {{layer4_out_dout[64:60]}};
        trunc_ln115_26_reg_3794 <= {{layer4_out_dout[69:65]}};
        trunc_ln115_27_reg_3800 <= {{layer4_out_dout[74:70]}};
        trunc_ln115_28_reg_3806 <= {{layer4_out_dout[79:75]}};
        trunc_ln115_reg_3715 <= trunc_ln115_fu_1112_p1;
        trunc_ln115_s_reg_3722 <= {{layer4_out_dout[9:5]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL <= trunc_ln115_22_reg_3770;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_1 <= trunc_ln115_21_reg_3764;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_10 <= trunc_ln115_27_reg_3800;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_11 <= trunc_ln115_26_reg_3794;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_12 <= trunc_ln115_24_reg_3782;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_13 <= trunc_ln115_23_reg_3776;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_14 <= trunc_ln115_reg_3715;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_2 <= trunc_ln115_20_reg_3758;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_3 <= trunc_ln115_19_reg_3752;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_4 <= trunc_ln115_18_reg_3746;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_5 <= trunc_ln115_17_reg_3740;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_6 <= trunc_ln115_16_reg_3734;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_7 <= trunc_ln115_15_reg_3728;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_8 <= trunc_ln115_s_reg_3722;
        p_ZZN4nnet12pooling2d_clINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_o_mode3EL_9 <= trunc_ln115_28_reg_3806;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap <= trunc_ln115_28_reg_3806;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_1 <= trunc_ln115_27_reg_3800;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_10 <= trunc_ln115_18_reg_3746;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_11 <= trunc_ln115_17_reg_3740;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_12 <= trunc_ln115_16_reg_3734;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_13 <= trunc_ln115_15_reg_3728;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_14 <= trunc_ln115_s_reg_3722;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_15 <= trunc_ln115_reg_3715;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_16 <= select_ln109_reg_3640;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_17 <= select_ln109_15_reg_3645;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_18 <= select_ln109_16_reg_3650;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_19 <= select_ln109_17_reg_3655;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_2 <= trunc_ln115_26_reg_3794;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_20 <= select_ln109_18_reg_3660;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_21 <= select_ln109_19_reg_3665;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_22 <= select_ln109_20_reg_3670;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_23 <= select_ln109_21_reg_3675;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_24 <= select_ln109_22_reg_3680;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_25 <= select_ln109_23_reg_3685;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_26 <= select_ln109_24_reg_3690;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_27 <= select_ln109_25_reg_3695;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_28 <= select_ln109_26_reg_3700;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_29 <= select_ln109_27_reg_3705;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_3 <= trunc_ln115_25_reg_3788;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_30 <= select_ln109_28_reg_3710;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_31 <= p_0_0_0_0_010984_reg_442;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_4 <= trunc_ln115_24_reg_3782;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_5 <= trunc_ln115_23_reg_3776;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_6 <= trunc_ln115_22_reg_3770;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_7 <= trunc_ln115_21_reg_3764;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_8 <= trunc_ln115_20_reg_3758;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi5ELi5EL9ap_q_mode5EL9ap_9 <= trunc_ln115_19_reg_3752;
        void_pooling2d_cl_stream_stream_array_ap_ufixed_16u_0_line_buffer_1 <= trunc_ln115_25_reg_3788;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln76_fu_2029_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        sY_1 <= ap_phi_mux_storemerge_i_phi_fu_455_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln109_fu_2155_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_4025 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_icmp_ln11186_phi_fu_435_p4 = icmp_ln111_reg_4020;
    end else begin
        ap_phi_mux_icmp_ln11186_phi_fu_435_p4 = icmp_ln11186_reg_431;
    end
end

always @ (*) begin
    if (((icmp_ln109_reg_4025 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_0_0_0_0_010984_phi_fu_445_p4 = trunc_ln115_reg_3715;
    end else begin
        ap_phi_mux_p_0_0_0_0_010984_phi_fu_445_p4 = p_0_0_0_0_010984_reg_442;
    end
end

always @ (*) begin
    if ((icmp_ln76_fu_2029_p2 == 1'd1)) begin
        if ((icmp_ln80_fu_2083_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_i_phi_fu_455_p4 = 32'd0;
        end else if ((icmp_ln80_fu_2083_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_i_phi_fu_455_p4 = select_ln86_fu_2111_p3;
        end else begin
            ap_phi_mux_storemerge_i_phi_fu_455_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_452;
        end
    end else begin
        ap_phi_mux_storemerge_i_phi_fu_455_p4 = ap_phi_reg_pp0_iter0_storemerge_i_reg_452;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'd1 == and_ln55_2_reg_3816) & (icmp_ln55_reg_3812 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op526_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_1280_p2 = (indvar_flatten3_fu_222 + 10'd1);

assign add_ln111_fu_2135_p2 = (i_iw_fu_414 + 5'd1);

assign add_ln76_fu_2023_p2 = (pX_1 + 32'd1);

assign add_ln80_fu_2077_p2 = (pY_1 + 32'd1);

assign add_ln86_fu_2105_p2 = (sY_1 + 32'd1);

assign add_ln91_fu_2041_p2 = (sX_1 + 32'd1);

assign and_ln55_2_fu_1318_p2 = (icmp_ln55_4_fu_1290_p2 & and_ln55_fu_1312_p2);

assign and_ln55_fu_1312_p2 = (icmp_ln55_6_fu_1306_p2 & icmp_ln55_5_fu_1300_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state3_pp0_stage0_iter1) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (layer4_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((layer5_out_full_n == 1'b0) & (ap_predicate_op526_write_state3 == 1'b1));
end

always @ (*) begin
    ap_condition_163 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_426 = ((icmp_ln76_fu_2029_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_i_reg_452 = 'bx;

always @ (*) begin
    ap_predicate_op526_write_state3 = ((1'd1 == and_ln55_2_reg_3816) & (icmp_ln55_reg_3812 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign i_iw_3_fu_2141_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? 5'd1 : add_ln111_fu_2135_p2);

assign icmp_ln109_fu_2155_p2 = ((indvar_flatten3_fu_222 == 10'd675) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_2149_p2 = ((i_iw_3_fu_2141_p3 == 5'd26) ? 1'b1 : 1'b0);

assign icmp_ln55_4_fu_1290_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_5_fu_1300_p2 = (($signed(pY_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_6_fu_1306_p2 = (($signed(pX_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_1270_p2 = ((sX_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln66_48_fu_1403_p2 = ((select_ln10987_fu_1395_p3 < trunc_ln115_fu_1112_p1) ? 1'b1 : 1'b0);

assign icmp_ln66_49_fu_2406_p2 = ((select_ln0_reg_3820 < select_ln0_32_reg_3826) ? 1'b1 : 1'b0);

assign icmp_ln66_50_fu_1423_p2 = ((p_0_1_0_0_011114465_fu_346 < select_ln109_28_fu_1104_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_51_fu_1443_p2 = ((p_0_1_0_0_019334_fu_282 < trunc_ln115_s_fu_1116_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_52_fu_2444_p2 = ((select_ln0_33_reg_3832 < select_ln0_34_reg_3838) ? 1'b1 : 1'b0);

assign icmp_ln66_53_fu_1463_p2 = ((p_0_2_0_0_011314763_fu_342 < select_ln109_27_fu_1096_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_54_fu_1483_p2 = ((p_0_2_0_0_019732_fu_278 < trunc_ln115_15_fu_1126_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_55_fu_2482_p2 = ((select_ln0_35_reg_3844 < select_ln0_36_reg_3850) ? 1'b1 : 1'b0);

assign icmp_ln66_56_fu_1503_p2 = ((p_0_3_0_0_011515061_fu_338 < select_ln109_26_fu_1088_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_57_fu_1523_p2 = ((p_0_3_0_0_020130_fu_274 < trunc_ln115_16_fu_1136_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_58_fu_2520_p2 = ((select_ln0_37_reg_3856 < select_ln0_38_reg_3862) ? 1'b1 : 1'b0);

assign icmp_ln66_59_fu_1543_p2 = ((p_0_4_0_0_011715359_fu_334 < select_ln109_25_fu_1080_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_60_fu_1563_p2 = ((p_0_4_0_0_020528_fu_270 < trunc_ln115_17_fu_1146_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_61_fu_2558_p2 = ((select_ln0_39_reg_3868 < select_ln0_40_reg_3874) ? 1'b1 : 1'b0);

assign icmp_ln66_62_fu_1583_p2 = ((p_0_5_0_0_011915657_fu_330 < select_ln109_24_fu_1072_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_63_fu_1603_p2 = ((p_0_5_0_0_020926_fu_266 < trunc_ln115_18_fu_1156_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_64_fu_2596_p2 = ((select_ln0_41_reg_3880 < select_ln0_42_reg_3886) ? 1'b1 : 1'b0);

assign icmp_ln66_65_fu_1623_p2 = ((p_0_6_0_0_012115955_fu_326 < select_ln109_23_fu_1064_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_66_fu_1643_p2 = ((p_0_6_0_0_021324_fu_262 < trunc_ln115_19_fu_1166_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_67_fu_2634_p2 = ((select_ln0_43_reg_3892 < select_ln0_44_reg_3898) ? 1'b1 : 1'b0);

assign icmp_ln66_68_fu_1663_p2 = ((p_0_7_0_0_012316253_fu_322 < select_ln109_22_fu_1056_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_69_fu_1683_p2 = ((p_0_7_0_0_021722_fu_258 < trunc_ln115_20_fu_1176_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_70_fu_2672_p2 = ((select_ln0_45_reg_3904 < select_ln0_46_reg_3910) ? 1'b1 : 1'b0);

assign icmp_ln66_71_fu_1703_p2 = ((p_0_8_0_0_012516551_fu_318 < select_ln109_21_fu_1048_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_72_fu_1723_p2 = ((p_0_8_0_0_022120_fu_254 < trunc_ln115_21_fu_1186_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_73_fu_2710_p2 = ((select_ln0_47_reg_3916 < select_ln0_48_reg_3922) ? 1'b1 : 1'b0);

assign icmp_ln66_74_fu_1743_p2 = ((p_0_9_0_0_012716849_fu_314 < select_ln109_20_fu_1040_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_75_fu_1763_p2 = ((p_0_9_0_0_022518_fu_250 < trunc_ln115_22_fu_1196_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_76_fu_2748_p2 = ((select_ln0_49_reg_3928 < select_ln0_50_reg_3934) ? 1'b1 : 1'b0);

assign icmp_ln66_77_fu_1783_p2 = ((p_0_10_0_0_012917147_fu_310 < select_ln109_19_fu_1032_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_78_fu_1803_p2 = ((p_0_10_0_0_022916_fu_246 < trunc_ln115_23_fu_1206_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_79_fu_2786_p2 = ((select_ln0_51_reg_3940 < select_ln0_52_reg_3946) ? 1'b1 : 1'b0);

assign icmp_ln66_80_fu_1823_p2 = ((p_0_11_0_0_013117445_fu_306 < select_ln109_18_fu_1024_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_81_fu_1843_p2 = ((p_0_11_0_0_023314_fu_242 < trunc_ln115_24_fu_1216_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_82_fu_2824_p2 = ((select_ln0_53_reg_3952 < select_ln0_54_reg_3958) ? 1'b1 : 1'b0);

assign icmp_ln66_83_fu_1863_p2 = ((p_0_12_0_0_013317743_fu_302 < select_ln109_17_fu_1016_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_84_fu_1883_p2 = ((p_0_12_0_0_023712_fu_238 < trunc_ln115_25_fu_1226_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_85_fu_2862_p2 = ((select_ln0_55_reg_3964 < select_ln0_56_reg_3970) ? 1'b1 : 1'b0);

assign icmp_ln66_86_fu_1903_p2 = ((p_0_13_0_0_013518041_fu_298 < select_ln109_16_fu_1008_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_87_fu_1923_p2 = ((p_0_13_0_0_024110_fu_234 < trunc_ln115_26_fu_1236_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_88_fu_2900_p2 = ((select_ln0_57_reg_3976 < select_ln0_58_reg_3982) ? 1'b1 : 1'b0);

assign icmp_ln66_89_fu_1943_p2 = ((p_0_14_0_0_013718339_fu_294 < select_ln109_15_fu_1000_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_90_fu_1963_p2 = ((p_0_14_0_0_02458_fu_230 < trunc_ln115_27_fu_1246_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_91_fu_2938_p2 = ((select_ln0_59_reg_3988 < select_ln0_60_reg_3994) ? 1'b1 : 1'b0);

assign icmp_ln66_92_fu_1983_p2 = ((p_0_15_0_0_013918637_fu_290 < select_ln109_fu_992_p3) ? 1'b1 : 1'b0);

assign icmp_ln66_93_fu_2003_p2 = ((p_0_15_0_0_02496_fu_226 < trunc_ln115_28_fu_1256_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_94_fu_2976_p2 = ((select_ln0_61_reg_4000 < select_ln0_62_reg_4006) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_1375_p2 = ((p_0_0_0_0_010914167_fu_350 < ap_phi_mux_p_0_0_0_0_010984_phi_fu_445_p4) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_2029_p2 = ((add_ln76_fu_2023_p2 == 32'd26) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_2083_p2 = ((add_ln80_fu_2077_p2 == 32'd26) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_2099_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign layer5_out_din = {{{{{{{{{{{{{{{{res_pack_30_fu_3008_p2}, {res_pack_29_fu_2970_p2}}, {res_pack_28_fu_2932_p2}}, {res_pack_27_fu_2894_p2}}, {res_pack_26_fu_2856_p2}}, {res_pack_25_fu_2818_p2}}, {res_pack_24_fu_2780_p2}}, {res_pack_23_fu_2742_p2}}, {res_pack_22_fu_2704_p2}}, {res_pack_21_fu_2666_p2}}, {res_pack_20_fu_2628_p2}}, {res_pack_19_fu_2590_p2}}, {res_pack_18_fu_2552_p2}}, {res_pack_17_fu_2514_p2}}, {res_pack_16_fu_2476_p2}}, {res_pack_fu_2438_p2}};

assign res_pack_16_fu_2476_p2 = (tmp_18_fu_2468_p3 ^ tmp_17_fu_2460_p3);

assign res_pack_17_fu_2514_p2 = (tmp_20_fu_2506_p3 ^ tmp_19_fu_2498_p3);

assign res_pack_18_fu_2552_p2 = (tmp_22_fu_2544_p3 ^ tmp_21_fu_2536_p3);

assign res_pack_19_fu_2590_p2 = (tmp_24_fu_2582_p3 ^ tmp_23_fu_2574_p3);

assign res_pack_20_fu_2628_p2 = (tmp_26_fu_2620_p3 ^ tmp_25_fu_2612_p3);

assign res_pack_21_fu_2666_p2 = (tmp_28_fu_2658_p3 ^ tmp_27_fu_2650_p3);

assign res_pack_22_fu_2704_p2 = (tmp_30_fu_2696_p3 ^ tmp_29_fu_2688_p3);

assign res_pack_23_fu_2742_p2 = (tmp_32_fu_2734_p3 ^ tmp_31_fu_2726_p3);

assign res_pack_24_fu_2780_p2 = (tmp_34_fu_2772_p3 ^ tmp_33_fu_2764_p3);

assign res_pack_25_fu_2818_p2 = (tmp_36_fu_2810_p3 ^ tmp_35_fu_2802_p3);

assign res_pack_26_fu_2856_p2 = (tmp_38_fu_2848_p3 ^ tmp_37_fu_2840_p3);

assign res_pack_27_fu_2894_p2 = (tmp_40_fu_2886_p3 ^ tmp_39_fu_2878_p3);

assign res_pack_28_fu_2932_p2 = (tmp_42_fu_2924_p3 ^ tmp_41_fu_2916_p3);

assign res_pack_29_fu_2970_p2 = (tmp_44_fu_2962_p3 ^ tmp_43_fu_2954_p3);

assign res_pack_30_fu_3008_p2 = (tmp_46_fu_3000_p3 ^ tmp_45_fu_2992_p3);

assign res_pack_fu_2438_p2 = (tmp_fu_2422_p3 ^ tmp_16_fu_2430_p3);

assign select_ln0_32_fu_1415_p3 = ((xor_ln66_48_fu_1409_p2[0:0] == 1'b1) ? select_ln10987_fu_1395_p3 : trunc_ln115_fu_1112_p1);

assign select_ln0_33_fu_1435_p3 = ((xor_ln66_50_fu_1429_p2[0:0] == 1'b1) ? p_0_1_0_0_011114465_fu_346 : select_ln109_28_fu_1104_p3);

assign select_ln0_34_fu_1455_p3 = ((xor_ln66_51_fu_1449_p2[0:0] == 1'b1) ? p_0_1_0_0_019334_fu_282 : trunc_ln115_s_fu_1116_p4);

assign select_ln0_35_fu_1475_p3 = ((xor_ln66_53_fu_1469_p2[0:0] == 1'b1) ? p_0_2_0_0_011314763_fu_342 : select_ln109_27_fu_1096_p3);

assign select_ln0_36_fu_1495_p3 = ((xor_ln66_54_fu_1489_p2[0:0] == 1'b1) ? p_0_2_0_0_019732_fu_278 : trunc_ln115_15_fu_1126_p4);

assign select_ln0_37_fu_1515_p3 = ((xor_ln66_56_fu_1509_p2[0:0] == 1'b1) ? p_0_3_0_0_011515061_fu_338 : select_ln109_26_fu_1088_p3);

assign select_ln0_38_fu_1535_p3 = ((xor_ln66_57_fu_1529_p2[0:0] == 1'b1) ? p_0_3_0_0_020130_fu_274 : trunc_ln115_16_fu_1136_p4);

assign select_ln0_39_fu_1555_p3 = ((xor_ln66_59_fu_1549_p2[0:0] == 1'b1) ? p_0_4_0_0_011715359_fu_334 : select_ln109_25_fu_1080_p3);

assign select_ln0_40_fu_1575_p3 = ((xor_ln66_60_fu_1569_p2[0:0] == 1'b1) ? p_0_4_0_0_020528_fu_270 : trunc_ln115_17_fu_1146_p4);

assign select_ln0_41_fu_1595_p3 = ((xor_ln66_62_fu_1589_p2[0:0] == 1'b1) ? p_0_5_0_0_011915657_fu_330 : select_ln109_24_fu_1072_p3);

assign select_ln0_42_fu_1615_p3 = ((xor_ln66_63_fu_1609_p2[0:0] == 1'b1) ? p_0_5_0_0_020926_fu_266 : trunc_ln115_18_fu_1156_p4);

assign select_ln0_43_fu_1635_p3 = ((xor_ln66_65_fu_1629_p2[0:0] == 1'b1) ? p_0_6_0_0_012115955_fu_326 : select_ln109_23_fu_1064_p3);

assign select_ln0_44_fu_1655_p3 = ((xor_ln66_66_fu_1649_p2[0:0] == 1'b1) ? p_0_6_0_0_021324_fu_262 : trunc_ln115_19_fu_1166_p4);

assign select_ln0_45_fu_1675_p3 = ((xor_ln66_68_fu_1669_p2[0:0] == 1'b1) ? p_0_7_0_0_012316253_fu_322 : select_ln109_22_fu_1056_p3);

assign select_ln0_46_fu_1695_p3 = ((xor_ln66_69_fu_1689_p2[0:0] == 1'b1) ? p_0_7_0_0_021722_fu_258 : trunc_ln115_20_fu_1176_p4);

assign select_ln0_47_fu_1715_p3 = ((xor_ln66_71_fu_1709_p2[0:0] == 1'b1) ? p_0_8_0_0_012516551_fu_318 : select_ln109_21_fu_1048_p3);

assign select_ln0_48_fu_1735_p3 = ((xor_ln66_72_fu_1729_p2[0:0] == 1'b1) ? p_0_8_0_0_022120_fu_254 : trunc_ln115_21_fu_1186_p4);

assign select_ln0_49_fu_1755_p3 = ((xor_ln66_74_fu_1749_p2[0:0] == 1'b1) ? p_0_9_0_0_012716849_fu_314 : select_ln109_20_fu_1040_p3);

assign select_ln0_50_fu_1775_p3 = ((xor_ln66_75_fu_1769_p2[0:0] == 1'b1) ? p_0_9_0_0_022518_fu_250 : trunc_ln115_22_fu_1196_p4);

assign select_ln0_51_fu_1795_p3 = ((xor_ln66_77_fu_1789_p2[0:0] == 1'b1) ? p_0_10_0_0_012917147_fu_310 : select_ln109_19_fu_1032_p3);

assign select_ln0_52_fu_1815_p3 = ((xor_ln66_78_fu_1809_p2[0:0] == 1'b1) ? p_0_10_0_0_022916_fu_246 : trunc_ln115_23_fu_1206_p4);

assign select_ln0_53_fu_1835_p3 = ((xor_ln66_80_fu_1829_p2[0:0] == 1'b1) ? p_0_11_0_0_013117445_fu_306 : select_ln109_18_fu_1024_p3);

assign select_ln0_54_fu_1855_p3 = ((xor_ln66_81_fu_1849_p2[0:0] == 1'b1) ? p_0_11_0_0_023314_fu_242 : trunc_ln115_24_fu_1216_p4);

assign select_ln0_55_fu_1875_p3 = ((xor_ln66_83_fu_1869_p2[0:0] == 1'b1) ? p_0_12_0_0_013317743_fu_302 : select_ln109_17_fu_1016_p3);

assign select_ln0_56_fu_1895_p3 = ((xor_ln66_84_fu_1889_p2[0:0] == 1'b1) ? p_0_12_0_0_023712_fu_238 : trunc_ln115_25_fu_1226_p4);

assign select_ln0_57_fu_1915_p3 = ((xor_ln66_86_fu_1909_p2[0:0] == 1'b1) ? p_0_13_0_0_013518041_fu_298 : select_ln109_16_fu_1008_p3);

assign select_ln0_58_fu_1935_p3 = ((xor_ln66_87_fu_1929_p2[0:0] == 1'b1) ? p_0_13_0_0_024110_fu_234 : trunc_ln115_26_fu_1236_p4);

assign select_ln0_59_fu_1955_p3 = ((xor_ln66_89_fu_1949_p2[0:0] == 1'b1) ? p_0_14_0_0_013718339_fu_294 : select_ln109_15_fu_1000_p3);

assign select_ln0_60_fu_1975_p3 = ((xor_ln66_90_fu_1969_p2[0:0] == 1'b1) ? p_0_14_0_0_02458_fu_230 : trunc_ln115_27_fu_1246_p4);

assign select_ln0_61_fu_1995_p3 = ((xor_ln66_92_fu_1989_p2[0:0] == 1'b1) ? p_0_15_0_0_013918637_fu_290 : select_ln109_fu_992_p3);

assign select_ln0_62_fu_2015_p3 = ((xor_ln66_93_fu_2009_p2[0:0] == 1'b1) ? p_0_15_0_0_02496_fu_226 : trunc_ln115_28_fu_1256_p4);

assign select_ln0_fu_1387_p3 = ((xor_ln66_fu_1381_p2[0:0] == 1'b1) ? p_0_0_0_0_010914167_fu_350 : ap_phi_mux_p_0_0_0_0_010984_phi_fu_445_p4);

assign select_ln10987_fu_1395_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0_0_010984_phi_fu_445_p4 : p_0_0_0_0_018936_fu_286);

assign select_ln109_15_fu_1000_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_14_0_0_02458_fu_230 : p_0_14_0_0_013770_fu_358);

assign select_ln109_16_fu_1008_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_13_0_0_024110_fu_234 : p_0_13_0_0_013571_fu_362);

assign select_ln109_17_fu_1016_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_12_0_0_023712_fu_238 : p_0_12_0_0_013372_fu_366);

assign select_ln109_18_fu_1024_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_11_0_0_023314_fu_242 : p_0_11_0_0_013173_fu_370);

assign select_ln109_19_fu_1032_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_10_0_0_022916_fu_246 : p_0_10_0_0_012974_fu_374);

assign select_ln109_20_fu_1040_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_9_0_0_022518_fu_250 : p_0_9_0_0_012775_fu_378);

assign select_ln109_21_fu_1048_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_8_0_0_022120_fu_254 : p_0_8_0_0_012576_fu_382);

assign select_ln109_22_fu_1056_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_7_0_0_021722_fu_258 : p_0_7_0_0_012377_fu_386);

assign select_ln109_23_fu_1064_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_6_0_0_021324_fu_262 : p_0_6_0_0_012178_fu_390);

assign select_ln109_24_fu_1072_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_5_0_0_020926_fu_266 : p_0_5_0_0_011979_fu_394);

assign select_ln109_25_fu_1080_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_4_0_0_020528_fu_270 : p_0_4_0_0_011780_fu_398);

assign select_ln109_26_fu_1088_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_3_0_0_020130_fu_274 : p_0_3_0_0_011581_fu_402);

assign select_ln109_27_fu_1096_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_2_0_0_019732_fu_278 : p_0_2_0_0_011382_fu_406);

assign select_ln109_28_fu_1104_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_1_0_0_019334_fu_282 : p_0_1_0_0_011183_fu_410);

assign select_ln109_fu_992_p3 = ((ap_phi_mux_icmp_ln11186_phi_fu_435_p4[0:0] == 1'b1) ? p_0_15_0_0_02496_fu_226 : p_0_15_0_0_013969_fu_354);

assign select_ln66_16_fu_2454_p3 = ((xor_ln66_52_fu_2448_p2[0:0] == 1'b1) ? select_ln0_33_reg_3832 : select_ln0_34_reg_3838);

assign select_ln66_17_fu_2492_p3 = ((xor_ln66_55_fu_2486_p2[0:0] == 1'b1) ? select_ln0_35_reg_3844 : select_ln0_36_reg_3850);

assign select_ln66_18_fu_2530_p3 = ((xor_ln66_58_fu_2524_p2[0:0] == 1'b1) ? select_ln0_37_reg_3856 : select_ln0_38_reg_3862);

assign select_ln66_19_fu_2568_p3 = ((xor_ln66_61_fu_2562_p2[0:0] == 1'b1) ? select_ln0_39_reg_3868 : select_ln0_40_reg_3874);

assign select_ln66_20_fu_2606_p3 = ((xor_ln66_64_fu_2600_p2[0:0] == 1'b1) ? select_ln0_41_reg_3880 : select_ln0_42_reg_3886);

assign select_ln66_21_fu_2644_p3 = ((xor_ln66_67_fu_2638_p2[0:0] == 1'b1) ? select_ln0_43_reg_3892 : select_ln0_44_reg_3898);

assign select_ln66_22_fu_2682_p3 = ((xor_ln66_70_fu_2676_p2[0:0] == 1'b1) ? select_ln0_45_reg_3904 : select_ln0_46_reg_3910);

assign select_ln66_23_fu_2720_p3 = ((xor_ln66_73_fu_2714_p2[0:0] == 1'b1) ? select_ln0_47_reg_3916 : select_ln0_48_reg_3922);

assign select_ln66_24_fu_2758_p3 = ((xor_ln66_76_fu_2752_p2[0:0] == 1'b1) ? select_ln0_49_reg_3928 : select_ln0_50_reg_3934);

assign select_ln66_25_fu_2796_p3 = ((xor_ln66_79_fu_2790_p2[0:0] == 1'b1) ? select_ln0_51_reg_3940 : select_ln0_52_reg_3946);

assign select_ln66_26_fu_2834_p3 = ((xor_ln66_82_fu_2828_p2[0:0] == 1'b1) ? select_ln0_53_reg_3952 : select_ln0_54_reg_3958);

assign select_ln66_27_fu_2872_p3 = ((xor_ln66_85_fu_2866_p2[0:0] == 1'b1) ? select_ln0_55_reg_3964 : select_ln0_56_reg_3970);

assign select_ln66_28_fu_2910_p3 = ((xor_ln66_88_fu_2904_p2[0:0] == 1'b1) ? select_ln0_57_reg_3976 : select_ln0_58_reg_3982);

assign select_ln66_29_fu_2948_p3 = ((xor_ln66_91_fu_2942_p2[0:0] == 1'b1) ? select_ln0_59_reg_3988 : select_ln0_60_reg_3994);

assign select_ln66_30_fu_2986_p3 = ((xor_ln66_94_fu_2980_p2[0:0] == 1'b1) ? select_ln0_61_reg_4000 : select_ln0_62_reg_4006);

assign select_ln66_fu_2416_p3 = ((xor_ln66_49_fu_2410_p2[0:0] == 1'b1) ? select_ln0_reg_3820 : select_ln0_32_reg_3826);

assign select_ln86_fu_2111_p3 = ((icmp_ln86_fu_2099_p2[0:0] == 1'b1) ? 32'd0 : add_ln86_fu_2105_p2);

assign select_ln91_fu_2047_p3 = ((icmp_ln55_fu_1270_p2[0:0] == 1'b1) ? 32'd0 : add_ln91_fu_2041_p2);

assign start_out = real_start;

assign tmp_16_fu_2430_p3 = select_ln66_fu_2416_p3[32'd3];

assign tmp_17_fu_2460_p3 = select_ln66_16_fu_2454_p3[32'd4];

assign tmp_18_fu_2468_p3 = select_ln66_16_fu_2454_p3[32'd3];

assign tmp_19_fu_2498_p3 = select_ln66_17_fu_2492_p3[32'd4];

assign tmp_20_fu_2506_p3 = select_ln66_17_fu_2492_p3[32'd3];

assign tmp_21_fu_2536_p3 = select_ln66_18_fu_2530_p3[32'd4];

assign tmp_22_fu_2544_p3 = select_ln66_18_fu_2530_p3[32'd3];

assign tmp_23_fu_2574_p3 = select_ln66_19_fu_2568_p3[32'd4];

assign tmp_24_fu_2582_p3 = select_ln66_19_fu_2568_p3[32'd3];

assign tmp_25_fu_2612_p3 = select_ln66_20_fu_2606_p3[32'd4];

assign tmp_26_fu_2620_p3 = select_ln66_20_fu_2606_p3[32'd3];

assign tmp_27_fu_2650_p3 = select_ln66_21_fu_2644_p3[32'd4];

assign tmp_28_fu_2658_p3 = select_ln66_21_fu_2644_p3[32'd3];

assign tmp_29_fu_2688_p3 = select_ln66_22_fu_2682_p3[32'd4];

assign tmp_30_fu_2696_p3 = select_ln66_22_fu_2682_p3[32'd3];

assign tmp_31_fu_2726_p3 = select_ln66_23_fu_2720_p3[32'd4];

assign tmp_32_fu_2734_p3 = select_ln66_23_fu_2720_p3[32'd3];

assign tmp_33_fu_2764_p3 = select_ln66_24_fu_2758_p3[32'd4];

assign tmp_34_fu_2772_p3 = select_ln66_24_fu_2758_p3[32'd3];

assign tmp_35_fu_2802_p3 = select_ln66_25_fu_2796_p3[32'd4];

assign tmp_36_fu_2810_p3 = select_ln66_25_fu_2796_p3[32'd3];

assign tmp_37_fu_2840_p3 = select_ln66_26_fu_2834_p3[32'd4];

assign tmp_38_fu_2848_p3 = select_ln66_26_fu_2834_p3[32'd3];

assign tmp_39_fu_2878_p3 = select_ln66_27_fu_2872_p3[32'd4];

assign tmp_40_fu_2886_p3 = select_ln66_27_fu_2872_p3[32'd3];

assign tmp_41_fu_2916_p3 = select_ln66_28_fu_2910_p3[32'd4];

assign tmp_42_fu_2924_p3 = select_ln66_28_fu_2910_p3[32'd3];

assign tmp_43_fu_2954_p3 = select_ln66_29_fu_2948_p3[32'd4];

assign tmp_44_fu_2962_p3 = select_ln66_29_fu_2948_p3[32'd3];

assign tmp_45_fu_2992_p3 = select_ln66_30_fu_2986_p3[32'd4];

assign tmp_46_fu_3000_p3 = select_ln66_30_fu_2986_p3[32'd3];

assign tmp_fu_2422_p3 = select_ln66_fu_2416_p3[32'd4];

assign trunc_ln115_15_fu_1126_p4 = {{layer4_out_dout[14:10]}};

assign trunc_ln115_16_fu_1136_p4 = {{layer4_out_dout[19:15]}};

assign trunc_ln115_17_fu_1146_p4 = {{layer4_out_dout[24:20]}};

assign trunc_ln115_18_fu_1156_p4 = {{layer4_out_dout[29:25]}};

assign trunc_ln115_19_fu_1166_p4 = {{layer4_out_dout[34:30]}};

assign trunc_ln115_20_fu_1176_p4 = {{layer4_out_dout[39:35]}};

assign trunc_ln115_21_fu_1186_p4 = {{layer4_out_dout[44:40]}};

assign trunc_ln115_22_fu_1196_p4 = {{layer4_out_dout[49:45]}};

assign trunc_ln115_23_fu_1206_p4 = {{layer4_out_dout[54:50]}};

assign trunc_ln115_24_fu_1216_p4 = {{layer4_out_dout[59:55]}};

assign trunc_ln115_25_fu_1226_p4 = {{layer4_out_dout[64:60]}};

assign trunc_ln115_26_fu_1236_p4 = {{layer4_out_dout[69:65]}};

assign trunc_ln115_27_fu_1246_p4 = {{layer4_out_dout[74:70]}};

assign trunc_ln115_28_fu_1256_p4 = {{layer4_out_dout[79:75]}};

assign trunc_ln115_fu_1112_p1 = layer4_out_dout[4:0];

assign trunc_ln115_s_fu_1116_p4 = {{layer4_out_dout[9:5]}};

assign xor_ln66_48_fu_1409_p2 = (icmp_ln66_48_fu_1403_p2 ^ 1'd1);

assign xor_ln66_49_fu_2410_p2 = (icmp_ln66_49_fu_2406_p2 ^ 1'd1);

assign xor_ln66_50_fu_1429_p2 = (icmp_ln66_50_fu_1423_p2 ^ 1'd1);

assign xor_ln66_51_fu_1449_p2 = (icmp_ln66_51_fu_1443_p2 ^ 1'd1);

assign xor_ln66_52_fu_2448_p2 = (icmp_ln66_52_fu_2444_p2 ^ 1'd1);

assign xor_ln66_53_fu_1469_p2 = (icmp_ln66_53_fu_1463_p2 ^ 1'd1);

assign xor_ln66_54_fu_1489_p2 = (icmp_ln66_54_fu_1483_p2 ^ 1'd1);

assign xor_ln66_55_fu_2486_p2 = (icmp_ln66_55_fu_2482_p2 ^ 1'd1);

assign xor_ln66_56_fu_1509_p2 = (icmp_ln66_56_fu_1503_p2 ^ 1'd1);

assign xor_ln66_57_fu_1529_p2 = (icmp_ln66_57_fu_1523_p2 ^ 1'd1);

assign xor_ln66_58_fu_2524_p2 = (icmp_ln66_58_fu_2520_p2 ^ 1'd1);

assign xor_ln66_59_fu_1549_p2 = (icmp_ln66_59_fu_1543_p2 ^ 1'd1);

assign xor_ln66_60_fu_1569_p2 = (icmp_ln66_60_fu_1563_p2 ^ 1'd1);

assign xor_ln66_61_fu_2562_p2 = (icmp_ln66_61_fu_2558_p2 ^ 1'd1);

assign xor_ln66_62_fu_1589_p2 = (icmp_ln66_62_fu_1583_p2 ^ 1'd1);

assign xor_ln66_63_fu_1609_p2 = (icmp_ln66_63_fu_1603_p2 ^ 1'd1);

assign xor_ln66_64_fu_2600_p2 = (icmp_ln66_64_fu_2596_p2 ^ 1'd1);

assign xor_ln66_65_fu_1629_p2 = (icmp_ln66_65_fu_1623_p2 ^ 1'd1);

assign xor_ln66_66_fu_1649_p2 = (icmp_ln66_66_fu_1643_p2 ^ 1'd1);

assign xor_ln66_67_fu_2638_p2 = (icmp_ln66_67_fu_2634_p2 ^ 1'd1);

assign xor_ln66_68_fu_1669_p2 = (icmp_ln66_68_fu_1663_p2 ^ 1'd1);

assign xor_ln66_69_fu_1689_p2 = (icmp_ln66_69_fu_1683_p2 ^ 1'd1);

assign xor_ln66_70_fu_2676_p2 = (icmp_ln66_70_fu_2672_p2 ^ 1'd1);

assign xor_ln66_71_fu_1709_p2 = (icmp_ln66_71_fu_1703_p2 ^ 1'd1);

assign xor_ln66_72_fu_1729_p2 = (icmp_ln66_72_fu_1723_p2 ^ 1'd1);

assign xor_ln66_73_fu_2714_p2 = (icmp_ln66_73_fu_2710_p2 ^ 1'd1);

assign xor_ln66_74_fu_1749_p2 = (icmp_ln66_74_fu_1743_p2 ^ 1'd1);

assign xor_ln66_75_fu_1769_p2 = (icmp_ln66_75_fu_1763_p2 ^ 1'd1);

assign xor_ln66_76_fu_2752_p2 = (icmp_ln66_76_fu_2748_p2 ^ 1'd1);

assign xor_ln66_77_fu_1789_p2 = (icmp_ln66_77_fu_1783_p2 ^ 1'd1);

assign xor_ln66_78_fu_1809_p2 = (icmp_ln66_78_fu_1803_p2 ^ 1'd1);

assign xor_ln66_79_fu_2790_p2 = (icmp_ln66_79_fu_2786_p2 ^ 1'd1);

assign xor_ln66_80_fu_1829_p2 = (icmp_ln66_80_fu_1823_p2 ^ 1'd1);

assign xor_ln66_81_fu_1849_p2 = (icmp_ln66_81_fu_1843_p2 ^ 1'd1);

assign xor_ln66_82_fu_2828_p2 = (icmp_ln66_82_fu_2824_p2 ^ 1'd1);

assign xor_ln66_83_fu_1869_p2 = (icmp_ln66_83_fu_1863_p2 ^ 1'd1);

assign xor_ln66_84_fu_1889_p2 = (icmp_ln66_84_fu_1883_p2 ^ 1'd1);

assign xor_ln66_85_fu_2866_p2 = (icmp_ln66_85_fu_2862_p2 ^ 1'd1);

assign xor_ln66_86_fu_1909_p2 = (icmp_ln66_86_fu_1903_p2 ^ 1'd1);

assign xor_ln66_87_fu_1929_p2 = (icmp_ln66_87_fu_1923_p2 ^ 1'd1);

assign xor_ln66_88_fu_2904_p2 = (icmp_ln66_88_fu_2900_p2 ^ 1'd1);

assign xor_ln66_89_fu_1949_p2 = (icmp_ln66_89_fu_1943_p2 ^ 1'd1);

assign xor_ln66_90_fu_1969_p2 = (icmp_ln66_90_fu_1963_p2 ^ 1'd1);

assign xor_ln66_91_fu_2942_p2 = (icmp_ln66_91_fu_2938_p2 ^ 1'd1);

assign xor_ln66_92_fu_1989_p2 = (icmp_ln66_92_fu_1983_p2 ^ 1'd1);

assign xor_ln66_93_fu_2009_p2 = (icmp_ln66_93_fu_2003_p2 ^ 1'd1);

assign xor_ln66_94_fu_2980_p2 = (icmp_ln66_94_fu_2976_p2 ^ 1'd1);

assign xor_ln66_fu_1381_p2 = (icmp_ln66_fu_1375_p2 ^ 1'd1);

endmodule //myproject_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_s
