-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    input_layer_1_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    layer13_out_TDATA : OUT STD_LOGIC_VECTOR (159 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_layer_1_TVALID : IN STD_LOGIC;
    input_layer_1_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    layer13_out_TVALID : OUT STD_LOGIC;
    layer13_out_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject_myproject,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=2362,HLS_SYN_TPT=2352,HLS_SYN_MEM=27,HLS_SYN_DSP=0,HLS_SYN_FF=10846,HLS_SYN_LUT=64523,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_out : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_input_layer_1_TREADY : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_din : STD_LOGIC_VECTOR (79 downto 0);
    signal conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_write : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer3_out_read : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_din : STD_LOGIC_VECTOR (79 downto 0);
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_write : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_out : STD_LOGIC;
    signal relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_write : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_start : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_done : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_continue : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_idle : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_ready : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_out : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_write : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer4_out_read : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_din : STD_LOGIC_VECTOR (15 downto 0);
    signal pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_out : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer5_out_read : STD_LOGIC;
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_din : STD_LOGIC_VECTOR (143 downto 0);
    signal conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_start : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_done : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_continue : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_idle : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_ready : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer7_out_read : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_din : STD_LOGIC_VECTOR (127 downto 0);
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_write : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_out : STD_LOGIC;
    signal relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_write : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_start : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_done : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_continue : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_idle : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_ready : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_out : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_write : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer8_out_read : STD_LOGIC;
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_write : STD_LOGIC;
    signal dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_start : STD_LOGIC;
    signal dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_done : STD_LOGIC;
    signal dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_continue : STD_LOGIC;
    signal dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_idle : STD_LOGIC;
    signal dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_ready : STD_LOGIC;
    signal dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer9_out_read : STD_LOGIC;
    signal dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TDATA : STD_LOGIC_VECTOR (159 downto 0);
    signal dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TVALID : STD_LOGIC;
    signal layer3_out_full_n : STD_LOGIC;
    signal layer3_out_dout : STD_LOGIC_VECTOR (79 downto 0);
    signal layer3_out_empty_n : STD_LOGIC;
    signal layer3_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal layer3_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal layer4_out_full_n : STD_LOGIC;
    signal layer4_out_dout : STD_LOGIC_VECTOR (79 downto 0);
    signal layer4_out_empty_n : STD_LOGIC;
    signal layer4_out_num_data_valid : STD_LOGIC_VECTOR (10 downto 0);
    signal layer4_out_fifo_cap : STD_LOGIC_VECTOR (10 downto 0);
    signal layer5_out_full_n : STD_LOGIC;
    signal layer5_out_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer5_out_empty_n : STD_LOGIC;
    signal layer5_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal layer5_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal layer7_out_full_n : STD_LOGIC;
    signal layer7_out_dout : STD_LOGIC_VECTOR (143 downto 0);
    signal layer7_out_empty_n : STD_LOGIC;
    signal layer7_out_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal layer7_out_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal layer8_out_full_n : STD_LOGIC;
    signal layer8_out_dout : STD_LOGIC_VECTOR (127 downto 0);
    signal layer8_out_empty_n : STD_LOGIC;
    signal layer8_out_num_data_valid : STD_LOGIC_VECTOR (7 downto 0);
    signal layer8_out_fifo_cap : STD_LOGIC_VECTOR (7 downto 0);
    signal layer9_out_full_n : STD_LOGIC;
    signal layer9_out_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal layer9_out_empty_n : STD_LOGIC;
    signal layer9_out_num_data_valid : STD_LOGIC_VECTOR (5 downto 0);
    signal layer9_out_fifo_cap : STD_LOGIC_VECTOR (5 downto 0);
    signal start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_empty_n : STD_LOGIC;
    signal start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_full_n : STD_LOGIC;
    signal start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_empty_n : STD_LOGIC;
    signal start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_full_n : STD_LOGIC;
    signal start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_empty_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_full_n : STD_LOGIC;
    signal start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_empty_n : STD_LOGIC;
    signal start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_full_n : STD_LOGIC;
    signal start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_empty_n : STD_LOGIC;
    signal start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_full_n : STD_LOGIC;
    signal start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_empty_n : STD_LOGIC;

    component myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        input_layer_1_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        input_layer_1_TVALID : IN STD_LOGIC;
        input_layer_1_TREADY : OUT STD_LOGIC;
        layer3_out_din : OUT STD_LOGIC_VECTOR (79 downto 0);
        layer3_out_full_n : IN STD_LOGIC;
        layer3_out_write : OUT STD_LOGIC;
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer3_out_dout : IN STD_LOGIC_VECTOR (79 downto 0);
        layer3_out_empty_n : IN STD_LOGIC;
        layer3_out_read : OUT STD_LOGIC;
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        layer4_out_din : OUT STD_LOGIC_VECTOR (79 downto 0);
        layer4_out_full_n : IN STD_LOGIC;
        layer4_out_write : OUT STD_LOGIC;
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component myproject_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer4_out_dout : IN STD_LOGIC_VECTOR (79 downto 0);
        layer4_out_empty_n : IN STD_LOGIC;
        layer4_out_read : OUT STD_LOGIC;
        layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        layer5_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        layer5_out_full_n : IN STD_LOGIC;
        layer5_out_write : OUT STD_LOGIC;
        layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component myproject_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer5_out_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        layer5_out_empty_n : IN STD_LOGIC;
        layer5_out_read : OUT STD_LOGIC;
        layer5_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        layer5_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        layer7_out_din : OUT STD_LOGIC_VECTOR (143 downto 0);
        layer7_out_full_n : IN STD_LOGIC;
        layer7_out_write : OUT STD_LOGIC;
        layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer7_out_dout : IN STD_LOGIC_VECTOR (143 downto 0);
        layer7_out_empty_n : IN STD_LOGIC;
        layer7_out_read : OUT STD_LOGIC;
        layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        layer8_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        layer8_out_full_n : IN STD_LOGIC;
        layer8_out_write : OUT STD_LOGIC;
        layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component myproject_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        layer8_out_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        layer8_out_empty_n : IN STD_LOGIC;
        layer8_out_read : OUT STD_LOGIC;
        layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        layer9_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        layer9_out_full_n : IN STD_LOGIC;
        layer9_out_write : OUT STD_LOGIC;
        layer9_out_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        layer9_out_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component myproject_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        layer9_out_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        layer9_out_empty_n : IN STD_LOGIC;
        layer9_out_read : OUT STD_LOGIC;
        layer9_out_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
        layer9_out_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
        layer13_out_TDATA : OUT STD_LOGIC_VECTOR (159 downto 0);
        layer13_out_TVALID : OUT STD_LOGIC;
        layer13_out_TREADY : IN STD_LOGIC );
    end component;


    component myproject_fifo_w80_d676_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (79 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (79 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_fifo_w16_d169_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component myproject_fifo_w144_d121_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (143 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (143 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component myproject_fifo_w128_d121_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (127 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (127 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component myproject_fifo_w32_d25_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (5 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component myproject_start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4JfO IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7KfY IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component myproject_start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0 : component myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_start,
        start_full_n => start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_full_n,
        ap_done => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_done,
        ap_continue => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_continue,
        ap_idle => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_idle,
        ap_ready => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_ready,
        start_out => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_out,
        start_write => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_write,
        input_layer_1_TDATA => input_layer_1_TDATA,
        input_layer_1_TVALID => input_layer_1_TVALID,
        input_layer_1_TREADY => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_input_layer_1_TREADY,
        layer3_out_din => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_din,
        layer3_out_full_n => layer3_out_full_n,
        layer3_out_write => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_write,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap);

    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0 : component myproject_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_start,
        start_full_n => start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_full_n,
        ap_done => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_done,
        ap_continue => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_continue,
        ap_idle => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_idle,
        ap_ready => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_ready,
        layer3_out_dout => layer3_out_dout,
        layer3_out_empty_n => layer3_out_empty_n,
        layer3_out_read => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer3_out_read,
        layer3_out_num_data_valid => layer3_out_num_data_valid,
        layer3_out_fifo_cap => layer3_out_fifo_cap,
        layer4_out_din => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_din,
        layer4_out_full_n => layer4_out_full_n,
        layer4_out_write => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_write,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        start_out => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_out,
        start_write => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_write);

    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0 : component myproject_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_start,
        start_full_n => start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_full_n,
        ap_done => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_done,
        ap_continue => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_continue,
        ap_idle => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_idle,
        ap_ready => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_ready,
        start_out => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_out,
        start_write => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_write,
        layer4_out_dout => layer4_out_dout,
        layer4_out_empty_n => layer4_out_empty_n,
        layer4_out_read => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer4_out_read,
        layer4_out_num_data_valid => layer4_out_num_data_valid,
        layer4_out_fifo_cap => layer4_out_fifo_cap,
        layer5_out_din => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_din,
        layer5_out_full_n => layer5_out_full_n,
        layer5_out_write => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_write,
        layer5_out_num_data_valid => layer5_out_num_data_valid,
        layer5_out_fifo_cap => layer5_out_fifo_cap);

    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0 : component myproject_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_start,
        start_full_n => start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_full_n,
        ap_done => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_done,
        ap_continue => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_continue,
        ap_idle => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_idle,
        ap_ready => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_ready,
        start_out => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_out,
        start_write => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_write,
        layer5_out_dout => layer5_out_dout,
        layer5_out_empty_n => layer5_out_empty_n,
        layer5_out_read => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer5_out_read,
        layer5_out_num_data_valid => layer5_out_num_data_valid,
        layer5_out_fifo_cap => layer5_out_fifo_cap,
        layer7_out_din => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_din,
        layer7_out_full_n => layer7_out_full_n,
        layer7_out_write => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_write,
        layer7_out_num_data_valid => layer7_out_num_data_valid,
        layer7_out_fifo_cap => layer7_out_fifo_cap);

    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0 : component myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_start,
        start_full_n => start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_full_n,
        ap_done => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_done,
        ap_continue => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_continue,
        ap_idle => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_idle,
        ap_ready => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_ready,
        layer7_out_dout => layer7_out_dout,
        layer7_out_empty_n => layer7_out_empty_n,
        layer7_out_read => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer7_out_read,
        layer7_out_num_data_valid => layer7_out_num_data_valid,
        layer7_out_fifo_cap => layer7_out_fifo_cap,
        layer8_out_din => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_din,
        layer8_out_full_n => layer8_out_full_n,
        layer8_out_write => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_write,
        layer8_out_num_data_valid => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid,
        layer8_out_fifo_cap => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap,
        start_out => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_out,
        start_write => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_write);

    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0 : component myproject_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_start,
        start_full_n => start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_full_n,
        ap_done => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_done,
        ap_continue => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_continue,
        ap_idle => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_idle,
        ap_ready => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_ready,
        start_out => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_out,
        start_write => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_write,
        layer8_out_dout => layer8_out_dout,
        layer8_out_empty_n => layer8_out_empty_n,
        layer8_out_read => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer8_out_read,
        layer8_out_num_data_valid => layer8_out_num_data_valid,
        layer8_out_fifo_cap => layer8_out_fifo_cap,
        layer9_out_din => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_din,
        layer9_out_full_n => layer9_out_full_n,
        layer9_out_write => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_write,
        layer9_out_num_data_valid => layer9_out_num_data_valid,
        layer9_out_fifo_cap => layer9_out_fifo_cap);

    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0 : component myproject_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_start,
        ap_done => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_done,
        ap_continue => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_continue,
        ap_idle => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_idle,
        ap_ready => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_ready,
        layer9_out_dout => layer9_out_dout,
        layer9_out_empty_n => layer9_out_empty_n,
        layer9_out_read => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer9_out_read,
        layer9_out_num_data_valid => layer9_out_num_data_valid,
        layer9_out_fifo_cap => layer9_out_fifo_cap,
        layer13_out_TDATA => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TDATA,
        layer13_out_TVALID => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TVALID,
        layer13_out_TREADY => layer13_out_TREADY);

    layer3_out_U : component myproject_fifo_w80_d676_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_din,
        if_full_n => layer3_out_full_n,
        if_write => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_layer3_out_write,
        if_dout => layer3_out_dout,
        if_empty_n => layer3_out_empty_n,
        if_read => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer3_out_read,
        if_num_data_valid => layer3_out_num_data_valid,
        if_fifo_cap => layer3_out_fifo_cap);

    layer4_out_U : component myproject_fifo_w80_d676_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_din,
        if_full_n => layer4_out_full_n,
        if_write => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_layer4_out_write,
        if_dout => layer4_out_dout,
        if_empty_n => layer4_out_empty_n,
        if_read => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer4_out_read,
        if_num_data_valid => layer4_out_num_data_valid,
        if_fifo_cap => layer4_out_fifo_cap);

    layer5_out_U : component myproject_fifo_w16_d169_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_din,
        if_full_n => layer5_out_full_n,
        if_write => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_layer5_out_write,
        if_dout => layer5_out_dout,
        if_empty_n => layer5_out_empty_n,
        if_read => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer5_out_read,
        if_num_data_valid => layer5_out_num_data_valid,
        if_fifo_cap => layer5_out_fifo_cap);

    layer7_out_U : component myproject_fifo_w144_d121_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_din,
        if_full_n => layer7_out_full_n,
        if_write => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_layer7_out_write,
        if_dout => layer7_out_dout,
        if_empty_n => layer7_out_empty_n,
        if_read => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer7_out_read,
        if_num_data_valid => layer7_out_num_data_valid,
        if_fifo_cap => layer7_out_fifo_cap);

    layer8_out_U : component myproject_fifo_w128_d121_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_din,
        if_full_n => layer8_out_full_n,
        if_write => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_write,
        if_dout => layer8_out_dout,
        if_empty_n => layer8_out_empty_n,
        if_read => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer8_out_read,
        if_num_data_valid => layer8_out_num_data_valid,
        if_fifo_cap => layer8_out_fifo_cap);

    layer9_out_U : component myproject_fifo_w32_d25_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_din,
        if_full_n => layer9_out_full_n,
        if_write => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_layer9_out_write,
        if_dout => layer9_out_dout,
        if_empty_n => layer9_out_empty_n,
        if_read => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer9_out_read,
        if_num_data_valid => layer9_out_num_data_valid,
        if_fifo_cap => layer9_out_fifo_cap);

    start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4JfO_U : component myproject_start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4JfO
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_din,
        if_full_n => start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_full_n,
        if_write => conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_start_write,
        if_dout => start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_dout,
        if_empty_n => start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_empty_n,
        if_read => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_ready);

    start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_U : component myproject_start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_din,
        if_full_n => start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_full_n,
        if_write => relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_start_write,
        if_dout => start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_dout,
        if_empty_n => start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_empty_n,
        if_read => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_ready);

    start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7KfY_U : component myproject_start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7KfY
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_din,
        if_full_n => start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_full_n,
        if_write => pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_start_write,
        if_dout => start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_dout,
        if_empty_n => start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_empty_n,
        if_read => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_ready);

    start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_U : component myproject_start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_din,
        if_full_n => start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_full_n,
        if_write => conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_start_write,
        if_dout => start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_dout,
        if_empty_n => start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_empty_n,
        if_read => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_ready);

    start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_U : component myproject_start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_din,
        if_full_n => start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_full_n,
        if_write => relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_start_write,
        if_dout => start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_dout,
        if_empty_n => start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_empty_n,
        if_read => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_ready);

    start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_U : component myproject_start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_din,
        if_full_n => start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_full_n,
        if_write => pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_start_write,
        if_dout => start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_dout,
        if_empty_n => start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_empty_n,
        if_read => dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_ready);




    ap_done <= dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_done;
    ap_idle <= (relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_idle and relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_idle and pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_idle and pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_idle and dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_idle and conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_idle and conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_idle);
    ap_ready <= conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_continue <= ap_const_logic_1;
    conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_ap_start <= start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_empty_n;
    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_continue <= ap_const_logic_1;
    conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_ap_start <= ap_start;
    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_continue <= ap_const_logic_1;
    dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_ap_start <= start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_empty_n;
    input_layer_1_TREADY <= conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_U0_input_layer_1_TREADY;
    layer13_out_TDATA <= dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TDATA;
    layer13_out_TVALID <= dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_layer13_out_TVALID;
    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_continue <= ap_const_logic_1;
    pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_ap_start <= start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_empty_n;
    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_continue <= ap_const_logic_1;
    pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_ap_start <= start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_empty_n;
    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_ap_start <= start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_empty_n;
    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(layer8_out_fifo_cap),8))),32));
    relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_layer8_out_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(layer8_out_num_data_valid),8))),32));
    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_continue <= ap_const_logic_1;
    relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_ap_start <= start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_empty_n;
    start_for_conv_2d_cl_array_ap_ufixed_16u_array_ap_fixed_9_9_5_3_0_16u_config7_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_dense_array_ap_ufixed_16u_array_ap_fixed_15_11_5_3_0_10u_config13_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_pooling2d_cl_array_array_ap_ufixed_1_5_0_3_0_16u_config5_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_pooling2d_cl_array_array_ap_ufixed_2_6_0_3_0_16u_config9_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_8_5_3_0_16u_relu_config8_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_relu_array_ap_ufixed_16u_array_ap_ufixed_5_5_5_3_0_16u_relu_config4_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
