-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    input_layer_1_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    input_layer_1_TVALID : IN STD_LOGIC;
    input_layer_1_TREADY : OUT STD_LOGIC;
    layer3_out_din : OUT STD_LOGIC_VECTOR (79 downto 0);
    layer3_out_full_n : IN STD_LOGIC;
    layer3_out_write : OUT STD_LOGIC;
    layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0) );
end;


architecture behav of myproject_conv_2d_cl_array_ap_ufixed_1u_array_ap_ufixed_5_5_5_3_0_16u_config3_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_30F : STD_LOGIC_VECTOR (9 downto 0) := "1100001111";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n : STD_LOGIC;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal icmp_ln25_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal input_layer_1_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal layer3_out_blk_n : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_done : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_idle : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ready : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_in_elem_0_0_0_0_0_val : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_din : STD_LOGIC_VECTOR (79 downto 0);
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_write : STD_LOGIC;
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce : STD_LOGIC;
    signal ap_block_state2_pp0_stage1_iter0_ignore_call6 : BOOLEAN;
    signal grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal indvar_flatten2_fu_70 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln25_fu_128_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal regslice_both_input_layer_1_U_apdone_blk : STD_LOGIC;
    signal input_layer_1_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal input_layer_1_TVALID_int_regslice : STD_LOGIC;
    signal input_layer_1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_layer_1_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_elem_0_0_0_0_0_val : IN STD_LOGIC_VECTOR (0 downto 0);
        layer3_out_din : OUT STD_LOGIC_VECTOR (79 downto 0);
        layer3_out_full_n : IN STD_LOGIC;
        layer3_out_write : OUT STD_LOGIC;
        layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        layer3_out_blk_n : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC );
    end component;


    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component myproject_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80 : component myproject_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start,
        ap_done => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_done,
        ap_idle => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_idle,
        ap_ready => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ready,
        in_elem_0_0_0_0_0_val => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_in_elem_0_0_0_0_0_val,
        layer3_out_din => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_din,
        layer3_out_full_n => layer3_out_full_n,
        layer3_out_write => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_write,
        layer3_out_num_data_valid => ap_const_lv11_0,
        layer3_out_fifo_cap => ap_const_lv11_0,
        layer3_out_blk_n => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n,
        ap_ce => grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce);

    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_input_layer_1_U : component myproject_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_layer_1_TDATA,
        vld_in => input_layer_1_TVALID,
        ack_in => regslice_both_input_layer_1_U_ack_in,
        data_out => input_layer_1_TDATA_int_regslice,
        vld_out => input_layer_1_TVALID_int_regslice,
        ack_out => input_layer_1_TREADY_int_regslice,
        apdone_blk => regslice_both_input_layer_1_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ready = ap_const_logic_1)) then 
                    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten2_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
                indvar_flatten2_fu_70 <= ap_const_lv10_0;
            elsif (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                indvar_flatten2_fu_70 <= add_ln25_fu_128_p2;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_block_state3_pp0_stage2_iter0, ap_CS_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage1_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln25_fu_128_p2 <= std_logic_vector(unsigned(indvar_flatten2_fu_70) + unsigned(ap_const_lv10_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_pp0_stage1_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_pp0_stage1_iter0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_pp0_stage2_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_pp0_stage2_iter0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_pp0_stage1_iter0_assign_proc : process(input_layer_1_TVALID_int_regslice)
    begin
                ap_block_state2_pp0_stage1_iter0 <= (input_layer_1_TVALID_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state2_pp0_stage1_iter0_ignore_call6_assign_proc : process(input_layer_1_TVALID_int_regslice)
    begin
                ap_block_state2_pp0_stage1_iter0_ignore_call6 <= (input_layer_1_TVALID_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n)
    begin
                ap_block_state3_pp0_stage2_iter0 <= (grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_pp0_stage2_iter0, icmp_ln25_fu_134_p2)
    begin
        if (((icmp_ln25_fu_134_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_pp0_stage2_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state3, ap_block_state3_pp0_stage2_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state3_pp0_stage2_iter0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state2, ap_block_state2_pp0_stage1_iter0_ignore_call6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0_ignore_call6) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce <= ap_const_logic_1;
        else 
            grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start <= grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_ap_start_reg;
    grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_in_elem_0_0_0_0_0_val <= input_layer_1_TDATA_int_regslice(1 - 1 downto 0);
    icmp_ln25_fu_134_p2 <= "1" when (indvar_flatten2_fu_70 = ap_const_lv10_30F) else "0";

    input_layer_1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, input_layer_1_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_layer_1_TDATA_blk_n <= input_layer_1_TVALID_int_regslice;
        else 
            input_layer_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_layer_1_TREADY <= regslice_both_input_layer_1_U_ack_in;

    input_layer_1_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_pp0_stage1_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_pp0_stage1_iter0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input_layer_1_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_layer_1_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    layer3_out_blk_n_assign_proc : process(ap_CS_fsm_state3, grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            layer3_out_blk_n <= grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_blk_n;
        else 
            layer3_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer3_out_din <= grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_din;
    layer3_out_write <= grp_compute_output_buffer_2d_array_array_ap_ufixed_5_5_5_3_0_16u_config3_s_fu_80_layer3_out_write;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
